### ISSUE TITLE
Player glitches into houses

### ISSUE THREAD

**Issue by maitian352** [maitian352/Meadow-Guarder#1]
When walking around, you might glitch into a house, where you are underneath a roof but above the house.

**Comment by maitian352** [comment]
We are making a new map with Above0 and Above1 instead of the old Deco1 and Deco2, which will hopefully fix this issue.

**Comment by maitian352** [comment]
This has been fixed in 080f3a.

**Comment by definitely-nobody-is-here** [comment]
aaaaaaaaaaaa furst isue
