### ISSUE TITLE
If you move the player to the edge of the map and zoom out, you will see the player's health bar sticking out of the map.

### ISSUE THREAD

**Issue by Suvanth-Erranki** [maitian352/Meadow-Guarder#100]
![image](https://user-images.githubusercontent.com/63676047/98819490-d5d71f80-2424-11eb-97e5-d250b417f3e1.png)

**Comment by Suvanth-Erranki** [comment]
#100th issue!

**Comment by maitian352** [comment]
Why is this an issue?
What is it supposed to look like?

**Comment by maitian352** [comment]
@Suvanth-Erranki So should the player head just disappear?

**Comment by Suvanth-Erranki** [comment]
No, if the player moves upwards, their head should stop at the edge of
the map - it shouldn't dissappear or go over the top.

**Comment by maitian352** [comment]
But it would look weird if the player moves up and the head can't go over and the legs never touch the top.

**Comment by Suvanth-Erranki** [comment]
It also looks weird if the player's head is in the middle of a black emtpy void.

**Comment by maitian352** [comment]
Well, which is weirder, not being able to reach the top of the screen, or having the player head stick out when you zoom out?

**Comment by Suvanth-Erranki** [comment]
Yeah I know, so just find a way to detect if the player is zooming out
and then make their head go under.

**Comment by maitian352** [comment]
Go under what?

**Comment by Suvanth-Erranki** [comment]
Go under the blackness.

**Comment by maitian352** [comment]
Ok.
