### ISSUE TITLE
The monster can move over the top of the NPC.

### ISSUE THREAD

**Issue by Suvanth-Erranki** [maitian352/Meadow-Guarder#101]
![image](https://user-images.githubusercontent.com/63676047/98838219-d8913f00-243b-11eb-897d-a5b6938b4484.png)
I'm sorry but it was hard to get a better picture.

**Comment by maitian352** [comment]
The monster is behind the NPC, not on top.

**Comment by Suvanth-Erranki** [comment]
Okay.
