### ISSUE TITLE
 READ THIS SP there is a guy named marcusantor that is spam killing everybody its annoying he is a dev whcih he has acces to spam things infenitly he has hacking the game he shoot like 100 arrows every single click he says sp let him SP DONT GIVE HIM ACCES TO SPAM THINGS INSTENTLY READ THIS PLS 

### ISSUE THREAD

**Issue by itsferytime** [maitian352/Meadow-Guarder#105]
sp pls take  the accese of marcusanator becuse he is spaming instently every click in his arrows he shootls like 100

**Comment by itsferytime** [comment]
his probly gonna say im LYING BUT TRUSSSTTT MEE

**Comment by maitian352** [comment]
You also have access to it. If you join the discord server you can access MGHC, which is the hack he is using. I will not shut down MGHC because I made it.

**Comment by itsferytime** [comment]
how do i join

**Comment by itsferytime** [comment]
where is the discord server

**Comment by maitian352** [comment]
There is a link on the menu screen.

**Comment by Suvanth-Erranki** [comment]
Suggestion: direct message sp or me on discord about this and we can explain, instead of posting an issue @itsferytime

**Comment by definitely-nobody-is-here** [comment]
They were probably using MGHC 


Also I found this reading my 1k unread emails
