### ISSUE TITLE
If you time it just right, you can travel after you die.

### ISSUE THREAD

**Issue by maitian352** [maitian352/Meadow-Guarder#106]
Just before you die, you have to move into the teleporter, and you can travel to other areas after you die.

Here is an image of me doing the glitch.
![image](https://user-images.githubusercontent.com/68207888/98982508-84df2e00-24ed-11eb-9d2f-c76c114c6f9c.png)

**Comment by Suvanth-Erranki** [comment]
I did this too!:

![image](https://user-images.githubusercontent.com/63676047/98999616-fcce4800-252f-11eb-8602-88d175ae64be.png)

**Comment by maitian352** [comment]
Fixed.
