### ISSUE TITLE
When I try to go up the stairs in the general store, I get stuck on the other end

### ISSUE THREAD

**Issue by Suvanth-Erranki** [maitian352/Meadow-Guarder#106]
Video: https://www.youtube.com/watch?v=c6-itb1_CTw

**Comment by Suvanth-Erranki** [comment]
![image](https://user-images.githubusercontent.com/76885647/142704306-ff8e07eb-7242-4b7d-a139-f3e66bc191fb.png)

**Comment by maitian352** [comment]
Fixed but didn't commit.
