### ISSUE TITLE
I found a way to get infinite items! Major Crafting bug. 

### ISSUE THREAD

**Issue by Suvanth-Erranki** [maitian352/Meadow-Guarder#107]
![image](https://user-images.githubusercontent.com/76885647/142738358-5cb3d2da-384d-485b-b2e1-c2235bc2411b.png)
1000 coins of all types
![image](https://user-images.githubusercontent.com/76885647/142739275-76fa8200-e168-4a06-8d86-876f71c66739.png)
45 deaths

All you have to do is click on the item you want to get in the crafting setting and then click on the ground of the game and then the item will be there on the ground. I was able to use an autoclicker to get 1000 gold coins.

Video: https://youtu.be/ra4pRr7iaJo

**Comment by maitian352** [comment]
Can you please delete the illegally obtained items?

**Comment by Suvanth-Erranki** [comment]
Fixed.
