### ISSUE TITLE
There is a glitch which allows the player to type in the chat if they die and haven't respawned.

### ISSUE THREAD

**Issue by Suvanth-Erranki** [maitian352/Meadow-Guarder#108]
If the player is killed while they are typing in chat, they can still type and send messages as long as they don't click outside off the textarea.
![image](https://user-images.githubusercontent.com/63676047/99001211-618aa200-2532-11eb-92d9-6c3d85d41889.png)

**Comment by maitian352** [comment]
This won't be fixed, because suppose you want to type but it is a long message and you get killed while you are typing then it will be annoying.
