### ISSUE TITLE
Health Bar Animation glitch

### ISSUE THREAD

**Issue by Suvanth-Erranki** [maitian352/Meadow-Guarder#109]
I was 1v1ing marcusnator and I killed him with my bow and arrow so it showed that I had killed him in chat. However, for around 0.25 seconds, he was still alive, because the animation of his health bar going up showed, right as I killed. In essence, it showed for 0.25 seconds that he was alive and that he had regained some health, even though he was dead.

Sorry I don't have a video, this was just an accident. I might be able to replicate it, but it's difficult.

**Comment by maitian352** [comment]
Could this just be lag?

**Comment by Suvanth-Erranki** [comment]
I know it wasn't lag. Nothing was lagging, it was just absurd chance.

**Comment by Suvanth-Erranki** [comment]
I think that you should execute the death animation (the health bar empty and the player having the respawn button right before you execute the player is dead code).

**Comment by maitian352** [comment]
What does the player is dead code mean?

**Comment by Suvanth-Erranki** [comment]
Like the code to show the death screen for the player and to give them the option to respawn.

**Comment by maitian352** [comment]
> Like the code to show the death screen for the player and to give them the option to respawn.

When the player's health hits 0, then the respawn screen shows up.

**Comment by Suvanth-Erranki** [comment]
Hmm. This glitch happened to me again with Tianmu. I killed him, and his health bar showed that it was empty, but then for a brief moment, his health bar showed he had gotten back some of his health. Then he dissappeared since he respawned.

**Comment by maitian352** [comment]
No. When you respawn, you regain 1/2 of your health. He respawned, but when a player teleports to the spawn to respawn, the player fades out. You saw tianmu fade out, and that means he already respawned and is teleporting to spawn. Since a fade out starts from tianmu being completely opaque, you think that it is a bug but it isn't a bug.
