### ISSUE TITLE
When you are talking to an NPC, the monsters aren't able to fire at you which is a glitch.

### ISSUE THREAD

**Issue by Suvanth-Erranki** [maitian352/Meadow-Guarder#109]
This is an image of glitch happening to me:
![image](https://user-images.githubusercontent.com/63676047/99002133-e75b1d00-2533-11eb-9732-1428741c828a.png)

**Comment by maitian352** [comment]
This isn't a glitch, because before you said the monsters kept killing you, so now you are invincible when you are talking to NPCs.

**Comment by Suvanth-Erranki** [comment]
Wait, can you show me the issue I said that in?

**Comment by Suvanth-Erranki** [comment]
Also, if that's true then make sure you tell the user before hand on the log in screen.

**Comment by maitian352** [comment]
Also, when you are talking to an NPC, you aren't able to walk and that isn't a glitch.

**Comment by Suvanth-Erranki** [comment]
I know that though.

**Comment by maitian352** [comment]
@Suvanth-Erranki You said it in [this](https://github.com/maitian352/Meadow-Guarder/issues/91) issue.

**Comment by Suvanth-Erranki** [comment]
I know, but the monsters didn't give me time to move or fire in that issue. To fix that, you should maybe instead let the monsters give you a few seconds to run before they fire at you.

**Comment by maitian352** [comment]
But what if you are in the middle of a long dialogue and the monsters start firing?

**Comment by Suvanth-Erranki** [comment]
Then let them move around in that area (i.e. map bridge) while talking
to NPC. If they go out of the area, the message cancels. That fixes
every problem.

**Comment by Suvanth-Erranki** [comment]
What quiz?

**Comment by Suvanth-Erranki** [comment]
Well, we'll get there when we get there...

**Comment by maitian352** [comment]
But I even made a Actor.move() function even though we don't use it now because we might use it in the future.

**Comment by Suvanth-Erranki** [comment]
Don't count your chickens before they hatch! :)

**Comment by maitian352** [comment]
> Don't count your chickens before they hatch! :)
> […]

You mean:

Count your chickens before you even have eggs!

**Comment by Suvanth-Erranki** [comment]
I mean the NPC quizing you isn't that practical or necessary for the player.

**Comment by maitian352** [comment]
Maybe you have to gather knowledge from NPCs all around the Village and the NPC quizzes you to prove you know everything.

**Comment by Suvanth-Erranki** [comment]
Okay. By the way, I got the saying correct.

**Comment by Suvanth-Erranki** [comment]
It is don't catch your chickens before they hatch.

**Comment by Suvanth-Erranki** [comment]
Also, for quizzes, then make a specific option to pause the moment so the monsters can't fire.

**Comment by Suvanth-Erranki** [comment]
Sure - that will work.

**Comment by Suvanth-Erranki** [comment]
Just make it subtle and not such a big deal.

**Comment by Suvanth-Erranki** [comment]
Like maybe in smaller print - not too smal - medium print maybe.

**Comment by Suvanth-Erranki** [comment]
I mean "small" when I said 'smal.'
