### ISSUE TITLE
Player can lure monsters in forest to a stalemate position

### ISSUE THREAD

**Issue by Suvanth-Erranki** [maitian352/Meadow-Guarder#11]
In the forest, there is a corner in which the player can move into and the monsters if in range, will pursue the player and end up in the corner of the house in a position where they can't move or fire.
![image](https://user-images.githubusercontent.com/63676047/97789472-2209a080-1b97-11eb-8b8a-dbfc9a7031c2.png)

**Comment by maitian352** [comment]
This issue has been fixed.
