### ISSUE TITLE
Player Sprite Sneak Peak

### ISSUE THREAD

**Issue by maitian352** [maitian352/Meadow-Guarder#110]
Sneak Peak for the new player sprites coming out in 0.1.1!
![image](https://user-images.githubusercontent.com/68207888/99014236-52025d80-2520-11eb-8b75-daa11eb039ab.png)

![image](https://user-images.githubusercontent.com/68207888/99014285-6ba3a500-2520-11eb-8940-292fe76e0319.png)

**Comment by Suvanth-Erranki** [comment]
Cool!!!

**Comment by Suvanth-Erranki** [comment]
You should also add an option in the menu to customize the character, though that would require more code.

**Comment by maitian352** [comment]
Ok. That is one of the goals to get by 0.1.1.

**Comment by maitian352** [comment]
Even more player sprites!

![image](https://user-images.githubusercontent.com/68207888/99149333-4b2c3580-265b-11eb-9aba-b8fa03fbae3a.png)

![image](https://user-images.githubusercontent.com/68207888/99149341-57b08e00-265b-11eb-83e6-5d109d91a5cd.png)

**Comment by Suvanth-Erranki** [comment]
Cool

**Comment by maitian352** [comment]
Should I update? If I do, all of the maps will be gone except for the Meadow of Willows.

**Comment by Suvanth-Erranki** [comment]
No, don't do it because people won't like it. However, you can make a
seperate website with only the meadow of willows.

**Comment by maitian352** [comment]
What if I add the Meadow of Willows as a separate map like River or The Bridge?

**Comment by Suvanth-Erranki** [comment]
Sure.

**Comment by maitian352** [comment]
Now with a GIF!
![Sprites](https://user-images.githubusercontent.com/68207888/99153145-b46c7280-2674-11eb-8b4d-a8933c0d78f8.gif)

**Comment by maitian352** [comment]
Player Sprite pixel manipulation is complete! Now you can change the color of your character!

Some examples:

![image](https://user-images.githubusercontent.com/68207888/99161567-b7da1b00-26c1-11eb-88a3-534664ae86ad.png)

![image](https://user-images.githubusercontent.com/68207888/99161605-1b644880-26c2-11eb-90b7-2a0cb3f1dc22.png)

We don't have a screen to change it yet, but it will be soon implemented.

**Comment by maitian352** [comment]
Pre-rendering players worked, and now Players and NPCs have randomized clothing!

Some screenshots:

![image](https://user-images.githubusercontent.com/68207888/99185770-07e4cc00-271a-11eb-9561-a6ff49195c1c.png)

![image](https://user-images.githubusercontent.com/68207888/99185790-22b74080-271a-11eb-9b89-7e1c9aad8c0e.png)

**Comment by maitian352** [comment]
There is now a menu to change your character! There are four sliders, for the characters body, shirt, pants, and hair.

Screenshots:

![image](https://user-images.githubusercontent.com/68207888/99189375-e3dfb580-272e-11eb-93ab-19e00901b152.png)

![image](https://user-images.githubusercontent.com/68207888/99189387-f35efe80-272e-11eb-8dfd-7a51526f9091.png)

**Comment by Suvanth-Erranki** [comment]
VERY COOL!!!!!

**Comment by maitian352** [comment]
New hair design is out!

![Sprites Orange Hat](https://user-images.githubusercontent.com/68207888/99452235-4bddf980-28f1-11eb-9455-eb2fdd06abc0.gif)

**Comment by Suvanth-Erranki** [comment]
COOL!

**Comment by Tianmu695** [comment]
So cool! Maitian told me he is also working on a pouch for the character.

**Comment by Tianmu695** [comment]
We should have Sprites with Custom Shirt's (not just color) and custom hat's (also not just color)

**Comment by maitian352** [comment]
> We should have Sprites with Custom Shirt's (not just color) and custom hat's (also not just color)

Yes, there will be more shirts, like soon you will be able to wear a pouch and we plan on adding also custom patterns on shirts and hats.

**Comment by Suvanth-Erranki** [comment]
That's very coo!

**Comment by Suvanth-Erranki** [comment]
I mean cool - that was very unintentional!

**Comment by maitian352** [comment]
Ok.

**Comment by maitian352** [comment]
You can now change the type of hair via a fifth slider!

Some screenshots:

![image](https://user-images.githubusercontent.com/68207888/99735307-64394a00-2a92-11eb-93c0-c41cdeaebcdb.png)

![image](https://user-images.githubusercontent.com/68207888/99735335-731ffc80-2a92-11eb-8eb7-1801b9dfc5bc.png)

![image](https://user-images.githubusercontent.com/68207888/99735379-859a3600-2a92-11eb-89fa-4eb647df34c1.png)

![image](https://user-images.githubusercontent.com/68207888/99735404-8d59da80-2a92-11eb-9085-344e6165cfe9.png)

![image](https://user-images.githubusercontent.com/68207888/99735425-98146f80-2a92-11eb-895f-19c67b97ed18.png)

**Comment by maitian352** [comment]
There is also a special hat for NPCs!

![image](https://user-images.githubusercontent.com/68207888/99735805-46201980-2a93-11eb-8900-65352c77db85.png)

**Comment by maitian352** [comment]
All of these features have been released.

**Comment by maitian352** [comment]
0.1.1 is now out!

**Comment by maitian352** [comment]
> Should I update? If I do, all of the maps will be gone except for the Meadow of Willows.

This is like updating to 0.3.0
