### ISSUE TITLE
When you get disconnected, you can still do certain actions, but they don't save

### ISSUE THREAD

**Issue by Suvanth-Erranki** [maitian352/Meadow-Guarder#110]
When you get disconnected, you can still modify your inventory (remove/move items) and open/close crafting and settings. The issue with this is that someone may not realize they are disconnected and they might try to change their inventory and think its saved, and then close the tab, but then find out it didn't save when they reopen the game the next time. 

Instead, right after a user is disconnected, can the game show this to the person, so they know immediately.

**Comment by maitian352** [comment]
Fixed.

**Comment by Suvanth-Erranki** [comment]
Not fixed, I still am able to do it.

**Comment by Suvanth-Erranki** [comment]
It's more of a bug, since its a visual glitch - it appears you are making changes to your inventory or opening/closing crafting, inventory, settings, etc.

**Comment by maitian352** [comment]
No, I made the player get disconnected. They can still modify their items, but they get disconnected around after 1 second.

**Comment by Suvanth-Erranki** [comment]
No, I was able to do that for as long as I wanted. It didn't disconnect me.

**Comment by maitian352** [comment]
> No, I was able to do that for as long as I wanted. It didn't disconnect me.

How did you know you were disconnected?

**Comment by Suvanth-Erranki** [comment]
> > No, I was able to do that for as long as I wanted. It didn't disconnect me.
> 
> How did you know you were disconnected?

Because I couldn't move at all.

**Comment by maitian352** [comment]
> > > No, I was able to do that for as long as I wanted. It didn't disconnect me.
> > 
> > 
> > How did you know you were disconnected?
> 
> Because I couldn't move at all.

Maybe you were in a chat box / search bar?

**Comment by maitian352** [comment]
Do you remember when this happened?

**Comment by Suvanth-Erranki** [comment]
This happened this morning right before I commented here. Also, I made sure I wasn't in a chat box/search bar by clicking directly on the game.

**Comment by maitian352** [comment]
> This happened this morning right before I commented here. Also, I made sure I wasn't in a chat box/search bar by clicking directly on the game.

Oh. I only updated I think later.

**Comment by maitian352** [comment]
I am 100% sure this is fixed.
