### ISSUE TITLE
Projectiles can glitch through trees and buildings.

### ISSUE THREAD

**Issue by definitely-nobody-is-here** [maitian352/Meadow-Guarder#111]
![image](https://user-images.githubusercontent.com/67865358/142765326-6f50e3e7-78fe-47a5-af13-d3191bfff76f.png)

**Comment by Suvanth-Erranki** [comment]
Similar to #98, except with projectiles.

**Comment by Suvanth-Erranki** [comment]
I was also able to shoot arrows through the inn.

**Comment by maitian352** [comment]
Were you using a mystic knight's helmet? If you were, then that is normal, as the mystic knight's helmet allows you to shoot homing arrows that go through collisions.

**Comment by Suvanth-Erranki** [comment]
I think I was using it, but I don't remember. Since I can't say for sure, I think its alright to assume that this wasn't a bug.

**Comment by definitely-nobody-is-here** [comment]
> Similar to #98, except with projectiles.
except it hasn't been fixed

**Comment by definitely-nobody-is-here** [comment]
![image](https://user-images.githubusercontent.com/67865358/143481924-7273325b-548b-4e0a-9f2d-17f7bf6238c7.png)

**Comment by definitely-nobody-is-here** [comment]
something's wrong

**Comment by definitely-nobody-is-here** [comment]
simply prevent projectiles spawning if they will spawn in a collision

**Comment by maitian352** [comment]
> simply prevent projectiles spawning if they will spawn in a collision, it makes sense
> 
> "hey, I want to shoot an arrow but I'm aiming at a wall, I shouldn't be able to shoot this"

You can still shoot the arrow, it just goes into the wall.
