### ISSUE TITLE
You can open the trade feature with dead players.

### ISSUE THREAD

**Issue by Suvanth-Erranki** [maitian352/Meadow-Guarder#112]
![image](https://user-images.githubusercontent.com/76885647/142767357-63929c01-b8e2-4326-b488-b712fa352a95.png)

Players shouldn't be able to open the trade feature with dead players. Please fix.

**Comment by Suvanth-Erranki** [comment]
This is how it looks for a dead player when a player who is alive tries to trade with them:
![image](https://user-images.githubusercontent.com/76885647/142767464-23935f1a-f354-4a3c-b666-058af555f222.png)

**Comment by maitian352** [comment]
Fixed.
