### ISSUE TITLE
New Maps and NPCs for 0.1.1!

### ISSUE THREAD

**Issue by maitian352** [maitian352/Meadow-Guarder#112]
Here are some screenshots.

![image](https://user-images.githubusercontent.com/68207888/99117082-1d93ad80-25c3-11eb-88f5-6d7120eaf79f.png)

![image](https://user-images.githubusercontent.com/68207888/99117146-3c923f80-25c3-11eb-957d-51cf7a2b3946.png)

There will be more screenshots when more maps and NPCs are made.

**Comment by Suvanth-Erranki** [comment]
Cool.

**Comment by maitian352** [comment]
A new map The Docks is out!

![image](https://user-images.githubusercontent.com/68207888/99310416-ffc78200-2828-11eb-849e-9bcbbd9dcd7d.png)

![image](https://user-images.githubusercontent.com/68207888/99310452-0c4bda80-2829-11eb-8fe3-f03af479927a.png)

![image](https://user-images.githubusercontent.com/68207888/99310493-1a99f680-2829-11eb-9f25-522b07a3de1b.png)

**Comment by Suvanth-Erranki** [comment]
COOL!

**Comment by maitian352** [comment]
Do you have an idea for the tiny fishing hut in the second screenshot?

**Comment by Suvanth-Erranki** [comment]
I belive we should call it:
The Old Fisherman's Shack

**Comment by maitian352** [comment]
Cool. I can make a fisherman NPC in the shack.

**Comment by Suvanth-Erranki** [comment]
Sure with a fisherman hat and all.

**Comment by Tianmu695** [comment]
There should be be a NPC that need help to attack mosters that are in the river

**Comment by maitian352** [comment]
There is already code for that, and it is a pet, not an NPC. React with Thumbs Up if you want to prioritize pets!

**Comment by Suvanth-Erranki** [comment]
I'm not sure what you mean by "pets."

**Comment by maitian352** [comment]
Did you know that the purple monster sprite was originally meant to be a pet? A pet will follow you and shoot bullets to kill monsters.

**Comment by Tianmu695** [comment]
Fishermen are out!!!
![image](https://user-images.githubusercontent.com/68877583/101168463-7b874400-3609-11eb-84c7-2d2f82a338e6.png)
![image](https://user-images.githubusercontent.com/68877583/101168516-8c37ba00-3609-11eb-965b-8125b69c2c55.png)

**Comment by maitian352** [comment]
0.1.1 is now out!
