### ISSUE TITLE
If you start Mark's quest for defeating the monsters - you can glitch the system.

### ISSUE THREAD

**Issue by Suvanth-Erranki** [maitian352/Meadow-Guarder#114]
I can make the Mark's quest dissappear so that you have to log off to start the quest again.
View this video:
https://drive.google.com/file/d/19rBH-FGKUHeIj417NFN_40hsgXoU9GTg/view

**Comment by maitian352** [comment]
It says the requested file does not exist.

**Comment by Suvanth-Erranki** [comment]
What? I'll see if I can reupload the video.

**Comment by Suvanth-Erranki** [comment]
Try it again - maybe it was a momentary glitch.
The link: https://drive.google.com/file/d/19rBH-FGKUHeIj417NFN_40hsgXoU9GTg/view

**Comment by Suvanth-Erranki** [comment]
The issue is that I manage to make the monsters dissappear in the middle of the quest, but NPC Mark believes I'm still doing the quest and there is no way to complete it. The only solution is to log out and log back in again - that is what makes this a bug.

**Comment by Suvanth-Erranki** [comment]
Also, this issue is seperate from this: github.com/maitian352/Meadow-Guarder/issues/104
