### ISSUE TITLE
It takes about 5 seconds for the log in textarea to actually let you type which is caused by the load handler taking too long. Please fix!

### ISSUE THREAD

**Issue by Suvanth-Erranki** [maitian352/Meadow-Guarder#115]
https://lh3.googleusercontent.com/-x6dtNHIkorI/X68-ouvjEuI/AAAAAAAAAvg/9jLBL2cMwJYasN0sPuiZcr5MzfE0BUeiwCK8BGAsYHg/s0/2020-11-13.png

**Comment by maitian352** [comment]
This has been fixed.

**Comment by maitian352** [comment]
Loading screen
