### ISSUE TITLE
Add these three quests in the description!

### ISSUE THREAD

**Issue by Suvanth-Erranki** [maitian352/Meadow-Guarder#116]
Quest 1: Save an NPC or multiple NPCs from a monster or several monsters.
Quest 2: fight 1 orange monster, 3 red monsters, 5 blue monsters, 7 green monsters, and 9 purple monsters to claim Guarded Citadel as player territory
This quest should give lots of xp.
Quest 3: Clear all monsters in Lower Deadlands like this:
![image](https://user-images.githubusercontent.com/63676047/99152559-6a968300-269a-11eb-908c-485e105f05d9.png)

**Comment by maitian352** [comment]
The Lower Deadlands map is depreciated, but we might add the other two.

**Comment by Suvanth-Erranki** [comment]
I think you mean deprecated and/or obselete.

**Comment by Suvanth-Erranki** [comment]
The last 2 quests don't work anymore since we have different maps and different monster types. We have already implimented "Saving" Mark in one of the quests, so I am closing this issue.

**Comment by maitian352** [comment]
Quest 3 has been added as Clear River.
