### ISSUE TITLE
use cooldown still shows even when attack not used

### ISSUE THREAD

**Issue by definitely-nobody-is-here** [maitian352/Meadow-Guarder#116]
kinda dumb because I cant attack but the client says you attacked and so you can't use it again

also items that you don't use still get a cooldown
if you don't use something why would it get a cooldown?

**Comment by maitian352** [comment]
> kinda dumb because I cant attack but the client says you attacked and so you can't use it again
> 
> also items that you don't use still get a cooldown if you don't use something why would it get a cooldown?

So that you don't just have 10 bows on your hotbar and just change items every time you want to attack.

**Comment by definitely-nobody-is-here** [comment]
but thats the point

if you get 10 bows, good for you. You should be able to switch weapons. If you can switch weapons like that good for you
like how Minecraft lets you shoot a billion crossbows from your hotbar because you can

**Comment by maitian352** [comment]
> but thats the point
> 
> if you get 10 bows, good for you. You should be able to switch weapons. If you can switch weapons like that good for you like how Minecraft lets you shoot a billion crossbows from your hotbar because you can

You still have to charge up each individual crossbow. If Meadow Guarder only makes that one weapon have a cooldown, then multiple bows would be reloading at the same time.

**Comment by maitian352** [comment]
Fixed. Didn't commit yet.
