### ISSUE TITLE
If you switch tabs while the bullets are firing from the player, the page still shows in the preview that the bullets are still being fired.

### ISSUE THREAD

**Issue by Suvanth-Erranki** [maitian352/Meadow-Guarder#117]
I switched tabs then hovered over the Guarded Meadow tab and this glitch was showing I was still firing even though I had already finished firing and had switched tabs.
![image](https://user-images.githubusercontent.com/63676047/99158784-8a479e80-26ce-11eb-808e-9f569cdce6f6.png)

**Comment by maitian352** [comment]
Did you use left click or right click?

**Comment by Suvanth-Erranki** [comment]
There is no way to fix.
