### ISSUE TITLE
deep-fried text

### ISSUE THREAD

**Issue by definitely-nobody-is-here** [maitian352/Meadow-Guarder#117]
![image](https://user-images.githubusercontent.com/67865358/143481749-068b32fb-bc1a-44c6-a09a-2dde2872ca26.png)

**Comment by maitian352** [comment]
MGHC. This isn't a bug.

**Comment by definitely-nobody-is-here** [comment]
fix mghc

or i will spam

**Comment by maitian352** [comment]
?
![image](https://user-images.githubusercontent.com/68207888/143497673-81347cdf-df97-40a7-96fb-468afdb8e6cc.png)
Works for me.
