### ISSUE TITLE
You can fire bullets in the secret base if you aim at a certain spot which make shaded lines appear in the area.

### ISSUE THREAD

**Issue by Suvanth-Erranki** [maitian352/Meadow-Guarder#118]
Click on any of the wiry black things to fire - these:
![image](https://user-images.githubusercontent.com/63676047/99191205-1a372800-2763-11eb-843a-5e07eece4039.png)
and shaded lines appear.
View this video to see the glitch:
https://drive.google.com/file/d/1W82asmq1aYKZL0WJo5hmGPo6I4f17pPJ/view

**Comment by maitian352** [comment]
Those are cracks in the walls and they are decoration. You are supposed to be able to fire to kill the red boss in the quest Weird House.

**Comment by Suvanth-Erranki** [comment]
Did you even see the glitch in the video?

**Comment by Suvanth-Erranki** [comment]
The bug isn't in the cracks in the wall - you misunderstood, watch the video to see the glitch.

**Comment by maitian352** [comment]
The bug will still happen even if there isn't the decoration crack.

**Comment by Suvanth-Erranki** [comment]
That's not what I meant - you just need to fire in that certain spot for the bug to happen.

**Comment by Suvanth-Erranki** [comment]
The bug won't happen unless you fire in those cracks.

**Comment by maitian352** [comment]
Maybe because the cracks are black.

**Comment by Suvanth-Erranki** [comment]
I don't know - you saw the video right?

**Comment by Suvanth-Erranki** [comment]
https://drive.google.com/file/d/1W82asmq1aYKZL0WJo5hmGPo6I4f17pPJ/view

**Comment by maitian352** [comment]
I saw it. I think it might be your graphics drivers or something. [https://stackoverflow.com/questions/16594397/horizontal-glitch-lines-bug](https://stackoverflow.com/questions/16594397/horizontal-glitch-lines-bug)

**Comment by Suvanth-Erranki** [comment]
But I use Windows 10 and chrome - I don't think this is a graphic problem - it only happened to me for the first time today.

**Comment by Suvanth-Erranki** [comment]
I will try in another browser - Firefox.

**Comment by maitian352** [comment]
What about before, when white lines showed up in the Cave? I think this is the same issue.

**Comment by Suvanth-Erranki** [comment]
Yeah, just happening in different spots.

**Comment by Suvanth-Erranki** [comment]
Any way to fix?

**Comment by maitian352** [comment]
I don't think so. Maybe you should fix the driver or something. I don't know.

**Comment by Suvanth-Erranki** [comment]
What do you mean by driver?

**Comment by maitian352** [comment]
Your video card buffer is corrupted, so the black lines appear and the problem isn't with the code.
