### ISSUE TITLE
i cant pick up items anymore

### ISSUE THREAD

**Issue by definitely-nobody-is-here** [maitian352/Meadow-Guarder#118]
i have empty slots
i am clicking on the item
![image](https://user-images.githubusercontent.com/67865358/143482088-53573207-d05a-4a0d-b80b-469e4a74f1cf.png)
no pick up
no yellow outline

**Comment by definitely-nobody-is-here** [comment]
![image](https://user-images.githubusercontent.com/67865358/143482217-04ca74df-bd11-4fab-a81f-d0a154ceb049.png)

**Comment by maitian352** [comment]
MGHC or something. Maybe you have an outdated version. Either way, it isn't a bug.

**Comment by definitely-nobody-is-here** [comment]
its not outdated. also im not using mghc

**Comment by maitian352** [comment]
Well you used something. It says the error is from VM28, which means it is not from Meadow Guarder code and isn't a bug.
