### ISSUE TITLE
The game doesn't work in Firefox - I tried multiple times.

### ISSUE THREAD

**Issue by Suvanth-Erranki** [maitian352/Meadow-Guarder#119]
![image](https://user-images.githubusercontent.com/63676047/99192174-5d949500-2769-11eb-8249-3f30eb32804a.png)

**Comment by Suvanth-Erranki** [comment]
Note: This game works in both Chrome and Edge - tested - because Chrome we know works and Edge is basically based off chrome.

**Comment by maitian352** [comment]
This doesn't work in chromium either.

**Comment by Suvanth-Erranki** [comment]
I know - any method for cross-browser-support.

**Comment by Suvanth-Erranki** [comment]
I think the main thing is chrome, edge, safari, and opera all use webkit engines while firefox uses gecko rendering engine.

**Comment by Suvanth-Erranki** [comment]
If you are using webkit only code for js or css ( for example : document.webkitRequestFullscreen), that could be the issue. Just simply do an if statement for webkit support and an else if statement for gecko support to render the css for the game.

**Comment by Suvanth-Erranki** [comment]
In the image, you can see that the css is not rendering in firefox. This could be due to the fact that you are using webkit only css selectors. To find out if you are using webkit only css - go to: https://www.w3schools.com/cssref/css3_browsersupport.asp to see more.

**Comment by Suvanth-Erranki** [comment]
Just check the browser rendering engine through: 

if(navigator.userAgent.search(/trident/i)>0){
    //Internet Explorer
} else if(navigator.userAgent.search(/webkit/i)>0){
    //Chrome, Safari
} else if(navigator.userAgent.search(/???/i)>0){ //replace ??? by the appropriate engine
    //others
} else if(navigator.userAgent.search(/gecko/i)>0){
    //Firefox
}

**Comment by Suvanth-Erranki** [comment]
BAM! I found this webkt only code in style.css to fix.

**Comment by Suvanth-Erranki** [comment]
Here:
![image](https://user-images.githubusercontent.com/63676047/99192645-c715a300-276b-11eb-89b4-68fa3d17bde1.png)
![image](https://user-images.githubusercontent.com/63676047/99192657-e01e5400-276b-11eb-9cba-b09a2064d54a.png)

**Comment by Suvanth-Erranki** [comment]
You also have microsoft edge code but no firefox code:
![image](https://user-images.githubusercontent.com/63676047/99192717-43a88180-276c-11eb-880d-e80e4831af65.png)
AND HERE:
![image](https://user-images.githubusercontent.com/63676047/99192724-4f944380-276c-11eb-977c-fb6e0eaa90a7.png)

**Comment by Suvanth-Erranki** [comment]
You do have mozilla firefox code here though:
![image](https://user-images.githubusercontent.com/63676047/99192775-af8aea00-276c-11eb-921f-d5c2aac23baa.png)
AND HERE:
![image](https://user-images.githubusercontent.com/63676047/99192795-c03b6000-276c-11eb-9998-7b7cccef5330.png)
But I guess you didn't do the mozilla firefox code for some of the properties.

**Comment by Suvanth-Erranki** [comment]
I will be checking the firefox console for css errors in rendering the game.

**Comment by Suvanth-Erranki** [comment]
I FOUND THE ERROR!!!!!!
I checked firefox web console and I found the error:
![image](https://user-images.githubusercontent.com/63676047/99192851-2c1dc880-276d-11eb-9fbc-0e3cc162c2c5.png)

**Comment by Suvanth-Erranki** [comment]
The only place where you use off screen canvas is in index.html here:
![image](https://user-images.githubusercontent.com/63676047/99193494-34780280-2771-11eb-9bd9-9a6d155beada.png)

**Comment by Suvanth-Erranki** [comment]
So all you got to do to fix this issue is to insert this code:

if(navigator.userAgent.search(/trident/i)>0){
    //Internet Explorer
} else if(navigator.userAgent.search(/webkit/i)>0){
    //Chrome, Safari
} else if(navigator.userAgent.search(/???/i)>0){ //replace ??? by the appropriate engine
    //others
} else if(navigator.userAgent.search(/gecko/i)>0){
    //Firefox
}

into index.html and when you are using OffscreenCanvas, just detect if the browser is firefox and then run the code that firefox has no error with which you can read about here:
https://developer.mozilla.org/en-US/docs/Web/API/OffscreenCanvas

**Comment by Suvanth-Erranki** [comment]
Just alert the user if the browser is firefox and put the disclaimer using:

if(navigator.userAgent.search(/gecko/i)>0){
    alert("The game only supports firefox if OffscreenCanvas is enabled in settings. To learn more, go to: https://developer.mozilla.org/en-US/docs/Web/API/OffscreenCanvas/OffscreenCanvas");
}

**Comment by Suvanth-Erranki** [comment]
We have already established that even though you enable gfx.offscreencanvas.enabled in about:config - this doesn't work due to this bug:
https://bugzilla.mozilla.org/show_bug.cgi?id=151495
![image](https://user-images.githubusercontent.com/63676047/99198137-8713e780-278e-11eb-884a-316c96e9eb46.png)

**Comment by Suvanth-Erranki** [comment]
I am reopening this because you need to use regular canvas if you detect firefox through this code:
if(navigator.userAgent.search(/gecko/i)>0){"
    // Use normal canvas
}

**Comment by maitian352** [comment]
There is one problem with that code. When I open it in chrome it still says you are in firefox.

**Comment by Suvanth-Erranki** [comment]
var isFirefox = typeof InstallTrigger !== 'undefined';
if (isFirefox === true) {
    // Person is using firefox.
}

**Comment by Suvanth-Erranki** [comment]
Fixed.
