### ISSUE TITLE
i can only attack up now

### ISSUE THREAD

**Issue by definitely-nobody-is-here** [maitian352/Meadow-Guarder#119]
what
![image](https://user-images.githubusercontent.com/67865358/143482177-0c58dbd8-1ae5-4363-8542-d6e17ba784e2.png)
I am clicking to the right
but it shoots up

also i cant pick up items

**Comment by definitely-nobody-is-here** [comment]
![image](https://user-images.githubusercontent.com/67865358/143482203-46b876b3-31f2-4456-8b38-285081eb28fa.png)

**Comment by maitian352** [comment]
It's MGHC or something. Maybe you have an outdated version. Either way, this isn't a bug.

**Comment by definitely-nobody-is-here** [comment]
its not outdated. also im not using mghc

**Comment by maitian352** [comment]
Well you used something. It says the error is from VM28, which means it is not from Meadow Guarder code and isn't a bug.
