### ISSUE TITLE
Once the monster touches the side of a building, it cannot move - it can only fire.

### ISSUE THREAD

**Issue by Suvanth-Erranki** [maitian352/Meadow-Guarder#12]
![image](https://user-images.githubusercontent.com/63676047/97789517-86c4fb00-1b97-11eb-98e3-f0c703f916c5.png)

**Comment by maitian352** [comment]
This is a duplicate of [this](https://github.com/maitian352/Meadow-Guarder/issues/14), where when the monster gets to you it stops tracking you.
