### ISSUE TITLE
ew scrollbar is ocd

### ISSUE THREAD

**Issue by definitely-nobody-is-here** [maitian352/Meadow-Guarder#120]
![image](https://user-images.githubusercontent.com/67865358/143482289-50bfe9b0-2c7d-418f-9205-b8294de5906c.png)

**Comment by definitely-nobody-is-here** [comment]
i want to punch the scroll bar

**Comment by maitian352** [comment]
It's so tiny it's fine.

**Comment by definitely-nobody-is-here** [comment]
ugly

**Comment by maitian352** [comment]
> ugly

Ok i'll try to fix this.

**Comment by maitian352** [comment]
Fixed.
