### ISSUE TITLE
Suggestion: Make the game fullscreen with the code below in the description!

### ISSUE THREAD

**Issue by Suvanth-Erranki** [maitian352/Meadow-Guarder#122]
document.fullscreenEnabled =
	document.fullscreenEnabled ||
	document.mozFullScreenEnabled ||
	document.documentElement.webkitRequestFullScreen ||
        document.msFullScreenEnabled;

function requestFullscreen(element) {
	if (element.requestFullscreen) {
		element.requestFullscreen();
	} else if (element.mozRequestFullScreen) {
		element.mozRequestFullScreen();
	} else if (element.webkitRequestFullScreen) {
		element.webkitRequestFullScreen(Element.ALLOW_KEYBOARD_INPUT);
        } else if (element.msRequestFullScreen) {
		element.msRequestFullScreen();
	}
}

if (document.fullscreenEnabled) {
	requestFullscreen(document.documentElement);
}

**Comment by Suvanth-Erranki** [comment]
I did it!

**Comment by definitely-nobody-is-here** [comment]
this was added
