### ISSUE TITLE
You Don't Level Up

### ISSUE THREAD

**Issue by Tianmu695** [maitian352/Meadow-Guarder#123]
![image](https://user-images.githubusercontent.com/68877583/99613305-4d88e980-29e5-11eb-8295-edadd2ce6e6d.png)

**Comment by Tianmu695** [comment]
What!!!

**Comment by maitian352** [comment]
This is because the game rounds you XP to the nearest thousand, so if you had 29000XP / 30000XP, it will show as 30K/30K.
