### ISSUE TITLE
Can we please have rooms!!

### ISSUE THREAD

**Issue by Tianmu695** [maitian352/Meadow-Guarder#124]
These houses don't have rooms!

![image](https://user-images.githubusercontent.com/68877583/99614913-78287180-29e8-11eb-8693-55463a32999c.png)

**Comment by Tianmu695** [comment]
let's have it at 1.5 update!

**Comment by maitian352** [comment]
Lilypad Pathway will be deleted in the upcoming 0.1.1 update.

**Comment by maitian352** [comment]
This map is depreciated.

**Comment by maitian352** [comment]
This map has been re-added, and there are rooms.

**Comment by maitian352** [comment]
> Let's have it at 1.5 update!

when do you think 1.5 is coming out
23412?
