### ISSUE TITLE
In the river map, mosters can go through a spall part of an tree.

### ISSUE THREAD

**Issue by Tianmu695** [maitian352/Meadow-Guarder#126]
![image](https://user-images.githubusercontent.com/68877583/99984592-419d7e80-2d7b-11eb-8f64-434536db5601.png)

**Comment by Tianmu695** [comment]
but it looks cool!!!!

**Comment by maitian352** [comment]
The monster is behind the tree.

**Comment by maitian352** [comment]
Ah yes, spall part of a tree.

**Comment by maitian352** [comment]
Also, what is a moster?
