### ISSUE TITLE
Players can't go through the sides of the bridge, yet weapons can.

### ISSUE THREAD

**Issue by Suvanth-Erranki** [maitian352/Meadow-Guarder#126]
So weapons cannot go through trees and other objects just like the players (without mystic knight helmet), but they can go through the sides of the walls? Players can't do that. That makes absolutely no sense.
![image](https://user-images.githubusercontent.com/76885647/143661970-31d10117-abea-408a-b8ad-73f8b368426a.png)
![image](https://user-images.githubusercontent.com/76885647/143662111-b134d530-0d05-480c-a57c-f1fb94112d4b.png)

**Comment by maitian352** [comment]
You can shoot off the bridge, however your player will not walk off otherwise he will drown.

**Comment by Suvanth-Erranki** [comment]
Isn't there a solid barrier on the sides of the bridge? That's whats blocking the player right? Why doesn't it block the arrows is my question.

**Comment by maitian352** [comment]
There is no solid barrier at the sides of the bridge.
