### ISSUE TITLE
Menu Screen Sneak Peak!

### ISSUE THREAD

**Issue by maitian352** [maitian352/Meadow-Guarder#131]
We are making a new menu screen for 0.1.1!

Preview:
![image](https://user-images.githubusercontent.com/68207888/100780197-6d51e180-33d7-11eb-957e-547faac66a28.png)

**Comment by Suvanth-Erranki** [comment]
Cool

**Comment by maitian352** [comment]
New Menu Screen! We are hoping to release this soon.

![image](https://user-images.githubusercontent.com/68207888/100786261-e7866400-33df-11eb-89ab-25c5ba7b60e1.png)

**Comment by Suvanth-Erranki** [comment]
Cool!!!

**Comment by maitian352** [comment]
This sneak peak is out!

**Comment by Suvanth-Erranki** [comment]
I am closing this now because it is out.

**Comment by maitian352** [comment]
No, this still has to be open because 0.1.1 isn't out yet.

**Comment by maitian352** [comment]
0.1.1 is now out!
