### ISSUE TITLE
you start with slot selected as none

### ISSUE THREAD

**Issue by definitely-nobody-is-here** [maitian352/Meadow-Guarder#131]
kinda dumb that when you join you don't have a slot selected. that's like when you join and you don't have a position until you move.

**Comment by maitian352** [comment]
> kinda dumb that when you join you don't have a slot selected. that's like when you join and you don't have a position until you move.

Then you select an item to use.

**Comment by Suvanth-Erranki** [comment]
I don't think this is really an issue because it's really easy and not that difficult to just select an item when you start. Also, what if you don't want to use a weapon when you start?

**Comment by definitely-nobody-is-here** [comment]
who cares. it doesnt make sense

**Comment by Suvanth-Erranki** [comment]
That's subjective.

**Comment by maitian352** [comment]
It does. You don't do anything until you specify what you want to select.
