### ISSUE TITLE
Add a fishermen!! (more information in the description)

### ISSUE THREAD

**Issue by Tianmu695** [maitian352/Meadow-Guarder#132]
After Mark chops lots of wood, he gets hungry. He needs fish, so you have to go to the fishermen's house(in the Docks map), then the fishermen will ask: "What do you need?" and you click "I need fish." and the fishermen will say: "I have a lot of fish." and end the conversation. after that, you come to Mark and Mark will say: "Do you have the fish?" and you say: "yes" and you get lot's of Xp.

**Comment by maitian352** [comment]
This sounds pretty cool, but because Mark is a quest Npc and is only there during a quest, I might add this as a side quest.

**Comment by Suvanth-Erranki** [comment]
Fisherman has been added.
