### ISSUE TITLE
Monsters get stuck

### ISSUE THREAD

**Issue by Suvanth-Erranki** [maitian352/Meadow-Guarder#133]
![image](https://user-images.githubusercontent.com/76885647/143663529-7fa3527f-aa8b-443b-b2f9-623f59cffc84.png)

**Comment by Suvanth-Erranki** [comment]
Also, sometimes they shoot projectiles and sometimes they don't.

**Comment by Suvanth-Erranki** [comment]
![image](https://user-images.githubusercontent.com/76885647/143723729-bc3b4d9d-032c-4ef1-abbd-777a7b10992a.png)
They get stuck on their own somtimes.

**Comment by maitian352** [comment]
> ![image](https://user-images.githubusercontent.com/76885647/143723729-bc3b4d9d-032c-4ef1-abbd-777a7b10992a.png) They get stuck on their own somtimes.

This is because the Ten Eyed One's hitbox is huge.

**Comment by Suvanth-Erranki** [comment]
![image](https://user-images.githubusercontent.com/76885647/145126292-c6f7366c-9bf5-47f2-9fbd-a6fac9bdbe0e.png)

**Comment by maitian352** [comment]
I believe this is fixed. Reopen if still happening.
