### ISSUE TITLE
New monsters for 0.1.1!!!!!!

### ISSUE THREAD

**Issue by Tianmu695** [maitian352/Meadow-Guarder#133]
Here we have the cool green monster,
![image](https://user-images.githubusercontent.com/68877583/101193512-ac2ba580-362a-11eb-8391-1ee481e2a913.png)
And here is the cool blue monster!!!
![image](https://user-images.githubusercontent.com/68877583/101193627-dd0bda80-362a-11eb-9ae0-9ee20b7fe6eb.png)

**Comment by maitian352** [comment]
You forgot red monsters.
![image](https://user-images.githubusercontent.com/68207888/101196236-77b9e880-362e-11eb-9131-de1255cd5d4f.png)

**Comment by maitian352** [comment]
Please do not post images of sneak peaks. Leave that to the owner.

**Comment by Tianmu695** [comment]
Super-rare-half-exploded-cherry-bomb!!!
![image](https://user-images.githubusercontent.com/68877583/101261704-3812ff80-3707-11eb-8166-6e9ee13792fb.png)

**Comment by Tianmu695** [comment]
If you don't know what is a cherry bomb, this an one that I caught in a screenshot!!!
![image](https://user-images.githubusercontent.com/68877583/101261800-d0a97f80-3707-11eb-8f7d-c37749dee7a3.png)

**Comment by Tianmu695** [comment]
![image](https://user-images.githubusercontent.com/68877583/101261923-aad0aa80-3708-11eb-9704-6ccd2b65fdb8.png)
![image](https://user-images.githubusercontent.com/68877583/101261958-ea979200-3708-11eb-82a7-b6bd9a943d0c.png)
![image](https://user-images.githubusercontent.com/68877583/101261973-026f1600-3709-11eb-8ac1-c57456fd76f0.png)
