### ISSUE TITLE
ten-eyed-one getst stuck on nothing

### ISSUE THREAD

**Issue by definitely-nobody-is-here** [maitian352/Meadow-Guarder#135]
dont have screenshot

**Comment by Suvanth-Erranki** [comment]
I do have a screenshot.
![image](https://user-images.githubusercontent.com/76885647/143664555-56b0288c-5cd6-4b08-997e-02b3fa4c38c1.png)

**Comment by Suvanth-Erranki** [comment]
Duplicate of #133
