### ISSUE TITLE
Suggestion: stop making NPC walk into random object, even if they are dumb.

### ISSUE THREAD

**Issue by Suvanth-Erranki** [maitian352/Meadow-Guarder#135]
![image](https://user-images.githubusercontent.com/63676047/101258408-528dae80-36f0-11eb-8b88-8eb743a52bd7.png)

**Comment by Suvanth-Erranki** [comment]
I also extend this to NPC walking into random structures like houses.

**Comment by maitian352** [comment]
The Npc pathfinding algorithm isn't very smart. It just chooses a random place to walk to. But I did improve it a bit, so it might be better.

**Comment by maitian352** [comment]
The Npc has been changed to walk better.
