### ISSUE TITLE
physics?

### ISSUE THREAD

**Issue by definitely-nobody-is-here** [maitian352/Meadow-Guarder#137]
![image](https://user-images.githubusercontent.com/67865358/143664469-8074d399-86bc-44e1-8605-f330759a3769.png)

**Comment by maitian352** [comment]
? I don't get it.

**Comment by maitian352** [comment]
This is the lawn chair thingy.
![image](https://user-images.githubusercontent.com/68207888/143688071-2d61138b-ac6f-4e62-8647-9b134f084dbb.png)
This

**Comment by Suvanth-Erranki** [comment]
Ok that isn't a bug. @definitely-nobody-is-here please provide more information or we will close the issue.
