### ISSUE TITLE
The Entire Screen went gray

### ISSUE THREAD

**Issue by Suvanth-Erranki** [maitian352/Meadow-Guarder#138]
I left Meadow Guarder running while I turned on auto kill monsters and I came back 15 minutes later. This is what I saw:
![image](https://user-images.githubusercontent.com/76885647/143665603-1f45b381-391f-46e6-b45f-a22ca685e166.png)

There were no issues in the console:
![image](https://user-images.githubusercontent.com/76885647/143665613-6850107c-5a26-40a8-9d28-8ebf63b7646e.png)

**Comment by maitian352** [comment]
Duplicate of #91
