### ISSUE TITLE
Suggestion: add holiday themes - like change the music or theme when its a special occasion.

### ISSUE THREAD

**Issue by Suvanth-Erranki** [maitian352/Meadow-Guarder#138]
Add different monsters on the holidays - like snowy monsters for the winter holidays and scary monsters for halloween.

**Comment by maitian352** [comment]
Instead of changing that, we added new items! There is now an item called Candy Cane, which has the same drop chance as a Simple Dark Steel Bow.

**Comment by Tianmu695** [comment]
we also added a snow monster

**Comment by Tianmu695** [comment]
it is a snowy ball(SNOWBALL!!!!!!!!!)

**Comment by Tianmu695** [comment]
Relesed!
![image](https://user-images.githubusercontent.com/68877583/101489213-a38ae600-392e-11eb-8c8c-79b442215405.png)
