### ISSUE TITLE
Sugggestion: add homes that NPC live - their own unique houses.

### ISSUE THREAD

**Issue by Suvanth-Erranki** [maitian352/Meadow-Guarder#139]
Maybe like make this an NPC house or add a new NPC house:
![image](https://user-images.githubusercontent.com/63676047/101258594-7e5d6400-36f1-11eb-9ea8-37f93bdfa9c9.png)

**Comment by Suvanth-Erranki** [comment]
I know that the fisherman has his own hut, but create other NPC houses:
![image](https://user-images.githubusercontent.com/63676047/101258831-13149180-36f3-11eb-9802-c2fc878d16fd.png)

**Comment by Tianmu695** [comment]
John has a house

**Comment by maitian352** [comment]
In 0.1.1, Bob also has a house.
