### ISSUE TITLE
You can go down the basement of the forge without using the stairs

### ISSUE THREAD

**Issue by Suvanth-Erranki** [maitian352/Meadow-Guarder#140]
Right here: 
![image](https://user-images.githubusercontent.com/76885647/143721752-3e33a191-8598-47f5-a199-7402ed28566c.png)

Please fix this glitch. Also, Smorties found this!

**Comment by maitian352** [comment]
Fixed. Didn't update yet though.

**Comment by definitely-nobody-is-here** [comment]
you were jsut fixing it
