### ISSUE TITLE
Suggestion: Add an option in the login screen to change username.

### ISSUE THREAD

**Issue by Suvanth-Erranki** [maitian352/Meadow-Guarder#140]
I know I mentioned this in another issue, but that was mostly about a change password option so I made this its own suggestion.

**Comment by maitian352** [comment]
I don't think this will be implemented, because it will cause many problems because the database sorts your progress by the username.

**Comment by Suvanth-Erranki** [comment]
Okay, but I will keep this issue open in case we wish to do this in the future.

**Comment by Suvanth-Erranki** [comment]
Yeah, I don't see this being used.
