### ISSUE TITLE
Ten-Eyed One only has 7 eyes? Seriously...

### ISSUE THREAD

**Issue by Suvanth-Erranki** [maitian352/Meadow-Guarder#142]
![image](https://user-images.githubusercontent.com/76885647/143724429-f1b2a913-4213-4986-81d4-a569be0d2434.png)
He is "ten-eyed one" and has only 7 eyes SMH

**Comment by maitian352** [comment]
![image](https://user-images.githubusercontent.com/68207888/143727023-71ca726c-2e99-478a-a59d-93202ef5e317.png)
what do you mean
10 eyes
