### ISSUE TITLE
Suggestion: don't let NPC and players go through the same space - they should act like real people.

### ISSUE THREAD

**Issue by Suvanth-Erranki** [maitian352/Meadow-Guarder#144]
![image](https://user-images.githubusercontent.com/63676047/101259050-879c0000-36f4-11eb-9b1e-74741bb358a2.png)

**Comment by maitian352** [comment]
The Npc's are passive to you, so they can be in the same space as you. If you teamed up with another player you wouldn't want to your attacks to be messed up if the other player walks into you.
