### ISSUE TITLE
When killing a monster, you can get its stats to show negative health right as you kill it.

### ISSUE THREAD

**Issue by Suvanth-Erranki** [maitian352/Meadow-Guarder#144]
![image](https://user-images.githubusercontent.com/76885647/143772824-76db9fab-ada5-4678-beb4-edf5944b17ac.png)

**Comment by Suvanth-Erranki** [comment]
Why is this an enhancement? Monsters shouldn't show negative health, so I assume its a bug.

**Comment by maitian352** [comment]
> Why is this an enhancement? Monsters shouldn't show negative health, so I assume its a bug.

Because this bug doesn't actively affect gameplay.

**Comment by Suvanth-Erranki** [comment]
> > Why is this an enhancement? Monsters shouldn't show negative health, so I assume its a bug.
> 
> Because this bug doesn't actively affect gameplay.

Got it.
