### ISSUE TITLE
You can respawn 3 times in a row without dying

### ISSUE THREAD

**Issue by Suvanth-Erranki** [maitian352/Meadow-Guarder#145]
![image](https://user-images.githubusercontent.com/76885647/143781510-07cfc494-a4d7-4113-a900-795d7ba69847.png)

**Comment by maitian352** [comment]
> ![image](https://user-images.githubusercontent.com/76885647/143781510-07cfc494-a4d7-4113-a900-795d7ba69847.png)

This was because I was messing around with commands.
