### ISSUE TITLE
my screen is grey what

### ISSUE THREAD

**Issue by definitely-nobody-is-here** [maitian352/Meadow-Guarder#146]
![image](https://user-images.githubusercontent.com/67865358/143793281-28105b30-adaa-489f-84ba-050d4963f352.png)

**Comment by Suvanth-Erranki** [comment]
its gray not grey

**Comment by Suvanth-Erranki** [comment]
duplicate of #138

**Comment by definitely-nobody-is-here** [comment]
British spelling is “grey”

**Comment by Suvanth-Erranki** [comment]
Hello british mate.
