### ISSUE TITLE
For a brief moment, the game says please enable javascript, even though its already enabled.

### ISSUE THREAD

**Issue by Suvanth-Erranki** [maitian352/Meadow-Guarder#147]
Here is the frame in which it gives the message:
![image](https://user-images.githubusercontent.com/63676047/101261798-ca1b0800-3707-11eb-8aec-761e08bbd520.png)
The detection of javascript disabled isn't working. Try using the <noscript> tag.

**Comment by maitian352** [comment]
This issue has been fixed.
