### ISSUE TITLE
I CANT MOVE

### ISSUE THREAD

**Issue by definitely-nobody-is-here** [maitian352/Meadow-Guarder#148]
I was fighting ten-eyed-one and couldnt move and ided

**Comment by definitely-nobody-is-here** [comment]
i still cant move

**Comment by definitely-nobody-is-here** [comment]
I relogged and still cant move

**Comment by definitely-nobody-is-here** [comment]
AAAAAA

**Comment by definitely-nobody-is-here** [comment]
After logging in for a little it stops working

**Comment by definitely-nobody-is-here** [comment]
every time I touch my trackpad i stop moving and cant move anymore

**Comment by Suvanth-Erranki** [comment]
![image](https://user-images.githubusercontent.com/76885647/143793621-321694aa-2e8c-4be4-8bca-4da06102f7cb.png)
I was playing a joke.
