### ISSUE TITLE
There can be Catch 22s

### ISSUE THREAD

**Issue by Suvanth-Erranki** [maitian352/Meadow-Guarder#148]
Maitian had to kill the monster because whenever I tried to respawn, the monster killed me.
![image](https://user-images.githubusercontent.com/63676047/101262105-094a5880-370a-11eb-882d-e6e1f7ca00f4.png)

**Comment by maitian352** [comment]
I think the real bug is this:

![image](https://user-images.githubusercontent.com/68207888/101262575-df933080-370d-11eb-940c-675b0bb8367d.png)

**Comment by maitian352** [comment]
This issue has been fixed.
