### ISSUE TITLE
Monsters still fire at you even though you are dead, which shouldn't be so and could lead to catch 22s

### ISSUE THREAD

**Issue by Suvanth-Erranki** [maitian352/Meadow-Guarder#154]
![image](https://user-images.githubusercontent.com/63676047/101267840-5e4a9680-372b-11eb-9b97-af876bf8c614.png)

**Comment by Suvanth-Erranki** [comment]
Fixed.

**Comment by Suvanth-Erranki** [comment]
This still happens in the weird tower quest.

**Comment by maitian352** [comment]
This is because the monster is firing at me, not you, and it just can't reach me because of the barrier.

**Comment by maitian352** [comment]
Actually, sometimes the monster tries to fire at another monster. But this has been fixed.

**Comment by Suvanth-Erranki** [comment]
No, this sometimes happens on solo quests too.

**Comment by maitian352** [comment]
When did it happen?

**Comment by maitian352** [comment]
This issue has been fixed.
