### ISSUE TITLE
how do i get in your discord and fill out that form so i can beccome a dev

### ISSUE THREAD

**Issue by itsferytime** [maitian352/Meadow-Guarder#154]

**Comment by definitely-nobody-is-here** [comment]
Why is the discord link not here

**Comment by itsferytime** [comment]
yeah he shuold put the link

**Comment by maitian352** [comment]
![image](https://user-images.githubusercontent.com/68207888/143941336-5276b30b-1187-466b-bab1-fe13e09f6145.png)
I will put the link and the contribution form.
