### ISSUE TITLE
The Clear River Quest doesn't always work.

### ISSUE THREAD

**Issue by Suvanth-Erranki** [maitian352/Meadow-Guarder#157]
![image](https://user-images.githubusercontent.com/63676047/101288168-1414f400-37c3-11eb-9215-0b83faaca7c9.png)

**Comment by Suvanth-Erranki** [comment]
Also, I know for a fact that I talked to John completely and then went and tried to do the quest.

**Comment by maitian352** [comment]
This bug is caused by the CherryBombs exploding and not counting as killed.

**Comment by Suvanth-Erranki** [comment]
The issue has been concluded to be not by the CherryBombs, but some sort of one time glitch, so the issue is being closed.
