### ISSUE TITLE
Make monsters smarter at chasing the player - otherwise, the game isn't that fun.

### ISSUE THREAD

**Issue by Suvanth-Erranki** [maitian352/Meadow-Guarder#159]
Monsters always get stuck behind trees or houses, even though they can still physically move and follow the player.
Monster stuck behind tree:
![image](https://user-images.githubusercontent.com/63676047/101413488-5ec16980-38b2-11eb-8657-90de4b2abba0.png)
Monster stuck behind stump:
![image](https://user-images.githubusercontent.com/63676047/101413610-90d2cb80-38b2-11eb-9c68-43b7b131e9cb.png)
Monster stuck behind house:
![image](https://user-images.githubusercontent.com/63676047/101413685-acd66d00-38b2-11eb-9513-7143147c8cc2.png)
Please make the monsters super advanced as that will make the game more interesting and fun!

**Comment by maitian352** [comment]
How do you do that?

**Comment by Suvanth-Erranki** [comment]
Make the monsters find paths around the obstacles - don't even render paths towards objects when making the monsters.

**Comment by maitian352** [comment]
How do you find paths?

**Comment by Suvanth-Erranki** [comment]
List all the houses, trees, and stumps and make that a place the monsters can never go towards.

**Comment by maitian352** [comment]
Ok, but pathfinding is actually pretty hard.

**Comment by Suvanth-Erranki** [comment]
I know, but I believe this will definitely make the game better!

**Comment by Suvanth-Erranki** [comment]
Also, make the monsters not run into walls when chasing:
![image](https://user-images.githubusercontent.com/63676047/101414219-b3191900-38b3-11eb-935a-da65af5caff0.png)

**Comment by maitian352** [comment]
The monsters won't be super smart, because if you use pathfinding to find the best path it takes a lot of time. They will only detect obstacles in a 8by8 range.

**Comment by maitian352** [comment]
Can you do the pathfinding?

**Comment by maitian352** [comment]
Better pathfinding has been added!
