### ISSUE TITLE
In any house, you can fire out your bullets into a black empty void.

### ISSUE THREAD

**Issue by Suvanth-Erranki** [maitian352/Meadow-Guarder#16]
![image](https://user-images.githubusercontent.com/63676047/97789802-c391f180-1b99-11eb-8bc0-6312d51b16c2.png)

**Comment by Suvanth-Erranki** [comment]
I didn't capture a bullet in that image, but it possible - you can try it for yourself.

**Comment by maitian352** [comment]
Fixed.
