### ISSUE TITLE
the monster gets stuck on trees this is a glich but im a bug finder

### ISSUE THREAD

**Issue by itsferytime** [maitian352/Meadow-Guarder#160]
![image](https://user-images.githubusercontent.com/94699229/144069830-9ae1249b-be95-4cbd-8e98-ba41f260edc9.png)

**Comment by itsferytime** [comment]
![image](https://user-images.githubusercontent.com/94699229/144069830-9ae1249b-be95-4cbd-8e98-ba41f260edc9.png)

**Comment by itsferytime** [comment]
see look

**Comment by definitely-nobody-is-here** [comment]
It’s a bug

**Comment by definitely-nobody-is-here** [comment]
Duplicate of #133

**Comment by itsferytime** [comment]
so i found a bug oooo

**Comment by maitian352** [comment]
Why is this closed? It isn't fixed yet.

**Comment by Suvanth-Erranki** [comment]
> Why is this closed? It isn't fixed yet.

It's a duplicate and duplicates are closed.

**Comment by maitian352** [comment]
> > Why is this closed? It isn't fixed yet.
> 
> It's a duplicate and duplicates are closed.

Duplicates should not be closed.

**Comment by maitian352** [comment]
I believe this is fixed. Reopen if still happening.
