### ISSUE TITLE
Monsters can't move after they kill you

### ISSUE THREAD

**Issue by Suvanth-Erranki** [maitian352/Meadow-Guarder#161]
![image](https://user-images.githubusercontent.com/63676047/101414645-7d286480-38b4-11eb-95fc-999fc77f722c.png)

**Comment by maitian352** [comment]
It isn't they can't move, but they stop chasing you when you die. When you respawn if the monster detects you again it will start chasing you again.

**Comment by Suvanth-Erranki** [comment]
Okay, my bad - sorry.
