### ISSUE TITLE
When you start a trade, you can't close it until the other person either accepts or declines it.

### ISSUE THREAD

**Issue by Suvanth-Erranki** [maitian352/Meadow-Guarder#161]
This is annoying because you have to wait for someone else and they might be idle.

**Comment by maitian352** [comment]
Well then just don't accept the trade if you think the player is afk. Clicking "accept" means that you are going to trade.

**Comment by maitian352** [comment]
You should always tell a person you are trading with them and tell them to accept first.

**Comment by Suvanth-Erranki** [comment]
> Well then just don't accept the trade if you think the player is afk. Clicking "accept" means that you are going to trade.

You don't always know if someone is online or idle because it's not like we can see what they are doing in real life.
Also, what if someone forgets or gets distracted. 

There's not really any harm I can see with adding this, it only helps.

**Comment by maitian352** [comment]
> > Well then just don't accept the trade if you think the player is afk. Clicking "accept" means that you are going to trade.
> 
> You don't always know if someone is online or idle because it's not like we can see what they are doing in real life. Also, what if someone forgets or gets distracted. What if they are at school and they have to close the tab? That's an exteme scenario, but you get what I mean.
> 
> There's not really any harm I can see with adding this, it only helps.

When they close the tab, you get all the items from the trade.

**Comment by maitian352** [comment]
Added.
