### ISSUE TITLE
Monsters can get stuck bumping into each other.

### ISSUE THREAD

**Issue by Suvanth-Erranki** [maitian352/Meadow-Guarder#163]
Please fix this by either damaging the monsters if they bump into each other, or make them move around each other.
![image](https://user-images.githubusercontent.com/63676047/101415061-3c7d1b00-38b5-11eb-808e-2a121c7b5ae9.png)

**Comment by Suvanth-Erranki** [comment]
I'm serious - they can't move!

**Comment by Suvanth-Erranki** [comment]
Whoops, didn't mean to/

**Comment by Suvanth-Erranki** [comment]
Again!
![image](https://user-images.githubusercontent.com/63676047/101423100-46f3e080-38c6-11eb-98ba-1ce3e3c33f04.png)

**Comment by Tianmu695** [comment]
cool

**Comment by Suvanth-Erranki** [comment]
Monsters get stuck so frequently!
![image](https://user-images.githubusercontent.com/63676047/101499463-4e090600-393b-11eb-8a4b-59af529de8d0.png)

**Comment by maitian352** [comment]
This has been fixed. The problem is that if you are dazed you can't move, so if a monster is on the side of another monster it gets dazed and can't move away and it gets dazed again and the loop continues.
