### ISSUE TITLE
glitch

### ISSUE THREAD

**Issue by ashyboiii** [maitian352/Meadow-Guarder#163]
i can craft infinite death books

**Comment by Suvanth-Erranki** [comment]
How does this work? You can dm Sp or me privately so that nobody abuses this.

**Comment by ashyboiii** [comment]
im pretty sure it happens after an hour or 2 when your ingame , leaving
stops the timer but rejoining continues it

**Comment by maitian352** [comment]
This was part of a huge bug where part of the trading process was handled on the client. It has been fixed.
