### ISSUE TITLE
Monster can push player into different region through bumping them - please change.

### ISSUE THREAD

**Issue by Suvanth-Erranki** [maitian352/Meadow-Guarder#164]
https://drive.google.com/file/d/1K1_wlsHfqpF-6pShG26uV1kN0DZrq5Pk/view

**Comment by maitian352** [comment]
Why is this a problem?

**Comment by Suvanth-Erranki** [comment]
I believe this is a problem because if monsters can't go into other regions, how come they can push players into other regions. Surely they can't do that?

**Comment by maitian352** [comment]
They can push players into other regions. Players have the ability to go to other regions but monsters don't, so even if they can't go into other regions themselves they can push players into other regions.
