### ISSUE TITLE
Why do I still have the text here!!1

### ISSUE THREAD

**Issue by Tianmu695** [maitian352/Meadow-Guarder#165]
![image](https://user-images.githubusercontent.com/68877583/101419332-c7621380-38bd-11eb-915d-95e3b36f44b5.png)
why,Why,WHY,WHY!!!!!!!!!!!!!!!!!!!!!!

**Comment by Tianmu695** [comment]
YAY, MY FIRST REAL BUG!!!!!!!!!!!!!

**Comment by Suvanth-Erranki** [comment]
Isn't this the village text - this should not be a bug - maybe the faded box of text should be but...

**Comment by Tianmu695** [comment]
I already played in the village for a minute!

**Comment by Suvanth-Erranki** [comment]
This isn't a bug - that text is supposed to be there - if the issue is that the text is faded, report it as a different issue. I am closing this.

**Comment by maitian352** [comment]
This has been fixed.

**Comment by maitian352** [comment]
The issue is that the text never fades completely, even though it should.
