### ISSUE TITLE
samuel keeps on spam camping he is abusing his power ask marcus and sullyboi

### ISSUE THREAD

**Issue by itsferytime** [maitian352/Meadow-Guarder#165]

**Comment by maitian352** [comment]
He doesn't have power.

**Comment by itsferytime** [comment]
He dose he is a ten eye monsterSent from my Metro By T-Mobile 4G LTE Android Device
-------- Original message --------From: maitian352 ***@***.***> Date: 12/2/21  7:24 PM  (GMT-06:00) To: maitian352/Meadow-Guarder ***@***.***> Cc: itsferytime ***@***.***>, Author ***@***.***> Subject: Re: [maitian352/Meadow-Guarder] samuel keeps on spam camping he is abusing his power ask marcus and sullyboi (Issue #165) 
He doesn't have power.

**Comment by maitian352** [comment]
I made him a ten eyed monster.
