### ISSUE TITLE
npm has a solution

### ISSUE THREAD

**Issue by definitely-nobody-is-here** [maitian352/Meadow-Guarder#167]
![image](https://user-images.githubusercontent.com/67865358/144712858-ffe5b8ed-b5d3-4d19-8a68-342e62c3c1b9.png)

go search npm. 
https://www.npmjs.com/package/leo-profanity
warns if inappropriate names are used

also have people been begging for admin why its not like there's any point its just rickroll and trolls and maybe a bit of /debug (but using it to get items is abuse)

**Comment by maitian352** [comment]
Already did, used https://www.npmjs.com/package/bad-words. I just put that as an extra warning, as there can be false negatives.

**Comment by definitely-nobody-is-here** [comment]
this one is bad

**Comment by maitian352** [comment]
Why?

**Comment by maitian352** [comment]
They want to be able to brag to their friends at school who also play meadow guarder.
