### ISSUE TITLE
1 in 10000 glitch (maybe less or more):

### ISSUE THREAD

**Issue by Suvanth-Erranki** [maitian352/Meadow-Guarder#167]
![image](https://user-images.githubusercontent.com/63676047/101499861-c1ab1300-393b-11eb-9436-46bec762e57b.png)
This is what happened:
The monster killed me but I had brought it down to 1 health or even less. As I died, I bumped into it. That's a glitch. I don't think the game registered that the monster got hit and should have lost health and died because I had died at the same time and the game only chose to register the event of me dying.

**Comment by Suvanth-Erranki** [comment]
Also, zoom in or view the picture in a new tab to see that I am touching the ball monster.

**Comment by Suvanth-Erranki** [comment]
Also, when I respawned, the monster was dead and was gone. Obviously, the game had stopped midway of processing the snowball monster's death even though it was dead.

**Comment by maitian352** [comment]
Just because your sprite is touching, that doesn't mean your hitbox is touching the monsters hitbox.

**Comment by maitian352** [comment]
This is the players actual hitbox.
![image](https://user-images.githubusercontent.com/68207888/101500673-c9b78280-393c-11eb-8a7a-5d38f1e370da.png)

**Comment by Suvanth-Erranki** [comment]
I know, but then how can you explain the fact that once I clicked respawn, the monster was gone - I didn't kill it, the game got rid of it.

**Comment by Suvanth-Erranki** [comment]
When I clicked respawn, me nor the monster moved and the monster was gone.

**Comment by maitian352** [comment]
When you respawned the monster hit your hitbox and it got killed.

**Comment by Suvanth-Erranki** [comment]
No, the monster didn't even respawn is what I am saying.

**Comment by maitian352** [comment]
Monsters can't respawn.

**Comment by maitian352** [comment]
Also, the monster updates first so the monster should have died and not you.

**Comment by Suvanth-Erranki** [comment]
I meant that when I respawned, there was no monster.

**Comment by maitian352** [comment]
The monster died right when you respawned.

**Comment by Suvanth-Erranki** [comment]
No, as soon as I respawned, the monster was already gone.

**Comment by maitian352** [comment]
No, it was killed and killed entities don't send out a update packet so it didn't display the monster. Even if it was a bug I also fixed it and now it updates both the player and the monster.

**Comment by maitian352** [comment]
Also, the game updates very fast, so maybe you just didn't catch the one frame of it dying?
