### ISSUE TITLE
Monsters get stuck bouncing in this spot:

### ISSUE THREAD

**Issue by Suvanth-Erranki** [maitian352/Meadow-Guarder#168]
The monster kept bouncing up and down here:
![image](https://user-images.githubusercontent.com/63676047/101521549-ff1b9a80-3953-11eb-93a9-c83d81893a8c.png)

**Comment by maitian352** [comment]
It isn't just this spot, this happens in other places too.

**Comment by maitian352** [comment]
I think this is fixed. Reopen this if it isn't.

**Comment by Suvanth-Erranki** [comment]
Still happening.

**Comment by maitian352** [comment]
This is a duplicate of #160, and the bouncing is the monster running away from you.

**Comment by maitian352** [comment]
There was a comment on another issue, but was meant to be posted here. This happened again, and the monster was on full health. This is because the monster healed.
