### ISSUE TITLE
Advanced death messages don't show sometimes.

### ISSUE THREAD

**Issue by Suvanth-Erranki** [maitian352/Meadow-Guarder#168]
I died to ten eyed one after i killed him, yet it didn't show that he killed me:
![unknown](https://user-images.githubusercontent.com/76885647/144726778-554de253-b219-4e6e-8c14-a37607e850fc.png)

Not a gameplay bug, just a visual error.

**Comment by maitian352** [comment]
This is caused because ten eyed one was killed, so the projectile that killed you couldn't find its parent and its parent's name.

**Comment by Suvanth-Erranki** [comment]
It happened again!
![image](https://user-images.githubusercontent.com/76885647/144730846-7d5006a4-cb53-4e53-9125-160b23958f01.png)

**Comment by definitely-nobody-is-here** [comment]
this is better than the projectiles despawning when their parent dies
just make projectiles store their parent name

**Comment by maitian352** [comment]
Fixed.
