### ISSUE TITLE
After staying in Seashore Province for a while, Ten Eyed One doesn't respawn.

### ISSUE THREAD

**Issue by Suvanth-Erranki** [maitian352/Meadow-Guarder#169]
I killed Ten Eyed One, then went to the left side of Seashore province, went idle for around 30 minutes, came back to the right side where Ten Eyed One should have respawned and he didn't respawn.

![image](https://user-images.githubusercontent.com/76885647/144729413-7aeb2c10-7ff3-41a0-98c4-488e012cfdf3.png)

**Comment by maitian352** [comment]
Either you got very unlucky, or one of your arrows/projectiles hit ten eyed one and killed him.

**Comment by Suvanth-Erranki** [comment]
> Either you got very unlucky, or one of your arrows/projectiles hit ten eyed one and killed him.

I didn't even shoot! I just moved to the area and wait for over 2 minutes and it didn't spawn.

**Comment by maitian352** [comment]
> > Either you got very unlucky, or one of your arrows/projectiles hit ten eyed one and killed him.
> 
> I didn't even shoot! I just moved to the area and waited for over 2 minutes and it didn't spawn.

If it was only 2 minutes, then it is unlucky.

**Comment by Suvanth-Erranki** [comment]
I'm not sure exactly the time, but I know it was over 2 minutes. Probably more.

**Comment by maitian352** [comment]
Also, how are there potions on the ground? If you went afk for 30 minutes, then all items would have despawned.

**Comment by Suvanth-Erranki** [comment]
I killed Ten Eyed One and didn't pick up the potions. I went idle and then came back 30 minutes later.

**Comment by Suvanth-Erranki** [comment]
Actually, I'm pretty sure I didn't wait long enough.

**Comment by maitian352** [comment]
You didn't pick up the potions. You waited 30 minutes. That means the potions despawned, as items despawn after 5 minutes. That means you killed Ten Eyed One while killing radioactive skeletons or randomly attacking.
