### ISSUE TITLE
If a monster bumps into you and moves you to another spot and you die, then if a monster spawns in that so

### ISSUE THREAD

**Issue by Suvanth-Erranki** [maitian352/Meadow-Guarder#169]
![image](https://user-images.githubusercontent.com/63676047/101522550-67b74700-3955-11eb-91d1-55ff79b8d176.png)
I spawned and then I was on top of the monster. That's the glitch.

**Comment by maitian352** [comment]
Why is this a bug?

**Comment by Suvanth-Erranki** [comment]
This is a bug because you can't share the same space as a monster right? Btw, this happened when I respawned to - I was on top of the cherry bomb.

**Comment by maitian352** [comment]
A dead person can share space with a monster.

**Comment by Suvanth-Erranki** [comment]
Yeah, but I was alive and this happened - I just couldn't take a screenshot in time.

**Comment by maitian352** [comment]
You can share space with a monster it you were inside the monster, it is just hard to get inside the monster.

**Comment by Suvanth-Erranki** [comment]
I wasn't inside, I was only partially on it.

**Comment by maitian352** [comment]
That is the same thing.

**Comment by Suvanth-Erranki** [comment]
Okay, but still fix.

**Comment by maitian352** [comment]
This won't work, because if I fix it then there will be another issue saying dead people can push monsters even though they are dead.
