### ISSUE TITLE
It can get confusing for the player to figure out where they are in the village.

### ISSUE THREAD

**Issue by Suvanth-Erranki** [maitian352/Meadow-Guarder#17]
There are two reasons for this:
1) The Npc and players are all walking over each other.
2) The Npc and players are hard to distinguish - only the health bar can really tell the location of the character.
![image](https://user-images.githubusercontent.com/63676047/97790034-c42b8780-1b9b-11eb-8040-30df871e3014.png)

**Comment by maitian352** [comment]
Fixed.
