### ISSUE TITLE
My inventory is glitching - it claims I am using numerous random items

### ISSUE THREAD

**Issue by Suvanth-Erranki** [maitian352/Meadow-Guarder#173]
![image](https://user-images.githubusercontent.com/76885647/145127906-1a602333-cffc-47ff-a08f-8ca711eb4ddc.png)

**Comment by maitian352** [comment]
How did you do this?

**Comment by Suvanth-Erranki** [comment]
![image](https://user-images.githubusercontent.com/76885647/147985844-013c16bf-9177-4bd8-b5db-344a9c899c4e.png)
