### ISSUE TITLE
Database

### ISSUE THREAD

**Issue by einVxncent** [maitian352/Meadow-Guarder#174]
Can you send me the server/DATABASE_URL.js?

**Comment by Suvanth-Erranki** [comment]
no, we won't give you.

**Comment by Suvanth-Erranki** [comment]
also, this isn't an issue, please don't report on github - dm or email sp or me.

**Comment by maitian352** [comment]
> Can you send me the server/DATABASE_URL.js?

That's literally the DATABASE URL, which allows you to access the database, so no.

**Comment by maitian352** [comment]
> Can you send me the server/DATABASE_URL.js?

Actually, yes.
The url is [here](https://www.youtube.com/watch?v=dQw4w9WgXcQ).

**Comment by einVxncent** [comment]
Is it possible to buy the DATABASE_URL.JS?

**Comment by maitian352** [comment]
Absolutely not.

**Comment by maitian352** [comment]
Actually, yes.

[The url is here](https://tinyurl.com/yryj6ka8)
