### ISSUE TITLE
I lost all my XP in level 12 and now I can't gain any XP.

### ISSUE THREAD

**Issue by Suvanth-Erranki** [maitian352/Meadow-Guarder#177]
![image](https://user-images.githubusercontent.com/76885647/145728424-99c70e8d-56f3-412c-a2df-3f0fa0a58917.png)

So I had around 30,000 XP in level 12 and i just lost the 30,000 randomly out of nowehre. I also noticed that I couldn't gain any XP by killing monsters. Please fix ASAP and return my 30,000 xp back to me.

This is a video of me unable to gain any XP by killing monsters: https://www.youtube.com/watch?v=Yb-ztBQcBb8

**Comment by Suvanth-Erranki** [comment]
Update: Apparently, now I am able to gain xp. What is happening?
![image](https://user-images.githubusercontent.com/76885647/145728750-48b91b90-c50f-4a6e-897e-196811768a94.png)

**Comment by maitian352** [comment]
Did you relog? This might have been caused by getting `null` xp.

**Comment by Suvanth-Erranki** [comment]
> Did you relog? This might have been caused by getting `null` xp.

What do you mean relog?

**Comment by maitian352** [comment]
Reload the page. I read the messages in discord, and i conclude that you got `null` xp from a monster because of a bug. This is why this happened.

**Comment by Suvanth-Erranki** [comment]
> Reload the page. I read the messages in discord, and i conclude that you got `null` xp from a monster because of a bug. This is why this happened.

Why did i get `null` xp from a monster? Also, can you give me back the xp?

**Comment by maitian352** [comment]
idk

**Comment by Suvanth-Erranki** [comment]
> idk

Idk why I got `null` xp or Idk if you'll give me back xp, or both?

**Comment by Suvanth-Erranki** [comment]
Also, should this issue be left open or close. I assume some bug caused the monster to give `null` xp that needs to be resolved, so I'm leaving this open.
