### ISSUE TITLE
Disconnections during Trade will result in Item Loss

### ISSUE THREAD

**Issue by Suvanth-Erranki** [maitian352/Meadow-Guarder#178]
If you are trading with someone and you get disconnected for some reason, you lose all the items you put in the trade box and you don't get anything back. This is horrible. There also isn't a guarantee that the other player will give you your items back. I've seen this happen with me and another player before and I gave him my items back. This definitely needs to be fixed so that you keep your items. 

Also, if both players get disconnected, they both lose the items they put in the trade box. This can be so bad in numerous occasions. For example, today, I traded 30 death globes with another player. If I got disconnected for some reason, I would have lost all my death globes. This issue can be very harmful in trades with powerful items or large quantities of items.

Please fix this issue. Thank you.

**Comment by Suvanth-Erranki** [comment]
Also, as a sidenote to everyone who has access to the `\kick` command, please do not abuse this during trades and scam other people. Thank you.

**Comment by maitian352** [comment]
It's fixed, now you don't lose items.
