### ISSUE TITLE
Monster can be trapped near a house by the side of it leaving it in a state where it can't move and can only fire at you.

### ISSUE THREAD

**Issue by Suvanth-Erranki** [maitian352/Meadow-Guarder#18]
![image](https://user-images.githubusercontent.com/63676047/97790096-25535b00-1b9c-11eb-9c13-af9ffd2d95c6.png)

**Comment by maitian352** [comment]
This is also related to [this](https://github.com/maitian352/Meadow-Guarder/issues/14), where the monster stops moving if it reaches its destination, the player.
