### ISSUE TITLE
The game is too confusing for new players who have no idea what to expect.

### ISSUE THREAD

**Issue by Suvanth-Erranki** [maitian352/Meadow-Guarder#180]
We need to create a tutorial on playing Meadow Guarder that a new player sees when they first log into the game.
![image](https://user-images.githubusercontent.com/76885647/145734086-539d6cdb-be6b-41fb-9cf1-5c921082db8f.png)

**Comment by Suvanth-Erranki** [comment]
We made a tutorial and we have a wiki that is linked to the front page. Isn't it good enough?

**Comment by maitian352** [comment]
idk

**Comment by Suvanth-Erranki** [comment]
Pretty sure we're good. We have also included a contact via email and discord.
