### ISSUE TITLE
Menu does not resize on window resize

### ISSUE THREAD

**Issue by definitely-nobody-is-here** [maitian352/Meadow-Guarder#182]
you can open the game and then resize the window, however if it becomes bigger the menu background does not.
![image](https://user-images.githubusercontent.com/67865358/115290608-be156d00-a121-11eb-8450-2f794c431455.png)

**Comment by maitian352** [comment]
This issue has been fixed.

**Comment by maitian352** [comment]
If this is still a bug in different browsers please take a screenshot and post it here.
