### ISSUE TITLE
game is vulnerable to javascript injects

### ISSUE THREAD

**Issue by definitely-nobody-is-here** [maitian352/Meadow-Guarder#183]
because this game is open-source, people can easily look into the server source code and hack by typing lines of javascript into the console.
you can easily bork the game like this

**Comment by definitely-nobody-is-here** [comment]
also your code is inefficient

**Comment by maitian352** [comment]
How do you hack it?

**Comment by maitian352** [comment]
What code is inefficient?

**Comment by definitely-nobody-is-here** [comment]
problme is solved but code is still inefficient

**Comment by maitian352** [comment]
what code is inefficient?
