### ISSUE TITLE
Neccesary scripts are placed in body after everything

### ISSUE THREAD

**Issue by definitely-nobody-is-here** [maitian352/Meadow-Guarder#184]
This can cause people with slower internet to not be able to load init scripts and things, it's also inefficient. It's standard to put most scripts in the head.

**Comment by definitely-nobody-is-here** [comment]
Those scripts will load AFTER everything else

**Comment by maitian352** [comment]
Well, the scripts have to load after everything else, otherwise there will be errors because the scripts depend on everything else.

**Comment by definitely-nobody-is-here** [comment]
then add defer
they will take up less loading time and will be parsed after loading

**Comment by maitian352** [comment]
Fixed.
