### ISSUE TITLE
Never use eval()

### ISSUE THREAD

**Issue by definitely-nobody-is-here** [maitian352/Meadow-Guarder#185]
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/eval#never_use_eval!

go read this. change it up. using Eval is inefficient and also dangerous

**Comment by maitian352** [comment]
How is it dangerous? Also this is a duplicate.

**Comment by definitely-nobody-is-here** [comment]
don't see this as an open issue so it isn't a duplicate. If the "other" issue is closed the problem should be solved, but it clearly still exists and so this issue should be here,

**Comment by definitely-nobody-is-here** [comment]
btw it's innefficient

**Comment by maitian352** [comment]
I don't really see this as an issue as the eval is used only for debugging.
