### ISSUE TITLE
Cherry Bombs can kill you after exploding

### ISSUE THREAD

**Issue by definitely-nobody-is-here** [maitian352/Meadow-Guarder#186]
They will explode, however they can still move, creating a moving explosion. This isn't good and you can dodge the explosion and still die.
![image](https://user-images.githubusercontent.com/67865358/116798576-14d65b80-aabf-11eb-8371-5ee8e37daa09.png)
And then they move and I die
![image](https://user-images.githubusercontent.com/67865358/116798588-2ddf0c80-aabf-11eb-8c27-de5f01a194c7.png)

**Comment by maitian352** [comment]
This issue has been fixed.
