### ISSUE TITLE
Monsters get stuck in one spot while circling

### ISSUE THREAD

**Issue by definitely-nobody-is-here** [maitian352/Meadow-Guarder#186]
![image](https://user-images.githubusercontent.com/67865358/146105954-f3476ca7-1835-472b-bdd8-0fbe214856c7.png)
why is this not fixed???
write your own pathfinding algorithm that checks the hitbox size!
Ten-Eyed-One, Skeleton King, and a Radioactive Skeleton are all stuck! All they do is move up and down!

**Comment by maitian352** [comment]
I believe this is fixed. Reopen if still happening.

**Comment by Suvanth-Erranki** [comment]
Still happening.
![image](https://user-images.githubusercontent.com/76885647/146282291-98313785-a2c7-4f83-80ce-b840f07a4e89.png)

**Comment by definitely-nobody-is-here** [comment]
it seems to be happening again since the maps were updated

**Comment by maitian352** [comment]
?

**Comment by maitian352** [comment]
I believe this is fixed. Reopen if still happening.

**Comment by Suvanth-Erranki** [comment]
![image](https://user-images.githubusercontent.com/76885647/146295747-8d8ac336-04b6-453f-bed2-bbedb07f5171.png)

Still happening.

**Comment by maitian352** [comment]
I believe this is fixed. Reopen if still happening.

**Comment by Suvanth-Erranki** [comment]
Nope, just happened.

**Comment by maitian352** [comment]
Can I have a screenshot?

**Comment by Suvanth-Erranki** [comment]
It's harder, but definitely possible. Let me try to get a screenshot.

**Comment by Suvanth-Erranki** [comment]
![image](https://user-images.githubusercontent.com/76885647/146483253-62b49581-aa8c-4bc2-b90c-c0c471530aef.png)

**Comment by Suvanth-Erranki** [comment]
![image](https://user-images.githubusercontent.com/76885647/146483658-3b33a413-aa3c-41cd-8884-c1066007d580.png)

**Comment by maitian352** [comment]
I believe this is fixed. Reopen if still happening.

**Comment by Suvanth-Erranki** [comment]
Just saw some monsters stuck on the bottom of Altoris Island. Unfortunately, I had auto attack on and killed him. Hopefully I can get a screenshot next time.

**Comment by Suvanth-Erranki** [comment]
![image](https://user-images.githubusercontent.com/76885647/147394758-44fa78ec-c505-4857-9bf0-5691c274033a.png)

**Comment by definitely-nobody-is-here** [comment]
![image](https://user-images.githubusercontent.com/67865358/147892977-513bb253-1c03-4f8a-b4b7-c65eab160f9b.png)

**Comment by Suvanth-Erranki** [comment]
![image](https://user-images.githubusercontent.com/76885647/148304741-0ead2c62-effd-454c-aa57-4d5fc63ded88.png)

**Comment by definitely-nobody-is-here** [comment]
![image](https://user-images.githubusercontent.com/67865358/148590687-58d2092f-3155-41b2-b074-c7239f4b4532.png)
still happening

**Comment by Suvanth-Erranki** [comment]
Yes, we know.

**Comment by Suvanth-Erranki** [comment]
![image](https://user-images.githubusercontent.com/76885647/148690741-819ec553-8591-4bdf-a42c-64e236ba56d7.png)

Ten Eyed One can easily get trapped.

**Comment by definitely-nobody-is-here** [comment]
now they're just stuck on nothing

**Comment by definitely-nobody-is-here** [comment]
just moving back and forth in one spot
so easy to kill

**Comment by definitely-nobody-is-here** [comment]
There was a karate skeleton in the forest fortress just walking up but not going anywhere
![image](https://user-images.githubusercontent.com/67865358/148849385-bc6e8435-49d2-4219-8305-dfe8674d6896.png)
here

**Comment by Suvanth-Erranki** [comment]
![image](https://user-images.githubusercontent.com/76885647/148851960-cafbdec5-5c7d-40ef-bce5-73c9f1b1a5ef.png)
 
 Again.

**Comment by Suvanth-Erranki** [comment]
Not fixed, I've seen several monsters get stuck.

**Comment by maitian352** [comment]
How?

**Comment by maitian352** [comment]
![image](https://user-images.githubusercontent.com/68207888/148862645-cec2268b-b854-4ed8-b7e3-7dd9a4b95dab.png)
This?

**Comment by Suvanth-Erranki** [comment]
No.

**Comment by Suvanth-Erranki** [comment]
Let me get a screenshot

**Comment by Suvanth-Erranki** [comment]
![image](https://user-images.githubusercontent.com/76885647/148862836-03f0ed06-bb3e-4e9e-a980-0d1336c393cb.png)

**Comment by Suvanth-Erranki** [comment]
They get stuck when attacking you, meaning that it is so easy to just shoot at them and kill them. I haven't seen them get stuck by themselves though, so that's fixed.

**Comment by Suvanth-Erranki** [comment]
Just saw a monster get stuck to a collision by itself.

**Comment by Suvanth-Erranki** [comment]
![image](https://user-images.githubusercontent.com/76885647/149037063-f8459cd4-4230-4ad6-b197-15ed08af3927.png)

**Comment by maitian352** [comment]
Did you have particles: 0%?

**Comment by Suvanth-Erranki** [comment]
> Did you have particles: 0%?

Yes.

**Comment by maitian352** [comment]
He might just have the frozen debuff.

**Comment by definitely-nobody-is-here** [comment]
![image](https://user-images.githubusercontent.com/67865358/149416182-7711583c-5de6-48c1-aab6-c6413f0df19f.png)
stuck

**Comment by Suvanth-Erranki** [comment]
> He might just have the frozen debuff.

I wasn't using weapons and he was moving back and forth.

**Comment by Suvanth-Erranki** [comment]
![image](https://user-images.githubusercontent.com/76885647/149632243-b50dd66f-f526-4465-a8a7-d883fa72d500.png)

Monster got stuck on me while I was dead.

**Comment by definitely-nobody-is-here** [comment]
https://github.com/definitely-nobody-is-here/Mountain_Guarder/issues/201

**Comment by Suvanth-Erranki** [comment]
![image](https://user-images.githubusercontent.com/76885647/149675955-7bc416d4-a815-45a2-a168-4e5e787bfcf2.png)

**Comment by maitian352** [comment]
It's not circling, its wandering.

**Comment by Suvanth-Erranki** [comment]
![image](https://user-images.githubusercontent.com/76885647/149811205-cbd8ac55-2926-407a-a6a9-9654487ff8b6.png)

Monsters get stuck bouncing up and down. Pathfinding is definitely broken.

**Comment by definitely-nobody-is-here** [comment]
Is it fixed yet?
