### ISSUE TITLE
Math.random() is not cryptographically secure

### ISSUE THREAD

**Issue by definitely-nobody-is-here** [maitian352/Meadow-Guarder#187]
![image](https://user-images.githubusercontent.com/67865358/116896251-0c3a6e00-ac02-11eb-94cc-54e7e0da519f.png)
I got a warning from the security warning from nodejsscan with this same thing, you should fix this and use a secure id generator.
![image](https://user-images.githubusercontent.com/67865358/116896468-46a40b00-ac02-11eb-98b9-427f09a2b725.png)

**Comment by definitely-nobody-is-here** [comment]
I feel like he never pays attention to the issues tab anymore.

**Comment by maitian352** [comment]
Why does it have to be secure?

**Comment by definitely-nobody-is-here** [comment]
ok go ahead get your accounts hacked

**Comment by maitian352** [comment]
Go and hack it. Once you do I can fix it.

**Comment by maitian352** [comment]
The whole points of having Math.random() there is so that no two players have the same id.
