### ISSUE TITLE
I crashed the server

### ISSUE THREAD

**Issue by definitely-nobody-is-here** [maitian352/Meadow-Guarder#190]
was fighting red boss and crashed the server.

**Comment by definitely-nobody-is-here** [comment]
![image](https://user-images.githubusercontent.com/67865358/117578515-bca1e980-b0bc-11eb-935a-36b585f117b1.png)
trying again at 10 fps and 100000 ping and lag

**Comment by maitian352** [comment]
Will fix and will nerf earth book.
