### ISSUE TITLE
Closing the inventory window during an enchant process allows you to enchant while anywhere

### ISSUE THREAD

**Issue by definitely-nobody-is-here** [maitian352/Meadow-Guarder#191]
I closed the enchant window and left the town hall. Then I just opened my inventory and it allowed me to enchant my stuff outside of town hall
![image](https://user-images.githubusercontent.com/67865358/117578607-228e7100-b0bd-11eb-946d-db6afc869b86.png)

**Comment by definitely-nobody-is-here** [comment]
also there should be a door closed texture on this shed
![image](https://user-images.githubusercontent.com/67865358/117578702-8fa20680-b0bd-11eb-89cc-b58bd365f06e.png)

**Comment by maitian352** [comment]
The door is wontadd, and the enchant thing is because the wizard has MAGIC.
