### ISSUE TITLE
Pathfinding breaks sometimes - monsters get stuck moving left right every other frame kind of

### ISSUE THREAD

**Issue by Suvanth-Erranki** [maitian352/Meadow-Guarder#193]
Video: https://youtu.be/z0c99ab-5eI

**Comment by definitely-nobody-is-here** [comment]
the monster could be trying to circle you but there are collisions in the way and it keeps switching directions since the raycast thingymabob is in the collision.

**Comment by maitian352** [comment]
I believe this is fixed. Reopen if still happening.

**Comment by Suvanth-Erranki** [comment]
Pretty sure it's fixed, I tried trapping Ten Eyed One in the spots he usually get's trapped in. He didn't get trapped.
