### ISSUE TITLE
It is possible to pick up items during respawning, even though you shouldn't be able to.

### ISSUE THREAD

**Issue by Suvanth-Erranki** [maitian352/Meadow-Guarder#195]
This was extremely difficult, but let me explain how I think I did it:

1) I killed a Radioactive Skeleton which dropped two meterorite coins.
2) Skeleton King spawned and quickly killed me, as I was unprepared.
3) As I respawned, there was a brief moment where I was alive and still in the same location.
4) During this extremely miniscule period, I was able to click on the meteorite coins and they went into my inventory.
5) I got teleported back to the inn.

What I think is happening is that when respawning, the player first gains hp before teleporting back to the inn. I think this should be reversed: the player teleports to the inn and then gains hp. I'm not sure if this is exactly how the process works, but otherwise, I can't seem to understand I picked up the two meteorite coins.

**Comment by definitely-nobody-is-here** [comment]
the player should be dead, then teleports, then gets hp, and then is not dead

**Comment by maitian352** [comment]
There's actually no "dead" property of a player, it just checks the hp.
