### ISSUE TITLE
The currency system makes absolutely no sense! 

### ISSUE THREAD

**Issue by Suvanth-Erranki** [maitian352/Meadow-Guarder#196]
This is the rarity of each type of coin:

- Copper Coin: 1.0
- Silver Coin: 2.0
- Gold Coin: 3.0
- Meteorite Coin: 4.0

This should mean that:

- 3 meteorite coins have as much value as 4 gold coins
- 2 gold coins have as much value as 3 silver coins
- 1 silver coin have as much value as 2 copper coins

But in crafting:

- 1 meteorite coin costs 100 gold coins
- 1 gold coin costs 100 silver coins
- 1 silver coin costs 100 copper coins

This makes no sesnse, because the rarity of a coin should affect its value in currency. This would be like saying:

1 meteorite coin = 1 million copper coins

This also devalues the currency, because once you get 1 meteorite coin, you could buy enormous amounts of material in shops where they sell items for copper/silver/gold coins.

Please fix the currency system, this is a huge problem that must be resolved.

**Comment by maitian352** [comment]
The rarity system is not linear and doesn't match with every item.

**Comment by maitian352** [comment]
Additionally, the drop chance for every coin and material is the same, 1/82.

**Comment by maitian352** [comment]
Connects with #115

**Comment by Suvanth-Erranki** [comment]
> Additionally, the drop chance for every coin and material is the same, 1/82.
> The rarity system is not linear and doesn't match with every item.

Acknowledged, and I really meant to say that it's not like getting a meteorite coin is a 100 times rarer than getting a gold coin or something. I just think that the currency system should be more equal.

**Comment by maitian352** [comment]
> > Additionally, the drop chance for every coin and material is the same, 1/82.
> > The rarity system is not linear and doesn't match with every item.
> 
> Acknowledged, and I really meant to say that it's not like getting a meteorite coin is a 100 times rarer than getting a gold coin or something. I just think that the currency system should be more equal.

How should I make the currency system more equal?
