### ISSUE TITLE
i can type in chat while dead?

### ISSUE THREAD

**Issue by definitely-nobody-is-here** [maitian352/Meadow-Guarder#198]
![image](https://user-images.githubusercontent.com/67865358/147395974-1b2170db-71d1-43a2-ac6e-dabe800edc88.png)
![image](https://user-images.githubusercontent.com/67865358/147395977-d2877b0c-f4fe-4c2b-a040-85511b279e15.png)
also what

**Comment by maitian352** [comment]
Fixed. Now the death screen is under the chat screen.
