### ISSUE TITLE
why is the server lagging

### ISSUE THREAD

**Issue by definitely-nobody-is-here** [maitian352/Meadow-Guarder#199]
there are like 100 ten-eyed-ones in the inn and its lagging

**Comment by definitely-nobody-is-here** [comment]
![image](https://user-images.githubusercontent.com/67865358/147396040-0fc6a8d6-eb36-4313-92ae-ffe6fbaf37a4.png)

**Comment by definitely-nobody-is-here** [comment]
lag

**Comment by definitely-nobody-is-here** [comment]
![image](https://user-images.githubusercontent.com/67865358/147396060-7c0108b9-0abb-4272-a054-2d95080f14e3.png)
still lagging

**Comment by definitely-nobody-is-here** [comment]
suvanth is moving really fast its lagging more now

**Comment by definitely-nobody-is-here** [comment]
![image](https://user-images.githubusercontent.com/67865358/147396071-644fbb38-2c25-4421-8654-a2db569e77f2.png)
AAAAAAA

**Comment by definitely-nobody-is-here** [comment]
![image](https://user-images.githubusercontent.com/67865358/147396202-d48711cd-0b20-415b-b84c-237786ec7b92.png)
image credits to @Suvanth-Erranki

**Comment by maitian352** [comment]
Why do you think?
