### ISSUE TITLE
The cave has an unmapped section where the player can hide from the monsters and the monsters won't chase them.

### ISSUE THREAD

**Issue by Suvanth-Erranki** [maitian352/Meadow-Guarder#20]
![image](https://user-images.githubusercontent.com/63676047/97790225-2f298e00-1b9d-11eb-9880-26a68ab29cb5.png)

**Comment by maitian352** [comment]
This will be mapped. Soon.

**Comment by maitian352** [comment]
This has been mapped, and isn't a bug anymore.
