### ISSUE TITLE
Deployments contain invalid deployment environment

### ISSUE THREAD

**Issue by definitely-nobody-is-here** [maitian352/Meadow-Guarder#200]
![image](https://user-images.githubusercontent.com/67865358/117659670-3cd25880-b16a-11eb-851d-236fd6be672c.png)
![image](https://user-images.githubusercontent.com/67865358/117659688-422fa300-b16a-11eb-8873-ba97ad3ce737.png)

**Comment by definitely-nobody-is-here** [comment]
just set it to inactive already!

**Comment by maitian352** [comment]
I don't know how
