### ISSUE TITLE
The "delete account" button is right next to the login stuff and you can accidentally delete your account

### ISSUE THREAD

**Issue by definitely-nobody-is-here** [maitian352/Meadow-Guarder#209]
it's too close to everything and there is no confirm button. it just deletes your account.
![image](https://user-images.githubusercontent.com/67865358/118343430-ff1d5900-b4f6-11eb-9c7d-be084178277a.png)
too easy to lose everything

ADD A CONFIRM BUTTON

**Comment by maitian352** [comment]
A confirm button has been added.
