### ISSUE TITLE
with ENV.PVP you can get stuck in map transitions

### ISSUE THREAD

**Issue by definitely-nobody-is-here** [maitian352/Meadow-Guarder#212]
![image](https://user-images.githubusercontent.com/67865358/118344708-be750e00-b4fd-11eb-8529-eee4b8945b2a.png)

**Comment by definitely-nobody-is-here** [comment]
you can get stuck anywhere when the players are placed inside each other
![image](https://user-images.githubusercontent.com/67865358/118345109-6986c700-b500-11eb-9f58-aaff09a8b7b9.png)

**Comment by maitian352** [comment]
This is experimental and will be tested, so this isn't an issue.
