### ISSUE TITLE
water book is broken

### ISSUE THREAD

**Issue by definitely-nobody-is-here** [maitian352/Meadow-Guarder#213]
![image](https://user-images.githubusercontent.com/67865358/118344839-71de0280-b4fe-11eb-9067-120b23a21f68.png)
also rubberbanding galore

**Comment by definitely-nobody-is-here** [comment]
![image](https://user-images.githubusercontent.com/67865358/118344913-09dbec00-b4ff-11eb-80ea-1d188bd7a218.png)

**Comment by definitely-nobody-is-here** [comment]
![image](https://user-images.githubusercontent.com/67865358/118344932-237d3380-b4ff-11eb-8634-78a576505902.png)

**Comment by maitian352** [comment]
Water book has been nerfed, but comment if you run into run into this again.
