### ISSUE TITLE
Floating point error

### ISSUE THREAD

**Issue by definitely-nobody-is-here** [maitian352/Meadow-Guarder#216]
![image](https://user-images.githubusercontent.com/67865358/147893117-fa39cb8e-aed9-47fc-bae3-9b3e9ae1e14b.png)

**Comment by Suvanth-Erranki** [comment]
Maitian already told me about this some while back. It's a rounding error.

**Comment by maitian352** [comment]
This glitch is very confusing. Server side and client side, when I log the value, it is correct. But somehow it is displayed as this.

**Comment by maitian352** [comment]
Fixed.
