### ISSUE TITLE
still desync between server and client

### ISSUE THREAD

**Issue by definitely-nobody-is-here** [maitian352/Meadow-Guarder#219]
the client still highlights one item and the server will pick up another when the items are on top of one another

mountain guarder has no problems with this why does meadow guarder?

**Comment by maitian352** [comment]
Because the client has items filtered by y value but the server doesnt do that to increase performance.

**Comment by definitely-nobody-is-here** [comment]
ok mountain guarder also does that
also when you hover over an item in meadow guarder it doesn't choose the top one, it chooses the one that comes first in the list. The server should do the same so it doesn't have desync. When I pick up an item, it always picks up the one on the top of the pile. The one you is highlighted is the one you should pick up, not the one that appears on top.

**Comment by maitian352** [comment]
Fixed.
