### ISSUE TITLE
There are only a few items

### ISSUE THREAD

**Issue by definitely-nobody-is-here** [maitian352/Meadow-Guarder#22]
there are literally 4 weapons
axe
sword
staff
crossbow
and then there is a hat and armor
and then there is a stupid scythe and a dumb axe
and they all suck
they all are either rusty or bad materials
except the staff
add more
BUG

**Comment by maitian352** [comment]
no you literally didn't craft anything

**Comment by maitian352** [comment]
like back then there were like 20 items and now i believe there are like 260 items

**Comment by maitian352** [comment]
Now there are over 350 items.
