### ISSUE TITLE
Players can abuse the auto move and auto click glitch.

### ISSUE THREAD

**Issue by Suvanth-Erranki** [maitian352/Meadow-Guarder#22]
Players can hold down the mouse/touchpad or a moving key (WASD) and then move to another tab and let go while it still registers in the game that you are holding them down thus, the bullets are auto fired and you can auto move too.
A possible solution is to detect if the player moves to another tab and stop the game from doing the glitch. You can use 
page visibility web API: https://developer.mozilla.org/en-US/docs/Web/API/Page_Visibility_API  - or maybe
window.onfocus and window.onblur: https://developer.mozilla.org/en-US/docs/Web/API/Window/focus_event

![image](https://user-images.githubusercontent.com/63676047/97790453-0f936500-1b9f-11eb-98b4-43699dd6419c.png)

**Comment by Suvanth-Erranki** [comment]
UPDATE: 

Maitian, I found a way to detect if the user switches tabs. By using the following code:

document.addEventListener("visibilitychange", function() {
    var hidden = document.hidden 
    if (hidden = true) {
        // STOP THE GLITCH FROM HAPPENING!!!!
    }
});

you can execute the code inside the "if" condition when the player switches tabs and the code executed can stop the auto move/auto click glitch. While i haven't developed a solution for that yet, this is a great start to do so.

**Comment by maitian352** [comment]
Thanks, Suvanth. This has been fixed.
