### ISSUE TITLE
resized image is not resized

### ISSUE THREAD

**Issue by definitely-nobody-is-here** [maitian352/Meadow-Guarder#221]
i try to resize an image and it becomes big.

**Comment by definitely-nobody-is-here** [comment]
![image](https://user-images.githubusercontent.com/67865358/118842625-617bae00-b897-11eb-9593-5bed250ed0be.png)

**Comment by maitian352** [comment]
How is this an issue?

**Comment by definitely-nobody-is-here** [comment]
cannot resize

**Comment by definitely-nobody-is-here** [comment]
totally not

**Comment by definitely-nobody-is-here** [comment]
resize = no

**Comment by definitely-nobody-is-here** [comment]
how do you resize an image on a canvas

**Comment by definitely-nobody-is-here** [comment]
HOW OD IMAGE RESIZE IMAGE

**Comment by maitian352** [comment]
ctx.drawImage(image,x,y,width,height);

**Comment by definitely-nobody-is-here** [comment]
**
![image](https://user-images.githubusercontent.com/67865358/119197266-756d0e80-ba55-11eb-9f39-2ac18bb44a83.png)
**

**Comment by definitely-nobody-is-here** [comment]
what
