### ISSUE TITLE
I DELETED EVERYTHING

### ISSUE THREAD

**Issue by definitely-nobody-is-here** [maitian352/Meadow-Guarder#222]
I DIDNT MAKE A BACKUP

HELP!!!!!!!!!!!!!!!!!!
HOW OD I RECOVER STUFF WHEN GITHUB OVERWRITES EVERYTHING WITH ERRORS

**Comment by maitian352** [comment]
Can you post things like this in Discussions?

**Comment by definitely-nobody-is-here** [comment]
fixed it
