### ISSUE TITLE
water book ends up firing in illegal zones (why you should fill in places with collision)

### ISSUE THREAD

**Issue by definitely-nobody-is-here** [maitian352/Meadow-Guarder#223]
![Screenshot (31359)](https://user-images.githubusercontent.com/67865358/119011011-9acd2000-b962-11eb-83c2-db007b1c00f0.png)

**Comment by definitely-nobody-is-here** [comment]
![image](https://user-images.githubusercontent.com/67865358/119029817-2355bb80-b977-11eb-92ad-d2dadd1480eb.png)

**Comment by definitely-nobody-is-here** [comment]
![image](https://user-images.githubusercontent.com/67865358/119029865-2fda1400-b977-11eb-82f0-6f628b5929cf.png)

**Comment by definitely-nobody-is-here** [comment]
all you need to do it just fire while near collisions.
![image](https://user-images.githubusercontent.com/67865358/119029940-46806b00-b977-11eb-8bc4-e347cdd634b6.png)

**Comment by definitely-nobody-is-here** [comment]
![image](https://user-images.githubusercontent.com/67865358/119029996-5730e100-b977-11eb-9862-690e0f8a15ee.png)

**Comment by definitely-nobody-is-here** [comment]
It's also pretty laggy because of all those entities

**Comment by definitely-nobody-is-here** [comment]
just fill in the void where there is no collision with collision and when a projectile is inside a collision far enough it gets deleted.

**Comment by maitian352** [comment]
It would be even laggier if you filled it all with collisions.

**Comment by definitely-nobody-is-here** [comment]
it would not be laggy if the collisions were optimized to only check the spot that it's in and 4 surrounding spots

**Comment by maitian352** [comment]
That is what the collisions do.

**Comment by maitian352** [comment]
I think the main problem is how the projectiles are shot and how they detect collisions, because even if the map is filled with collisions it would still be able to pass through other collisions like the wood wall in Weird Tower and Clear Tower.

**Comment by maitian352** [comment]
This issue seems to be fixed, if this comes up again please comment.
