### ISSUE TITLE
secondary attack has less value than primary

### ISSUE THREAD

**Issue by definitely-nobody-is-here** [maitian352/Meadow-Guarder#224]
for most attacks, the secondary one always has a lower bullet-to-mana ratio. it's less valuable so it is useless

**Comment by maitian352** [comment]
So which attacks? I know water book is one but I think that is it. Earth book secondary attack is OP and fire book secondary attack shoots around you when the main attack shoots in all directions which might miss.

**Comment by maitian352** [comment]
Secondary attacks are going to be changed and are now temporarily disabled.

**Comment by maitian352** [comment]
hahaha secondary attack -> click at npc and swtich weaopn -> talk to npc

**Comment by maitian352** [comment]
> for most attacks, the secondary one always has a lower bullet-to-mana ratio. it's less valuable so it is useless

A high bullet-to-mana ratio doesn't always mean a weapon is better. For example, which weapon is better?

Weapon 1: Shoots one bullet that does 1000 damage, uses 500 mana.

Weapon 2: Shoots one bullet that does 10 damage, uses 1 mana.
