### ISSUE TITLE
wizard hats are listed backwards in the crafting

### ISSUE THREAD

**Issue by definitely-nobody-is-here** [maitian352/Meadow-Guarder#224]
for every other item, going down down the list means better, but for wizard hats the best one is first

**Comment by definitely-nobody-is-here** [comment]
same thing for amulets

**Comment by maitian352** [comment]
No, red fedora is the best fedora and is listed first.

**Comment by definitely-nobody-is-here** [comment]
but what about the hats and amulets

**Comment by maitian352** [comment]
What is wrong with the best item being listed first? Also there is no "best" amulet, they are all equal.

**Comment by definitely-nobody-is-here** [comment]
Ok, they are listed backwards in terms of crafting easiness
