### ISSUE TITLE
SERVER CRASEHED

### ISSUE THREAD

**Issue by definitely-nobody-is-here** [maitian352/Meadow-Guarder#225]
AAAA I JOINED AND IT CRASHED!!!
![image](https://user-images.githubusercontent.com/67865358/147959792-054f7fe5-fc92-43e4-95c8-df06f3d134f4.png)
![image](https://user-images.githubusercontent.com/67865358/147959827-4dc0290c-a30e-432e-b163-ed857df0901c.png)
and then it crashed

**Comment by maitian352** [comment]
I used /exit

**Comment by definitely-nobody-is-here** [comment]
well you said submit crash reports when it crashed
