### ISSUE TITLE
fonts broke

### ISSUE THREAD

**Issue by definitely-nobody-is-here** [maitian352/Meadow-Guarder#226]
![image](https://user-images.githubusercontent.com/67865358/147962509-9bfd185b-8028-4c86-9189-5a4c214ce193.png)
packet loss?
![image](https://user-images.githubusercontent.com/67865358/147962530-b0d3d191-7030-45f7-aaf4-b55c58c786cf.png)

**Comment by maitian352** [comment]
It couldn't load.
