### ISSUE TITLE
Game soft-locks if you die just after completing a quest

### ISSUE THREAD

**Issue by definitely-nobody-is-here** [maitian352/Meadow-Guarder#227]
![image](https://user-images.githubusercontent.com/67865358/119266661-b120e900-bbb9-11eb-927d-ec0f82558f08.png)
i have to log out and log back in because the quest is invalid so it doesn't do anything but its on my screen so I cant move

**Comment by maitian352** [comment]
This is because you died and then Tianmu killed the monster, but when you respawn the quest becomes 'none' in the server but the popup message is still displayed on the client side.

**Comment by maitian352** [comment]
Fixed.
