### ISSUE TITLE
Type Error: Cannot read properties of undefined (reading 'id')

### ISSUE THREAD

**Issue by Suvanth-Erranki** [maitian352/Meadow-Guarder#229]
![image](https://user-images.githubusercontent.com/76885647/148121050-90fbc9ea-5f90-4397-947c-3439469be35b.png)

**Comment by maitian352** [comment]
It's in beta testing.

**Comment by Suvanth-Erranki** [comment]
I meant to take a screenshot of the error in #errors channel.
