### ISSUE TITLE
I GOT A DEV KEY

### ISSUE THREAD

**Issue by definitely-nobody-is-here** [maitian352/Meadow-Guarder#229]
![image](https://user-images.githubusercontent.com/67865358/119386855-219d3800-bc96-11eb-9da3-f5788bcce536.png)

**Comment by definitely-nobody-is-here** [comment]
what does it do

**Comment by maitian352** [comment]
It makes you unable to obtain items.

**Comment by definitely-nobody-is-here** [comment]
bruh

**Comment by maitian352** [comment]
It becomes annoying when you test a new feature and you just get 1000 items

**Comment by definitely-nobody-is-here** [comment]
i have basically the best stuff now so yeah its useful
