### ISSUE TITLE
It becomes laggy for the server to handle large amounts of projectiles because the entity to projectile collision detection inefficient

### ISSUE THREAD

**Issue by maitian352** [maitian352/Meadow-Guarder#233]

**Comment by maitian352** [comment]
Fixed.

**Comment by maitian352** [comment]
Still an issue, but a minor one.

**Comment by definitely-nobody-is-here** [comment]
btw i tested the collision efficiency of mine and it worked on the most resource-heavy bullet, pathfind bullets

**Comment by maitian352** [comment]
How are pathfind bullets the most resource intensive?

**Comment by definitely-nobody-is-here** [comment]
it doesnt matter i tested with a bunch of bots to collide with and summoned a bullet every tick and it was fine-ish

**Comment by definitely-nobody-is-here** [comment]
also pathfind bullets are the most resource intensive because they pathfind every tick

**Comment by definitely-nobody-is-here** [comment]
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA SUPER LAGGY
