### ISSUE TITLE
items can render outside of rooms

### ISSUE THREAD

**Issue by definitely-nobody-is-here** [maitian352/Meadow-Guarder#234]
![image](https://user-images.githubusercontent.com/67865358/119391248-206f0980-bc9c-11eb-97a1-486a69ebf631.png)

**Comment by maitian352** [comment]
How would you render the items then? Just cut them off?

**Comment by definitely-nobody-is-here** [comment]
just add black tiles outside of the room instead of transparent ones

**Comment by maitian352** [comment]
Fixed.
