### ISSUE TITLE
You can store more items in your inventory than you have

### ISSUE THREAD

**Issue by Suvanth-Erranki** [maitian352/Meadow-Guarder#235]
Proof:

I did the command `/seeinv suvanth`. At the bottom of the items I had, it says I have 1 lead.

![image](https://user-images.githubusercontent.com/76885647/148310099-4b86800f-e441-45b8-bf19-3f2e2000a61a.png)

Where is my lead in my inventory? You can't see it.

![image](https://user-images.githubusercontent.com/76885647/148310121-a1b93595-8fad-4e84-938d-c4b79f275700.png)

This glitch has something to do with trading that allows you to keep items when your inventory is full. This bug is still being investigated and its full origin isn't clear. This has occured multiple times to me.

**Comment by definitely-nobody-is-here** [comment]
perhaps picking up items while there are items in the trading menu and then exiting the trade and the items are added back, causing overflow

**Comment by maitian352** [comment]
> perhaps picking up items while there are items in the trading menu and then exiting the trade and the items are added back, causing overflow

Actually, picking up items put them in the trade menu. I made a typo.
