### ISSUE TITLE
Server randomly disconnects you if you go idle.

### ISSUE THREAD

**Issue by Suvanth-Erranki** [maitian352/Meadow-Guarder#236]
It has happened so many times to me, even though my wifi is strong.
![image](https://user-images.githubusercontent.com/76885647/148450634-62838938-2f2e-4ec1-8492-44201554a73b.png)

**Comment by definitely-nobody-is-here** [comment]
It's supposed to. You go afk and you get disconnected for idling.

**Comment by definitely-nobody-is-here** [comment]
It's also called heroku

**Comment by Suvanth-Erranki** [comment]
> It's supposed to. You go afk and you get disconnected for idling.

What if you have to go to the bathroom or go somewhere else to do something, and when you come back, you've been signed out?
It's kind of like google sign out error.

**Comment by maitian352** [comment]
I have been logged on for more than 1 hour and more than 40 minutes of it is afk and I didn't get kicked.

**Comment by Suvanth-Erranki** [comment]
I'm gonna check if it still happens.

**Comment by Suvanth-Erranki** [comment]
Pretty sure it doesn't happen anymore. Reopen if it does.

**Comment by Suvanth-Erranki** [comment]
Wait, I just checked and i got disconnected. Did anyone restart the server?

**Comment by maitian352** [comment]
Yes.
