### ISSUE TITLE
Meadow Guarder uses so much memory!

### ISSUE THREAD

**Issue by Suvanth-Erranki** [maitian352/Meadow-Guarder#237]
![image](https://user-images.githubusercontent.com/76885647/148451127-5b71bed9-9aee-430e-a99f-0b883b0a8b77.png)

**Comment by maitian352** [comment]
How do i fix this

**Comment by definitely-nobody-is-here** [comment]
unload stuff

**Comment by definitely-nobody-is-here** [comment]
clear up cache?

**Comment by definitely-nobody-is-here** [comment]
![image](https://user-images.githubusercontent.com/67865358/148452396-448d32e1-4665-4fe4-8fc9-06ed160a87f4.png)

**Comment by definitely-nobody-is-here** [comment]
![image](https://user-images.githubusercontent.com/67865358/148452595-f90f1c61-2fc1-42a1-9751-36a57d8f7880.png)
It's really a lot. Here's Mountain Guarder for comparison.
![image](https://user-images.githubusercontent.com/67865358/148452839-ac603236-dc8e-4db2-bf28-e421c1b39839.png)
It uses more GPU but less RAM

**Comment by maitian352** [comment]
But if I unload the images then laggy

**Comment by Suvanth-Erranki** [comment]
https://stackoverflow.com/questions/10329619/reducing-memory-footprint-of-existing-web-page

**Comment by maitian352** [comment]
The main problem is all the images that are loaded.
