### ISSUE TITLE
server crashes when maitian smited me too much

### ISSUE THREAD

**Issue by definitely-nobody-is-here** [maitian352/Meadow-Guarder#237]
![image](https://user-images.githubusercontent.com/67865358/119392986-6c22b280-bc9e-11eb-8908-92bf5a52b932.png)

**Comment by definitely-nobody-is-here** [comment]
![image](https://user-images.githubusercontent.com/67865358/119393074-7e045580-bc9e-11eb-95be-889e672fd8aa.png)

**Comment by maitian352** [comment]
How is this an issue?
