### ISSUE TITLE
The screen becomes weird when it changes maps. Any way to fix?

### ISSUE THREAD

**Issue by Suvanth-Erranki** [maitian352/Meadow-Guarder#238]
![image](https://user-images.githubusercontent.com/76885647/148457812-31b6e969-f188-4a88-b09d-ed6ab7ce5446.png)

For a brief moment, I see this sometimes when changing maps, usually when there is lots of lag and it takes time for the maps to load.

**Comment by maitian352** [comment]
The map fades out.

**Comment by Suvanth-Erranki** [comment]
I know, but look at the position of the player. You see yourself in two different positions because of lag.
