### ISSUE TITLE
THIS ISSUE yeT AGAIN

### ISSUE THREAD

**Issue by definitely-nobody-is-here** [maitian352/Meadow-Guarder#238]
![image](https://user-images.githubusercontent.com/67865358/119393255-b5730200-bc9e-11eb-815e-7805a85ff2fd.png)
its not fixed!!!

**Comment by maitian352** [comment]
I didn't update the server.

**Comment by definitely-nobody-is-here** [comment]
UPDATE THE SERVER
![image](https://user-images.githubusercontent.com/67865358/119501136-94f68680-bd36-11eb-9d04-210a9509cd8a.png)
