### ISSUE TITLE
Maps are rarely added.

### ISSUE THREAD

**Issue by Suvanth-Erranki** [maitian352/Meadow-Guarder#239]
If more maps are added, the game will becoming A LOT more interesting and engaigng and fun, but this happens so infrequently. Can we speed up this process? Also, what kind of maps should I start making?

**Comment by maitian352** [comment]
Add More Maps -> More Monsters -> More Lag -> Game Unplayable -> Players Quit -> Meadow Guarder Dies

**Comment by Suvanth-Erranki** [comment]
But everyone wants more maps. The game needs more maps.
![image](https://user-images.githubusercontent.com/76885647/148458603-e728fd56-cf30-4939-a811-5de62d7df708.png)

**Comment by maitian352** [comment]
fine ill add another house map

**Comment by definitely-nobody-is-here** [comment]
just optimize monsters, add inactive modes to reduce lag, optimise/minimize packets sent by server (includes size).
mountain guarder has done this.

**Comment by maitian352** [comment]
> just optimize monsters, add inactive modes to reduce lag, optimise/minimize packets sent by server (includes size). mountain guarder has done this.

Done all of this 2 months ago.
