### ISSUE TITLE
items are blurry and render under objects

### ISSUE THREAD

**Issue by definitely-nobody-is-here** [maitian352/Meadow-Guarder#239]
![image](https://user-images.githubusercontent.com/67865358/119500008-53191080-bd35-11eb-9ca2-4bf1c1b7a885.png)
i dont know how to fix this

**Comment by definitely-nobody-is-here** [comment]
![image](https://user-images.githubusercontent.com/67865358/119500659-084bc880-bd36-11eb-8299-7217dcf697c7.png)

**Comment by maitian352** [comment]
The server didn't update yet.
