### ISSUE TITLE
Daylight savings happened last night so the time is 1 hour behind in the game.

### ISSUE THREAD

**Issue by Suvanth-Erranki** [maitian352/Meadow-Guarder#24]
The time says in the chat in the photo - 11:10 - when in fact it was 12:10.
![image](https://user-images.githubusercontent.com/63676047/97808131-fe943380-1c32-11eb-9e58-58d12484f7c5.png)

**Comment by maitian352** [comment]
Actually it is 11:10, and I think you didn't set your clocks.

**Comment by Suvanth-Erranki** [comment]
Oh. :(
