### ISSUE TITLE
The rain has a few problems

### ISSUE THREAD

**Issue by definitely-nobody-is-here** [maitian352/Meadow-Guarder#240]
It's a bit too dim. It's really hard to see and the ui hurts your eyes once you adjust.
also it looks weird on houses.
![image](https://user-images.githubusercontent.com/67865358/148589800-e7fefa6e-fc99-425e-b79f-866f5be631ef.png)
also they too common there was 5 seconds of no precipitation in a total of 10 minutes

**Comment by Suvanth-Erranki** [comment]
I kinda agree with this.
