### ISSUE TITLE
oh no the canvas is borken

### ISSUE THREAD

**Issue by definitely-nobody-is-here** [maitian352/Meadow-Guarder#241]
![image](https://user-images.githubusercontent.com/67865358/148590898-f293f43e-d5a5-4316-b8ee-9dfe0510dfb8.png)

**Comment by Suvanth-Erranki** [comment]
That happens when you do freecam.

**Comment by maitian352** [comment]
Very border. I did this to reduce lag because apparently it takes 11 seconds to run 1 fillrect to reset the canvas.
