### ISSUE TITLE
level 3 makes it sound like its obtainable. Just change it to "sp level"

### ISSUE THREAD

**Issue by definitely-nobody-is-here** [maitian352/Meadow-Guarder#242]
![image](https://user-images.githubusercontent.com/67865358/148593038-e367ebce-c895-49ff-91b0-82f49e7ec1df.png)

**Comment by maitian352** [comment]
How?

**Comment by Suvanth-Erranki** [comment]
I personally don't see anything wrong with this. Why is this an issue?
