### ISSUE TITLE
Building collisions and sizing is really stupid

### ISSUE THREAD

**Issue by definitely-nobody-is-here** [maitian352/Meadow-Guarder#242]
The walls on the town hall are three tiles tall, and you can't walk behind the building.
Is the back wall sloped?
The tiny house is only two blocks thick, so it is made entirely of wall
You literally can't walk behind any house properly, so everyone's houses have sloped back walls
All the houses are facing the same direction
ALL THE BUILDINGS IN THE WORLD ARE FACING IN THE SAME DIRECTION
ALL THE BACK WALLS ARE SLOPED
EACH BUILDING IS SO THIN SOME DONT EVEN HAVE SPACE TO FIT STUFF INSIDE

**Comment by definitely-nobody-is-here** [comment]
![image](https://user-images.githubusercontent.com/67865358/119503611-29fa7f00-bd39-11eb-9387-1181b912ed8b.png)
HOW AM I COLLIDING? IS IT HTE SLOPE? OR IS THE HOUSE ACTUALLY FLAT?

**Comment by maitian352** [comment]
The house is actually flat.

**Comment by maitian352** [comment]
It isn't that all the buildings are facing the same direction, it is that your point of view is always the same.

**Comment by maitian352** [comment]
So you would rather like gigantic houses?

**Comment by maitian352** [comment]
If I remove the collisions of where you say they should be removed, you would post an issue that you can see the name and health bar behind houses, and when I fix that you would say that the health bar is cut off by houses.
