### ISSUE TITLE
this door should be closed or you should be able to enter it

### ISSUE THREAD

**Issue by definitely-nobody-is-here** [maitian352/Meadow-Guarder#243]
![image](https://user-images.githubusercontent.com/67865358/119502131-9a080580-bd37-11eb-8d79-d47f51f7bc87.png)

**Comment by definitely-nobody-is-here** [comment]
![image](https://user-images.githubusercontent.com/67865358/119502115-95435180-bd37-11eb-957e-e579e22c3630.png)

**Comment by maitian352** [comment]
Some maps are not finished.

**Comment by maitian352** [comment]
the garage go brrrrrrrrrrrrrr
