### ISSUE TITLE
The weather glitched and became so dark!

### ISSUE THREAD

**Issue by Suvanth-Erranki** [maitian352/Meadow-Guarder#244]
![image](https://user-images.githubusercontent.com/76885647/148600309-4541e542-344e-4ce5-a663-bfb100b7c5b5.png)

I don't understand why this happened. Basically, I used `/weather snow` and then the weather changed to rain.

Normal rain:

![image](https://user-images.githubusercontent.com/76885647/148600439-84420416-e658-4a4e-bbfa-c799bccf3ee9.png)

**Comment by Suvanth-Erranki** [comment]
Invalid, sp did this.

**Comment by maitian352** [comment]
There are actually multiple levels of raining, light drizzle, rain, heavy rain, pouring rain, heavy pouring rain. I set the weather to heavy pouring rain using a command.
