### ISSUE TITLE
pillars and slopes dont mix and the building is made entirely of wall

### ISSUE THREAD

**Issue by definitely-nobody-is-here** [maitian352/Meadow-Guarder#244]
![image](https://user-images.githubusercontent.com/67865358/119502565-0daa1280-bd38-11eb-8dd7-518397403fad.png)

**Comment by maitian352** [comment]
How is the building made entirely of slope?

**Comment by definitely-nobody-is-here** [comment]
it's literally two tiles thick. So if the building were normal and each wall is 1 tile (as seen in other buildings) then the building would have a front wall and then immediately a back wall

**Comment by maitian352** [comment]
No, I meant the one in the picture.

**Comment by definitely-nobody-is-here** [comment]
oh
