### ISSUE TITLE
tell me how this works

### ISSUE THREAD

**Issue by definitely-nobody-is-here** [maitian352/Meadow-Guarder#245]
![image](https://user-images.githubusercontent.com/67865358/119503438-f9b2e080-bd38-11eb-92ea-88f1f7f5a3ff.png)

**Comment by definitely-nobody-is-here** [comment]
just render the items under the house already!

**Comment by definitely-nobody-is-here** [comment]
WHAT IS THIS
![image](https://user-images.githubusercontent.com/67865358/119504113-aab97b00-bd39-11eb-9123-edf78af8f516.png)
UPDATE THE SERVER

**Comment by maitian352** [comment]
If I render the items under the house then it will look like the item is cut off.
