### ISSUE TITLE
SUGGESTION: monsters dont despawn when nobody is on map

### ISSUE THREAD

**Issue by definitely-nobody-is-here** [maitian352/Meadow-Guarder#246]
instead of despawning monsters when nobody is on the map, the server should pause physics for those monsters. They do not move, have collisions, die, or attack. They are stored but not calculated. When a player enters the map physics will resume. Respawn timers will continue when the map is not active even though physics is paused. And monsters don't all spawn when a player enters. It's a lot more realistic than "oh a player entered the map time to spawn everything".

**Comment by definitely-nobody-is-here** [comment]
why no add

**Comment by maitian352** [comment]
Because this is a feature of the game.
