### ISSUE TITLE
You can't pick up items that drop in Seashell village

### ISSUE THREAD

**Issue by Suvanth-Erranki** [maitian352/Meadow-Guarder#249]
![image](https://user-images.githubusercontent.com/76885647/148658273-92417afc-dbc1-48fb-86a9-3d6d22964f97.png)

I couldn't pick up the copper coins.

**Comment by maitian352** [comment]
Works for me. Are you sure you had space in your inventory?

**Comment by Suvanth-Erranki** [comment]
Nevermind, I didn't have space in my inventory, but I found another bug.
