### ISSUE TITLE
When you die, your movements are still reported in the chat. However, this is bug because if you are not alive in the game, you can't REALLY move - its more like your ghost is moving.

### ISSUE THREAD

**Issue by Suvanth-Erranki** [maitian352/Meadow-Guarder#25]
In this photo: the player dtg1 died, but never respawned. his movements were still recorded though even though the player wasn't really alive and moving - only his "ghost" was.
![image](https://user-images.githubusercontent.com/63676047/97808167-52068180-1c33-11eb-8371-b29a32bd1072.png)

**Comment by maitian352** [comment]
I think this is asking for a new feature.

**Comment by Suvanth-Erranki** [comment]
What do you mean?

**Comment by maitian352** [comment]
I am going to fix this issue by making you unable to move if you die until you respawn.

**Comment by Suvanth-Erranki** [comment]
Ok. Great Idea!!!

**Comment by maitian352** [comment]
Fixed.
