### ISSUE TITLE
Monsters can enter noMonster territory in Seashell village.

### ISSUE THREAD

**Issue by Suvanth-Erranki** [maitian352/Meadow-Guarder#250]
![image](https://user-images.githubusercontent.com/76885647/148658471-3943638f-4579-4940-8128-e80790c4fb59.png)
![image](https://user-images.githubusercontent.com/76885647/148658543-ecda8639-3160-4370-890d-895d645d7394.png)

I can't use my weapon, even though the monster is really close to me. But the Radioactive Skeleton can deal damage to me. How do I kill it?

**Comment by maitian352** [comment]
This is actually a different bug where monsters can enter a village that is supposed to be noMonster. I believe its been fixed, however I did not update.
