### ISSUE TITLE
my kiol dies when i do anything

### ISSUE THREAD

**Issue by definitely-nobody-is-here** [maitian352/Meadow-Guarder#252]
![image](https://user-images.githubusercontent.com/67865358/120896735-c867c980-c5f0-11eb-9fd3-074284d9a268.png)

**Comment by maitian352** [comment]
You have a weapon from Boss Rush equipped or you have Unholy Trident equipped. These weapons inflict the death debuff, which the kiol is not immune to, so when you go into another map you hit your kiol and your kiol gets the debuff and it dies.
