### ISSUE TITLE
boss rush is too easy

### ISSUE THREAD

**Issue by definitely-nobody-is-here** [maitian352/Meadow-Guarder#253]
book of death is too good add more hard things

**Comment by definitely-nobody-is-here** [comment]
where is bosh rush level 2

**Comment by maitian352** [comment]
I am adding sp as a boss.

**Comment by maitian352** [comment]
Ok, I made boss rush harder.

**Comment by maitian352** [comment]
haha fire spirit go brrrrrrrrrrrrrrrrrrrrr
