### ISSUE TITLE
enchant books are too common and very badly made

### ISSUE THREAD

**Issue by definitely-nobody-is-here** [maitian352/Meadow-Guarder#254]
and they almost guarantee an upgrade

also update the wiki with enchant stats for all items like max enchant, which enchants, effects of enchants

**Comment by definitely-nobody-is-here** [comment]
also some are 0.05 and some are 3 and there are no labels so idk what is what pls add labels

and my illegal bow is underpowered

**Comment by definitely-nobody-is-here** [comment]
also the enchant books ignore dev kesy

**Comment by maitian352** [comment]
Having a dev key equipped makes your enchantment books useless, as dev keys reduce your luck to -1, preventing you from gaining any enchantments from enchantment books.

**Comment by definitely-nobody-is-here** [comment]
i still get enchant books and my inv is cluttered with books
