### ISSUE TITLE
An area of the map acts as a collision.

### ISSUE THREAD

**Issue by Suvanth-Erranki** [maitian352/Meadow-Guarder#255]
![image](https://user-images.githubusercontent.com/76885647/148659100-43cbe9a0-7646-49ed-8daf-3787165ab685.png)
![image](https://user-images.githubusercontent.com/76885647/148659115-b8b4411e-0e0c-4129-bc75-9bc1699440eb.png)

I can't move to the left, the map got messed up. No console errors.

**Comment by Suvanth-Erranki** [comment]
I basically can't move left anywhere to the left of that vertically, it's like a vertical wall.

**Comment by Suvanth-Erranki** [comment]
Also, the tree looks weird.

**Comment by maitian352** [comment]
WOW, i exported the new map in the middle of it. LOL

**Comment by Suvanth-Erranki** [comment]
> WOW, i exported the new map in the middle of it. LOL

LOL

**Comment by Suvanth-Erranki** [comment]
These are the kind of updates where releasing it on Beta instead of normal version for a day or two to find bugs is useful.

**Comment by definitely-nobody-is-here** [comment]
More important question: why is the rain red

**Comment by maitian352** [comment]
No, I was going to fix a critical bug and did not know I exported.
