### ISSUE TITLE
Ad - ad

### ISSUE THREAD

**Issue by definitely-nobody-is-here** [maitian352/Meadow-Guarder#257]
here is ad
`<embed src="https://meadowguarder.herokuapp.com" width="100%" height="200px">`

ok put ad

**Comment by definitely-nobody-is-here** [comment]
![image](https://user-images.githubusercontent.com/67865358/120901734-a0855f80-c60a-11eb-87ab-a62a7c0cc80d.png)

**Comment by maitian352** [comment]
Ads cannot contain embeds.
