### ISSUE TITLE
Enchant books are bad

### ISSUE THREAD

**Issue by definitely-nobody-is-here** [maitian352/Meadow-Guarder#259]
There is no label for power (so 0.05 and 3 look the same)
you can attain them with a dev key
when you try to enchant something that cant be enchanted it closes your inventory instead of reopening it
there is nothing to tell you if an enchant is maxed out or what enchants you can possibly add

**Comment by maitian352** [comment]
Fixed.

**Comment by maitian352** [comment]
wowowow new enchanting sysetsm
