### ISSUE TITLE
Player can get confused where their character is if they accidentally move to the wrong position - the top left corner of the map.

### ISSUE THREAD

**Issue by Suvanth-Erranki** [maitian352/Meadow-Guarder#26]
Can you find where the player is? While I know that the player is in the corner, it can get confusing if the player goes there because he or she might not remember him going there and could get confused about where he is. This is more like a recommendation rather than a bug though.
![image](https://user-images.githubusercontent.com/63676047/97808482-1c629800-1c35-11eb-94ee-95cf9fce181e.png)

**Comment by maitian352** [comment]
Fixed. Now there are always some blocker in the top left corner.
