### ISSUE TITLE
Add water books back

### ISSUE THREAD

**Issue by definitely-nobody-is-here** [maitian352/Meadow-Guarder#260]
i like them

**Comment by maitian352** [comment]
Frost book, which is basically water book, has been added.

**Comment by definitely-nobody-is-here** [comment]
yay

**Comment by definitely-nobody-is-here** [comment]
does it bounce. I want something that bounces.

**Comment by maitian352** [comment]
It does bounce. Frost book also freezes enemies for 6 seconds, and has a 50% drop chance from Possessed Spirit.
