### ISSUE TITLE
New idea for PVP system.

### ISSUE THREAD

**Issue by Suvanth-Erranki** [maitian352/Meadow-Guarder#267]
I have a really great idea for PVP. Here is my idea:

Players can create their own PVP rooms with custom rules and can also join other PVP rooms that are open, The rules of the PVP room can be customized by the owner. Matches in PVP arenas can include clans (teams) that fight each other to victory. 

PVP rooms:

PVP rooms are different versions of the PVP arena which can contain different players.
The owner (creator) can choose when the PVP room should be deleted (after clan matches end, after the owner leaves the room, after everyone leaves the room, after the owner logs off, after a specific timer, or manual deletion by the owner). 
The owner can choose between whether it is a solo match between all participants (everyone can kill everyone) or a match between clans (teams) (you can only kill the other team). 
The owner can specify the maximum number of players to be in the room.
The owner can specify the amount of teams the room will hold or choose unlimited number of clans. 
The owner can ban/block certain clans from joining the room.
The owners can make rooms private that require a password.
The owner can choose whether players who die during battles can rejoin the fight or cannot.

Clan system:

Clans can be created by anyone, as long as the user has been playing for a specified time requirement (for example, 1 month or something), to prevent people from killing a clan they created.
The clan owner can specify the requirements to join.
For example, the clan could specify that players must have frozen breath, shield of life, and blade of death to join (this is just an example).
Clan owners can specify if people who are part of another clan cannot join.
The clan owner can make the clan private join if they want.
The clan owner can only delete the clan if there are fewer than 3 (imo) people in it.
There is a limit for the amount of people in a clan (idk how much it should be, I think that 6 should be the limit imo).
Players can create their own clan and specify if there are any requirements to join. 
If players are good enough to be accepted, they can join strong clans. 

Clan leaderboard:

Clans win a match based on the rules the owner states (a clan kills all the other members of the other clan (if no joining the battle after death option is selected by the owner) or if a clan gets the most kills against another clan in under the time limit)
If a clan wins against another clan, that clan will get more points. 
If a clan wins against another clan, it will gain fewer points if that clan isn't that good and doesn't have much points. If that clan that lost has lots of points, the winning clan will gain more points.
If a clan loses against another clan, it loses more points if that clan has fewer points. It loses less points if the clan has lots of points or more points than it.
The clan leaderboard will show which clans have the highest points and are the best in PVP.

---------------------------------------------------------------------------------------------------------------------------------------------------

Feel free to add any ideas you may have. As a sidenote, creating PVP rooms, clans, and specifying the requirements for both should open up a new `div`. Also, there should be a `div` for Clan leaderboard. Additionally, I'm not sure about point values and how much you should receive/lose depending on wins/losses against teams.

**Comment by Suvanth-Erranki** [comment]
![image](https://user-images.githubusercontent.com/76885647/148702754-38d3d0b0-e6dd-4e2d-91e7-553758139984.png)

**Comment by definitely-nobody-is-here** [comment]
finally a high-effort suggestion in a garuder game

**Comment by Suvanth-Erranki** [comment]
> finally a high-effort suggestion in a garuder game

Should I say thank you?

**Comment by Tianmu695** [comment]
Really Good Idea =D
