### ISSUE TITLE
Cross site scripting/styling and SQL injection vulnerability due to no Content Security Policy. This can lead to hackers stealing player's passwords, hacking the game, etc.

### ISSUE THREAD

**Issue by Suvanth-Erranki** [maitian352/Meadow-Guarder#27]
Hackers can inject malicious scripts from their website to hack another website. Content Security Policy (CSP):  helps fight these hackers and blocks their malacious scripts. Content Security Policy can block scripts from other website or even the client side scripts because those could be malicious. THIS IS ABSOLUETLY IMPORTANT - HACKERS COULD HACK YOUR SERVER AND STEAL INFORMATION. Read more on: [https://developer.mozilla.org/en-US/docs/Web/HTTP/CSP](url) and test your CSP at: [https://csp-evaluator.withgoogle.com/](url) to see if it is a strong CSP. IN FACT - HACKERS COULD STEAL THE PASSWORDS OF USERS AND HACK THEIR ACCOUNTS!!!!!!!!! Add CSP right now - this is priority. I know your website game doesn't have CSP because: CSP is included under the head tag and your game doesn't have it in the image below:
![image](https://user-images.githubusercontent.com/63676047/97808778-d1e21b00-1c36-11eb-9733-7364dca132df.png)

**Comment by Suvanth-Erranki** [comment]
All you need to do to fix this issue is to add this under your head tag in index.html:

<meta http-equiv="Content-Security-Policy" content="">

In the quotes after content, add default-src 'self'; script-src 'WHATEVER <script> srcs you have'; object-src 'WHATEVER <object>, <embed>, and <applet> srcs you have'

**Comment by maitian352** [comment]
What is the worst hackers can do?

**Comment by Suvanth-Erranki** [comment]
View the MDN article I sent you. Hackers could hack player's accounts,
hack the game and delete it, they could do practically anything
through cross site scripting.

**Comment by maitian352** [comment]
Delete it? So they can hack into my computer and delete the file and also hack into github and delete it and also hack into my brain and delete any signs of it?

**Comment by Suvanth-Erranki** [comment]
No, they can hack the website and everything in it.

**Comment by maitian352** [comment]
What about the server?

**Comment by Suvanth-Erranki** [comment]
Yes they can hack the server

**Comment by maitian352** [comment]
Fixed.

**Comment by maitian352** [comment]
The SQL Injection has been fixed by sanitizing the inputs. Adding a Content Security Policy only protects the client, and you can still do SQL Injection with a CSP.
