### ISSUE TITLE
frost book gets stuck bouncing on the edge of the wall

### ISSUE THREAD

**Issue by definitely-nobody-is-here** [maitian352/Meadow-Guarder#270]
![image](https://user-images.githubusercontent.com/67865358/121778372-a1674580-cb64-11eb-88f7-fb78be50daf0.png)

**Comment by definitely-nobody-is-here** [comment]
![image](https://user-images.githubusercontent.com/67865358/121778469-01f68280-cb65-11eb-80ad-912139a88545.png)

**Comment by maitian352** [comment]
And this is why Frost Book should be removed.

**Comment by maitian352** [comment]
Fixed.
