### ISSUE TITLE
texture is a swatzika

### ISSUE THREAD

**Issue by definitely-nobody-is-here** [maitian352/Meadow-Guarder#271]
![image](https://user-images.githubusercontent.com/67865358/121778409-c2c83180-cb64-11eb-9030-bf033849efb2.png)

**Comment by maitian352** [comment]
Whirlwind32disbelief.mp3

**Comment by maitian352** [comment]
**Whirlwind has awoken!**
definitely-nobody-is-here got destroyed by Whirlwind.
**Whirlwind has killed every player!**

**Comment by definitely-nobody-is-here** [comment]
lol
