### ISSUE TITLE
Enhancement: improve manually dropping items - Items can sometimes drop in locations you can't see them.

### ISSUE THREAD

**Issue by Suvanth-Erranki** [maitian352/Meadow-Guarder#271]
I manually dropped Red Fedora from my inventory for a second and this is where it was:

![image](https://user-images.githubusercontent.com/76885647/148840705-25a748ea-e987-4288-9c2d-ffe59c640fc3.png)

Please automatically adjust manual drops which would end up in unseeable areas to make them drop in viewable places.

**Comment by maitian352** [comment]
But what if the item can only drop in unseeable locations?

**Comment by Suvanth-Erranki** [comment]
![image](https://user-images.githubusercontent.com/76885647/148844785-72296bbc-75f9-4252-a63b-3ba24313d6ba.png)
