### ISSUE TITLE
Changing your inventory won't update crafting immediately.

### ISSUE THREAD

**Issue by Suvanth-Erranki** [maitian352/Meadow-Guarder#272]
I removed all of my thick leather, but it still showed that I could craft items that required thick leather.
![image](https://user-images.githubusercontent.com/76885647/148841338-a2c8c603-11e4-44bc-8c27-2cb8cf5a941f.png)

**Comment by maitian352** [comment]
It does!

**Comment by Suvanth-Erranki** [comment]
> It does!

Then why didn't it update for me?

**Comment by maitian352** [comment]
Didn't update the server. Also I actually found this is a real bug and fixed it.

**Comment by Suvanth-Erranki** [comment]
> Didn't update the server. Also I actually found this is a real bug and fixed it.

What was the real bug?

**Comment by Suvanth-Erranki** [comment]
![image](https://user-images.githubusercontent.com/76885647/149856412-c66e8639-0685-4b53-a43e-5e7ea1936d45.png)
