### ISSUE TITLE
Declining the trade after accepting breaks it

### ISSUE THREAD

**Issue by definitely-nobody-is-here** [maitian352/Meadow-Guarder#274]
![image](https://user-images.githubusercontent.com/67865358/148851553-a1d56105-7c3c-456c-a767-7b6957c468be.png)

**Comment by maitian352** [comment]
Lag?

**Comment by maitian352** [comment]
Works for me.

**Comment by definitely-nobody-is-here** [comment]
Not lag it was like this for 10 seconds until suvanth did something

**Comment by definitely-nobody-is-here** [comment]
You have to both accept, then one declines.

**Comment by definitely-nobody-is-here** [comment]
reopen reopen reopen reopen reopen reopen reopen reopen reopen reopen reopen reopen reopen reopen reopen reopen reopen reopen reopen reopen reopen reopen reopen reopen reopen

**Comment by Suvanth-Erranki** [comment]
Didn't happen to me ever before.
