### ISSUE TITLE
Monsters shoot projectiles at you without facing you - visual bug

### ISSUE THREAD

**Issue by Suvanth-Erranki** [maitian352/Meadow-Guarder#275]
![image](https://user-images.githubusercontent.com/76885647/148854349-7f4c5526-160d-44ad-8a43-99f9a5fd1922.png)

This is a visual bug, in my opinion, because why would they be facing a different direction yet somehow accurately pinpointing your location and shooting projectiles at you. It's not like they have a screen where they seen everything 2D. They are supposed to have a 3D field of view and can't see you, and it doesn't make sense that they can accurately shoot projectiles.

**Comment by Suvanth-Erranki** [comment]
Still happens.
![image](https://user-images.githubusercontent.com/76885647/148863422-7f6cedc3-5ecf-4039-9185-fd7f2758d0d2.png)

**Comment by maitian352** [comment]
The monster is wiggleing, so this makes the code think that it is moving and makes the monster face in that direction.
