### ISSUE TITLE
Monsters don't always attack you, even if you are close to them

### ISSUE THREAD

**Issue by definitely-nobody-is-here** [maitian352/Meadow-Guarder#281]
![image](https://user-images.githubusercontent.com/67865358/149056582-cd927710-36f4-436a-98a9-8c0029bc4271.png)
it was up here where the items were and i walked right up to its face but it still didn't attack

**Comment by Suvanth-Erranki** [comment]
We need more details, it's hard to figure out where exactly you were and how far you were positioned from the monster.

**Comment by Suvanth-Erranki** [comment]
I guess the issue you are trying to say is that monsters don't attack you even if you are near them. This goes along with #230, monster AI being improved.

**Comment by definitely-nobody-is-here** [comment]
I was about in front of the monster

**Comment by definitely-nobody-is-here** [comment]
Also maitian keeps posting bugs like this on mountain gaurder and he never elaborates enough and I have to go find it myself.

**Comment by Suvanth-Erranki** [comment]
![image](https://user-images.githubusercontent.com/76885647/149828382-3752f0fb-506b-403e-9ea1-11c45c315091.png)


It didn't even attack me with flames.

**Comment by Suvanth-Erranki** [comment]
![image](https://user-images.githubusercontent.com/76885647/150407809-71ea8490-4145-4054-b110-65bacb77ad93.png)
