### ISSUE TITLE
Chat bug: The game froze for a few seconds, then randomly disconnected me.

### ISSUE THREAD

**Issue by Suvanth-Erranki** [maitian352/Meadow-Guarder#284]
![image](https://user-images.githubusercontent.com/76885647/149207703-085df503-8679-4693-a149-eab3858242a8.png)

**Comment by definitely-nobody-is-here** [comment]
how come when i post it it gets closed and mark as invalid

**Comment by maitian352** [comment]
> how come when i post it it gets closed and mark as invalid

Which issue?
