### ISSUE TITLE
pressing login button too fast leaves you at a blank screen

### ISSUE THREAD

**Issue by definitely-nobody-is-here** [maitian352/Meadow-Guarder#289]
![image](https://user-images.githubusercontent.com/67865358/122921172-2f46eb80-d330-11eb-9943-79ca68265ba5.png)

**Comment by maitian352** [comment]
This doesn't happen to me

**Comment by maitian352** [comment]
This is the case of an Invalid Password.

**Comment by maitian352** [comment]
Fixed.
