### ISSUE TITLE
My account doesn't exist but I still had my items and could sign in

### ISSUE THREAD

**Issue by definitely-nobody-is-here** [maitian352/Meadow-Guarder#291]
![image](https://user-images.githubusercontent.com/67865358/149567287-fcdc88f0-bc44-4acf-9000-f7b7acbe8788.png)
![image](https://user-images.githubusercontent.com/67865358/149567306-50b5851a-bad1-48af-8902-219810a46179.png)

**Comment by Suvanth-Erranki** [comment]
what... how did this happen?
