### ISSUE TITLE
Server randomly disconnected me when I was fighting monsters

### ISSUE THREAD

**Issue by Suvanth-Erranki** [maitian352/Meadow-Guarder#292]
My game froze and then I got disconnected a minute later.
![image](https://user-images.githubusercontent.com/76885647/149590283-d0ed1f13-2604-45af-9b39-afbb3804efa2.png)

**Comment by maitian352** [comment]
Not enough information, maybe you actually got disconnected.

**Comment by Suvanth-Erranki** [comment]
But why did the game freeze for an entire minute - that wasn't supposed to happen right?

**Comment by Suvanth-Erranki** [comment]
The screenshot is of the game frozen.

**Comment by maitian352** [comment]
Lost wifi. You got wifi back, and all the socket emits got received in the same tick, causing the server to disconnect you for socket emit spam.

**Comment by Suvanth-Erranki** [comment]
> Lost wifi. You got wifi back, and all the socket emits got received in the same tick, causing the server to disconnect you for socket emit spam.

My wifi is really strong, and it was working, because i had this tab open and was able to refresh it to make sure it weas working.

**Comment by Suvanth-Erranki** [comment]
My router is literally in the same room and my connection goes through xFinity.

**Comment by maitian352** [comment]
You lost wifi for 1 minute.

**Comment by maitian352** [comment]
I really don't know why this is happening unless your wifi is bad, but because you posted so many issues I'm just going to disable the socket emit spam detection.

**Comment by maitian352** [comment]
This has literally never happened to me ONCE.

**Comment by Suvanth-Erranki** [comment]
Happened to me again.

![image](https://user-images.githubusercontent.com/76885647/149817398-f0e38596-8fd5-4ca1-92b1-adc6678a9332.png)

**Comment by Suvanth-Erranki** [comment]
Console:

![image](https://user-images.githubusercontent.com/76885647/149817456-77403e80-da08-4dd4-8f81-fcb321720915.png)

**Comment by Suvanth-Erranki** [comment]
![image](https://user-images.githubusercontent.com/76885647/149999246-ba5d98d5-b8fd-4bd8-b53a-595211606656.png)

It happened again today. Really irritating.

**Comment by Suvanth-Erranki** [comment]
Oh wait the server crashed.
