### ISSUE TITLE
left map and um

### ISSUE THREAD

**Issue by definitely-nobody-is-here** [maitian352/Meadow-Guarder#294]
![image](https://user-images.githubusercontent.com/67865358/123355104-f62a9900-d532-11eb-9b98-b8e44d8719a8.png)

**Comment by maitian352** [comment]
How do you reproduce this bug?

**Comment by definitely-nobody-is-here** [comment]
you leave a map right as you die

**Comment by maitian352** [comment]
But then why do you have full health?

**Comment by definitely-nobody-is-here** [comment]
idk
