### ISSUE TITLE
100% shield power

### ISSUE THREAD

**Issue by definitely-nobody-is-here** [maitian352/Meadow-Guarder#296]
![image](https://user-images.githubusercontent.com/67865358/149665764-0723439c-fe99-4cfb-93d5-2401e06d6e2f.png)

**Comment by Suvanth-Erranki** [comment]
There are shielding buffs right now?

**Comment by Suvanth-Erranki** [comment]
Plus projectiles can just come in a different angle the shield isn't facing and kill you. So this is fine.

**Comment by Suvanth-Erranki** [comment]
![image](https://user-images.githubusercontent.com/76885647/149667239-e44cfe29-deb0-403a-9395-b5991bca4819.png)

**Comment by Suvanth-Erranki** [comment]
Didn't mean to add that label.
