### ISSUE TITLE
4:3 aspect ratio doesn't work

### ISSUE THREAD

**Issue by definitely-nobody-is-here** [maitian352/Meadow-Guarder#298]
![image](https://user-images.githubusercontent.com/67865358/149668132-48834119-8572-4de4-8ab5-158eb89d4741.png)
![image](https://user-images.githubusercontent.com/67865358/149668162-849ab410-81c9-4758-a006-8edef0924f98.png)

**Comment by Suvanth-Erranki** [comment]
Why is this an enhancement? Pretty sure its a bug.
