### ISSUE TITLE
Bullet goes under roof but over house.

### ISSUE THREAD

**Issue by maitian352** [maitian352/Meadow-Guarder#3]

**Comment by maitian352** [comment]
Which house?

**Comment by maitian352** [comment]
The first one with the iron doors.

**Comment by maitian352** [comment]
This is a duplicate of [this](https://github.com/maitian352/Meadow-Guarder/issues/3), because the player and the bullet are drawn in the same thing.

**Comment by maitian352** [comment]
This has been fixed in 008f3a.

**Comment by definitely-nobody-is-here** [comment]
when lonely
