### ISSUE TITLE
Dashing is broken.

### ISSUE THREAD

**Issue by Suvanth-Erranki** [maitian352/Meadow-Guarder#301]
When Karate Skeletons dash at you, they jsut dash to your postion and ignore pathfinding. This allows it to dash into collisions.

**Comment by Suvanth-Erranki** [comment]
![image](https://user-images.githubusercontent.com/76885647/149670514-3f61112b-5335-49a0-8b67-6597867dd55f.png)
![image](https://user-images.githubusercontent.com/76885647/149670530-0aaf0103-33d1-4144-a2d2-c2ca38f53fc5.png)

The Karate Skeleton dashed at me and killed me, but it got itself stuck to the tree collision in the process. LOL

**Comment by definitely-nobody-is-here** [comment]
it's not stuck, it's just confused

**Comment by Suvanth-Erranki** [comment]
It's stuck, log on if you don't believe me.

**Comment by Suvanth-Erranki** [comment]
I made it a seperate issue, because in #302 the Karate Skeleton can't escape even if I am not around.
