### ISSUE TITLE
MGHC is broken.

### ISSUE THREAD

**Issue by Suvanth-Erranki** [maitian352/Meadow-Guarder#303]
![image](https://user-images.githubusercontent.com/76885647/149674183-063e0678-fef0-4171-8ae7-f4cb3fc68ca0.png)

**Comment by maitian352** [comment]
I don't really want to continue updating MGHC, maybe in the future.

**Comment by Suvanth-Erranki** [comment]
This issue isn't really invalid, just a wontfix.
