### ISSUE TITLE
Meadow Guarder Also Has Application Errors!!!

### ISSUE THREAD

**Issue by Tianmu695** [maitian352/Meadow-Guarder#305]
![image](https://user-images.githubusercontent.com/68877583/149817709-261f80ab-8c90-493c-946a-d21bff15fb21.png)
My Game Froze when im fighting ten eyed one

**Comment by Suvanth-Erranki** [comment]
![image](https://user-images.githubusercontent.com/76885647/149820287-a616a2de-a71f-4a1b-9be1-67daf9bc6e73.png)

**Comment by Suvanth-Erranki** [comment]
Why won't you fix?

**Comment by maitian352** [comment]
Idk which process and i don't think it is fixable.

**Comment by Suvanth-Erranki** [comment]
![image](https://user-images.githubusercontent.com/76885647/149999388-a231bda0-e10b-4ed0-8cc1-d7ee6d459eea.png)

IT HAPPENED AGAIN :(

**Comment by Suvanth-Erranki** [comment]
Server crashed....

**Comment by maitian352** [comment]
Unfixable.

**Comment by rod0624** [comment]
I thought it was normale thinking you were updating game
