### ISSUE TITLE
Near the corners of the map river, even though you should be able to move left, you can't making it harder for you to move at the edge of the map river.

### ISSUE THREAD

**Issue by Suvanth-Erranki** [maitian352/Meadow-Guarder#31]
Even though you should be able to, I can't move left here:
![image](https://user-images.githubusercontent.com/63676047/97815564-e3d6b480-1c5c-11eb-9b60-f3aee9eca380.png)

I can't move here left here either:

![image](https://user-images.githubusercontent.com/63676047/97815603-2ef0c780-1c5d-11eb-8015-985fcd842e58.png)

**Comment by maitian352** [comment]
You can't move left because the collision is a bit bigger than the water.

**Comment by Suvanth-Erranki** [comment]
Yeah, this isn't a bug, just try to fix it.

**Comment by Suvanth-Erranki** [comment]
I'll combine this with the other issue.
