### ISSUE TITLE
Dragging an item during cooldown looks weird.

### ISSUE THREAD

**Issue by Suvanth-Erranki** [maitian352/Meadow-Guarder#310]
![image](https://user-images.githubusercontent.com/76885647/149834501-6b542341-53cf-4a3e-8491-95361b0d9e46.png)

**Comment by maitian352** [comment]
What am i supposted to make it look like???

**Comment by Suvanth-Erranki** [comment]
Don't show the red stuff when dragging the item, but show it for all the items that are still in their slots.
