### ISSUE TITLE
Increase Ten Eyed One's HP regen a little more.

### ISSUE THREAD

**Issue by Suvanth-Erranki** [maitian352/Meadow-Guarder#311]
I acknowledge that Ten Eyed One is difficult. However, I feel like he regenerates health so slowly for a monster of his caliber. Imo, he should regen 20k or 25k hp per second instead of 10k.

**Comment by maitian352** [comment]
He doesn't have enough food for that.

**Comment by maitian352** [comment]
Also, it would make players with like staff of life able to defeat him.

**Comment by Suvanth-Erranki** [comment]
> He doesn't have enough food for that.

15k? Don't tell me he starves - he definitely feasts on Karate Skeletons.

**Comment by Suvanth-Erranki** [comment]
> Also, it would make players with like staff of life able to defeat him.

Wayyy to difficult. Staff of Life flames move way slower than me with my current setup. They don't even affect him - 123 damage.

**Comment by Suvanth-Erranki** [comment]
Actually, nvm
