### ISSUE TITLE
sp Boss Battle!

### ISSUE THREAD

**Issue by maitian352** [maitian352/Meadow-Guarder#313]
Sneak Peak

![image](https://user-images.githubusercontent.com/68207888/123649900-1e96e980-d7f8-11eb-8a02-d2cb32aad27d.png)

**Comment by definitely-nobody-is-here** [comment]
sp is capitalized!

**Comment by maitian352** [comment]
![image](https://user-images.githubusercontent.com/68207888/123881069-f3082200-d911-11eb-9139-37fd705b7ae7.png)

**Comment by maitian352** [comment]
0.3.0 is out!
