### ISSUE TITLE
Server keeps crashing because a process fails to exit.

### ISSUE THREAD

**Issue by definitely-nobody-is-here** [maitian352/Meadow-Guarder#317]
![image](https://user-images.githubusercontent.com/67865358/150443519-bdbb00e1-b03d-4087-8beb-01503e85d6f3.png)
thsi si a crash report

**Comment by rod0624** [comment]
that is not fixed i got it

**Comment by rod0624** [comment]
![Screenshot 2022-01-21 8 00 47 AM](https://user-images.githubusercontent.com/94392796/150549333-00c033b1-0c04-49f4-8343-9be934cc2135.png)

**Comment by rod0624** [comment]
it keeps happening when we are about to kill teo :/ 
https://padlet.com/lucifersbestwork/8skvq7h3vw37ey4v

**Comment by rod0624** [comment]
yep it keeps making me crash when we are trying to kill teo

**Comment by rod0624** [comment]
wth is this
![Screenshot 2022-01-21 8 50 54 AM](https://user-images.githubusercontent.com/94392796/150557542-99b424a5-a809-4a70-8ac0-3d4734b8cb3c.png)

**Comment by maitian352** [comment]
It's unfixable because of a heroku error. I removed the SIGTERM and SIGINT event handlers so maybe it will be fixed.

**Comment by maitian352** [comment]
![image](https://user-images.githubusercontent.com/68207888/150575446-27919e4e-6a71-4ae4-b64e-b705c87f9c9b.png)

**Comment by Suvanth-Erranki** [comment]
![image](https://user-images.githubusercontent.com/76885647/150596345-f985d84e-51ba-480c-a587-4695d0fe75a5.png)

Nope.

**Comment by rod0624** [comment]
> It's unfixable because of a heroku error. I removed the SIGTERM and SIGINT event handlers so maybe it will be fixed.

oh ok

**Comment by rod0624** [comment]
oh

**Comment by maitian352** [comment]
Which just got fixed.
