### ISSUE TITLE
The server disconnects you when you are about to kill a boss monster and when you log back on, the boss is at full health

### ISSUE THREAD

**Issue by Suvanth-Erranki** [maitian352/Meadow-Guarder#318]
![image](https://user-images.githubusercontent.com/76885647/150687192-7bd31eb5-2c37-410e-9758-3b35932af1c4.png)

**Comment by maitian352** [comment]
Logs say it was just a server restart.
![image](https://user-images.githubusercontent.com/68207888/150687694-8ded7cd1-988c-4806-9459-50f9d4bbdb18.png)
