### ISSUE TITLE
my screen froze

### ISSUE THREAD

**Issue by definitely-nobody-is-here** [maitian352/Meadow-Guarder#319]
![image](https://user-images.githubusercontent.com/67865358/150698459-6b792f64-febf-4605-9e66-d48b151d2a71.png)

**Comment by Suvanth-Erranki** [comment]
What was the error? We need more details. It may have been MGHC.

**Comment by Suvanth-Erranki** [comment]
This hasn't happened to me recently.

**Comment by Suvanth-Erranki** [comment]
How do we reproduce this issue @definitely-nobody-is-here ?
