### ISSUE TITLE
You can lure monsters from one place to another - even into the map village and the starter house.

### ISSUE THREAD

**Issue by Suvanth-Erranki** [maitian352/Meadow-Guarder#32]
I wasn't able to get a screenshot in time, but here is an image of me doing it - I died, but if I had lived, the monster would have gone to the map river and disappeared.
![image](https://user-images.githubusercontent.com/63676047/97815701-f998a980-1c5d-11eb-80b9-83b5e66bce2f.png)

**Comment by maitian352** [comment]
The monster disappears because there are no players in that map so the server deletes the monster.

**Comment by Suvanth-Erranki** [comment]
I know - that is a bug.

**Comment by maitian352** [comment]
Fixed.
