### ISSUE TITLE
ok idk if this a bug but i really hope my account did not get ternimated by accdent now

### ISSUE THREAD

**Issue by rod0624** [maitian352/Meadow-Guarder#324]
![Screenshot 2022-01-27 1 26 35 PM](https://user-images.githubusercontent.com/94392796/151438263-ba8b2df3-f297-48ae-a0f8-8981adff64a3.png)

**Comment by rod0624** [comment]
ok bruh now it changed to this
![Screenshot 2022-01-27 1 28 09 PM](https://user-images.githubusercontent.com/94392796/151438384-b1849d6d-8fbf-4c1a-b3bf-98a4c458bdaf.png)

**Comment by rod0624** [comment]
even this account bruh did you guys IP ban? 
![Screenshot 2022-01-27 1 28 44 PM](https://user-images.githubusercontent.com/94392796/151438492-3e87eaa0-2e5d-476a-809c-553473eb8db4.png)

**Comment by maitian352** [comment]
Database crashed for some reason.

**Comment by rod0624** [comment]
oh

**Comment by rod0624** [comment]
no wonder

**Comment by rod0624** [comment]
i thought it was a ip ban tbh

**Comment by rod0624** [comment]
it happened agian
![Screenshot 2022-01-28 9 49 57 AM](https://user-images.githubusercontent.com/94392796/151587944-36b69aad-4adb-4fb3-b7ff-4dbe9698c4db.png)

**Comment by rod0624** [comment]
ye it changed to currently suspended

**Comment by rod0624** [comment]
also before when this happened i see the code you changed but it still happenes
![Screenshot 2022-01-28 11 05 46 AM](https://user-images.githubusercontent.com/94392796/151599067-50291d77-0212-46b6-ba93-54f48d8b06fe.png)

**Comment by rod0624** [comment]
oh nvm there was more to that
