### ISSUE TITLE
You need to add a private policy.

### ISSUE THREAD

**Issue by Suvanth-Erranki** [maitian352/Meadow-Guarder#325]
The private policy should specify what data you collect, what cookies you place, and how you use that data.

You collect the IP address of an account after it logs it and also places cookies on the user's browser. Specify the exact data you collect and how you use it.

**Comment by maitian352** [comment]
Meadow Guarder actually doesnt collect the Ip address, it just checks the ip address against a list of ip addresses that are banned.
