### ISSUE TITLE
i am very sorry to say but  most of the players at my school will not be able to play anymore during school hours (down below are the ones i know currently that play this game that wont be able to anymore)

### ISSUE THREAD

**Issue by ashyboiii** [maitian352/Meadow-Guarder#326]
Sullyboi2
Itsferytime
Samuelmcleay
Darthplo
Ashyboi2
ZEAV2

**Comment by ashyboiii** [comment]
However i might know a way to fix this 
You could do this by switching from heroku but that would mean alot of work but it really doesnt matter that much its just an idea

**Comment by maitian352** [comment]
> However i might know a way to fix this You could do this by switching from heroku but that would mean alot of work but it really doesnt matter that much its just an idea

They only blocked meadowguarder.herokuapp.com, which means if I want to I can just rename the app to meadowguarderthatworks.herokuapp.com.

**Comment by ashyboiii** [comment]
actually they blocked herokuapp itself

**Comment by ashyboiii** [comment]
actually they blocked herokuapp itslef

**Comment by maitian352** [comment]
Does [https://meadowguarderbeta.herokuapp.com](https://meadowguarderbeta.herokuapp.com) work?

**Comment by ashyboiii** [comment]
youre  right itll work
