### ISSUE TITLE
Dropping one item from a stack causes the item icon to shrink

### ISSUE THREAD

**Issue by definitely-nobody-is-here** [maitian352/Meadow-Guarder#327]
If you hold multiple items out of your inventory and right click to drop one, the stack shrinks. It only does it for the first item and does not shrink further afterwards.
![image](https://user-images.githubusercontent.com/67865358/152664310-8acb8e9f-3620-458f-9d76-3c63fae54a8f.png)
![image](https://user-images.githubusercontent.com/67865358/152664311-f9f2ef51-f214-487b-9289-30a3ae070c75.png)

**Comment by maitian352** [comment]
Imagine if it just keeps on shrinking LOL.
