### ISSUE TITLE
The game doesn't render and the entire screen is black because CSP doesn't allow 'unsafe-eval'

### ISSUE THREAD

**Issue by Suvanth-Erranki** [maitian352/Meadow-Guarder#33]
This is fixable jsut by allowing the parameter in the CSP for the script-src: 'unsafe-eval'
![image](https://user-images.githubusercontent.com/63676047/97820413-0af0ae80-1c7c-11eb-98f0-568b95b994c0.png)

**Comment by maitian352** [comment]
Fixed.
