### ISSUE TITLE
NPC Sean's shop doesn't work/isn't programmed

### ISSUE THREAD

**Issue by Suvanth-Erranki** [maitian352/Meadow-Guarder#337]
![image](https://user-images.githubusercontent.com/76885647/159184327-529403cb-9a39-496a-a239-dc251b0f42e6.png)

Clicking "open shop" does nothing.

**Comment by maitian352** [comment]
![image](https://user-images.githubusercontent.com/68207888/159184414-21907064-8454-4d06-ab0d-fce5947546c5.png)
way more important bug

**Comment by Suvanth-Erranki** [comment]
True, but why is this closed?

**Comment by maitian352** [comment]
Fixed. duh
