### ISSUE TITLE
TIP: Optimize projectile collisons with binary heaps

### ISSUE THREAD

**Issue by definitely-nobody-is-here** [maitian352/Meadow-Guarder#343]
Instead of using lists, use a binary heap. It's much faster and will make things much less laggy.

[Check out this article](https://blog.bitsrc.io/implementing-heaps-in-javascript)

**Comment by maitian352** [comment]
the site is a 404 error

**Comment by definitely-nobody-is-here** [comment]
u died

**Comment by definitely-nobody-is-here** [comment]
console.log('nopath')
****
