### ISSUE TITLE
AAAAAAAAAAAAA NO COLLISIONS HERE!!!

### ISSUE THREAD

**Issue by definitely-nobody-is-here** [maitian352/Meadow-Guarder#347]
![image](https://user-images.githubusercontent.com/67865358/125311022-1616d680-e301-11eb-8e09-c2a430e96a66.png)
![image](https://user-images.githubusercontent.com/67865358/125311090-26c74c80-e301-11eb-85f3-6a4d2fb2896b.png)
![image](https://user-images.githubusercontent.com/67865358/125311110-2af36a00-e301-11eb-9755-8f5f93ec6b89.png)
![image](https://user-images.githubusercontent.com/67865358/125311205-3a72b300-e301-11eb-8ced-5e5a46d1b6c2.png)

**Comment by maitian352** [comment]
Fixed.
