### ISSUE TITLE
There is a gap in the wall during red bird quest

### ISSUE THREAD

**Issue by definitely-nobody-is-here** [maitian352/Meadow-Guarder#349]
![image](https://user-images.githubusercontent.com/67865358/125471774-4d941826-aef0-4369-b87a-6fe0d8fd7e97.png)
its soft locked

**Comment by definitely-nobody-is-here** [comment]
![image](https://user-images.githubusercontent.com/67865358/125471956-06897b3b-c83e-4bf0-8aae-fe2bcc1f5329.png)

**Comment by maitian352** [comment]
oof
i somehow made a typo

fixed but didnt update yet so dont do that quest
