### ISSUE TITLE
There is a password DOM violation that need to be fixed - you can view it in the Chrome devtools console.

### ISSUE THREAD

**Issue by Suvanth-Erranki** [maitian352/Meadow-Guarder#37]
The load handler takes too long.
![image](https://user-images.githubusercontent.com/63676047/97822065-9b31f200-1c82-11eb-87e9-e9b142bdd3f7.png)

**Comment by Suvanth-Erranki** [comment]
This no longer happens.

**Comment by maitian352** [comment]
The load handler takes that long because some maps are really big.
