### ISSUE TITLE
hotkey weapon switching

### ISSUE THREAD

**Issue by definitely-nobody-is-here** [maitian352/Meadow-Guarder#370]
you should be able to place a weapon into a hotkey slot so when you press a key it equips it. so it would be easier than scrolling through your inventory during a boss rush trying to find that one weapon in those 10000 other random trash things.

**Comment by maitian352** [comment]
ok

**Comment by maitian352** [comment]
Use for right click? Like secodary weapon

**Comment by definitely-nobody-is-here** [comment]
no like press a button and it equips

**Comment by maitian352** [comment]
Added. Now you can right click to swap weapons.
