### ISSUE TITLE
hotkey swithcing allows infinite speed

### ISSUE THREAD

**Issue by definitely-nobody-is-here** [maitian352/Meadow-Guarder#371]
by right clicking super fast with an autoclicker you can reset your click timeout and get two attacks. so you have infinite speed enchants and double the weapons.

**Comment by definitely-nobody-is-here** [comment]
so using two books of death or two books of lasers or whatever you can get a lot of damage

**Comment by maitian352** [comment]
what do you mean? this doesnt happen

**Comment by definitely-nobody-is-here** [comment]
false alarm i had speed 100%
