### ISSUE TITLE
OH NO CANVAS IS BROKEN AND IM IN A COLLISION

### ISSUE THREAD

**Issue by definitely-nobody-is-here** [maitian352/Meadow-Guarder#375]
![image](https://user-images.githubusercontent.com/67865358/126704986-5d49a6f6-b67e-4490-bac7-08efa13a2d94.png)

**Comment by definitely-nobody-is-here** [comment]
![image](https://user-images.githubusercontent.com/67865358/126705032-1fb7abc0-8370-49b9-bb6e-0e859a70e619.png)

**Comment by definitely-nobody-is-here** [comment]
![image](https://user-images.githubusercontent.com/67865358/126705123-01a7196a-e6ce-4d4e-8eca-1b0327a50b06.png)

**Comment by definitely-nobody-is-here** [comment]
![image](https://user-images.githubusercontent.com/67865358/126705163-aadb49f9-168e-4176-8c9c-9bb4825e322c.png)

**Comment by definitely-nobody-is-here** [comment]
help artifacting

**Comment by maitian352** [comment]
hecks

**Comment by maitian352** [comment]
![image](https://user-images.githubusercontent.com/68207888/126851941-7a424d74-873d-4dd1-811c-2a2ce6236ad1.png)
