### ISSUE TITLE
camera wobble makes clicking inaccurate

### ISSUE THREAD

**Issue by definitely-nobody-is-here** [maitian352/Meadow-Guarder#377]
camera wobble is not calculated into click location so I sometimes have to click on the ground to talk to an npc. I was spamming the wizard and nothing happened and then I clicked the floor to his right and then somehow that was talking to him. also its annoying because aiming is hard

**Comment by definitely-nobody-is-here** [comment]
also camera wobble means that everything wobbles around you and it feels like jelly

**Comment by maitian352** [comment]
I don't think this happens? Camera wobble is calculated into click location. It is dependent on cameraX and cameraY, which is the location of the camera, which is affected by camera wobble.
