### ISSUE TITLE
Using a scepter on yourself the same tick you take fatal damage sets self.isDead = true but you dont die

### ISSUE THREAD

**Issue by maitian352** [maitian352/Meadow-Guarder#380]
Screenshot:
![image](https://user-images.githubusercontent.com/68207888/126850886-5dc2e1fb-93b9-4e7a-9e66-1dd373e4bc81.png)

I was fighting sp and then I died to the sp laser so i used the scepter and this happened.

**Comment by maitian352** [comment]
Fixed. It turns out that the projectile that kills you sets isDead to true but then the healing scepter heals you and you don't die while self.isDead = true.

**Comment by definitely-nobody-is-here** [comment]
wasbugwasbugwasbugwasbugwasbugwasbugwasbugwasbugwasbugwasbugwasbugwasbugwasbugwasbugwasbugwasbugwasbugwasbugwasbugwasbugwasbugwasbugwasbug
