### ISSUE TITLE
i type while disconnected

### ISSUE THREAD

**Issue by definitely-nobody-is-here** [maitian352/Meadow-Guarder#385]
![image](https://user-images.githubusercontent.com/67865358/127012373-ab5e757e-7f5e-4e1c-92ec-ef5300df1274.png)

**Comment by definitely-nobody-is-here** [comment]
![image](https://user-images.githubusercontent.com/67865358/127668018-d24de15c-8eea-46a8-835e-48db5b512245.png)
fix alreay

**Comment by maitian352** [comment]
Fixed.
