### ISSUE TITLE
There is a way to still do the auto click glitch.

### ISSUE THREAD

**Issue by Suvanth-Erranki** [maitian352/Meadow-Guarder#40]
I figured out a secret way to do the auto glitches. Just click your touchpad and drag it up to the menu box. It really works!

Me doing the auto glitch:

![image](https://user-images.githubusercontent.com/63676047/97876183-7329a980-1ce9-11eb-9297-590bd399708d.png)

**Comment by maitian352** [comment]
Fixed.

**Comment by Suvanth-Erranki** [comment]
Uh no, I can still do the glitch.

**Comment by maitian352** [comment]
I didn't update it yet.

**Comment by Suvanth-Erranki** [comment]
Ok.
