### ISSUE TITLE
Monsters in maps with >1 players don't have health bars

### ISSUE THREAD

**Issue by maitian352** [maitian352/Meadow-Guarder#400]
![image](https://user-images.githubusercontent.com/68207888/127770784-dc2b93b4-3316-4b24-9bd3-5322a7373b1a.png)

Weird bug

**Comment by definitely-nobody-is-here** [comment]
unable to recreate

**Comment by definitely-nobody-is-here** [comment]
but something wierder
![image](https://user-images.githubusercontent.com/67865358/127774599-323b9769-c58f-4d55-b2d5-88508f71ae6d.png)
THE MONSTERS DONT EXIST

**Comment by definitely-nobody-is-here** [comment]
![image](https://user-images.githubusercontent.com/67865358/127774621-fc44d7dc-9a60-4ec8-9769-ee2ae388d8ce.png)

**Comment by maitian352** [comment]
Fixed. The bug was that Monsters weren't sending their width and height in the update packs correctly.
