### ISSUE TITLE
You can still do the auto click glitch!

### ISSUE THREAD

**Issue by Suvanth-Erranki** [maitian352/Meadow-Guarder#41]
The method to do the auto click glitch is to click and drag your mouse cursor to the url bar. Then, the player automatically fires.
Me doing the auto click glitch:

![image](https://user-images.githubusercontent.com/63676047/97906065-04f8dd00-1d11-11eb-987f-95b501fc6082.png)

**Comment by maitian352** [comment]
Fixed Again.

**Comment by Suvanth-Erranki** [comment]
Ok.

**Comment by Suvanth-Erranki** [comment]
Did you update?

**Comment by Suvanth-Erranki** [comment]
I can still do it.

**Comment by Suvanth-Erranki** [comment]
https://drive.google.com/file/d/16GP1zjO_03PXTpaItPp3l7E9hBiMU6io/view

VIEW THIS VIDEO TO SEE THE TUTORIAL.

**Comment by Suvanth-Erranki** [comment]
I found away - you can press F7 and the auto glitch still works.

**Comment by Suvanth-Erranki** [comment]
Also, there is a way to do the glitch without using any keyboard keys.

**Comment by maitian352** [comment]
Fixed.

**Comment by Suvanth-Erranki** [comment]
Ok, there is still one way. Press Ctrl + Shift + C and open Chrome Devtools. Then hold left click and let go of it on the chrome devtools part of the window. Then close chrome devtools and the glitch is there!

**Comment by Suvanth-Erranki** [comment]
There is stil a way to do the glitch, but you can only do it with a mouse. Hold down left click, unplug your mouse's USB and then plug it back in!

**Comment by Suvanth-Erranki** [comment]
Note, there is a way to detect if touchpad is being used or if mouse is being used: credits - https://stackoverflow.com/questions/10744645/detect-touchpad-vs-mouse-in-javascript

function handler(e) {
    var isTouchPad = e.wheelDeltaY ? e.wheelDeltaY === -3 * e.deltaY : e.deltaMode === 0
    // your code
   alert(isTouchPad ? "isTouchPad" : "isMouse");
}
document.addEventListener("mousewheel", handler, false);
document.addEventListener("DOMMouseScroll", handler, false);

**Comment by Suvanth-Erranki** [comment]
You can also do the auto click glitch by holding left click and releasing it on the downloads bar - this is the bar:
![image](https://user-images.githubusercontent.com/63676047/97926896-f7078400-1d31-11eb-9f27-75b80c3a80f7.png)

**Comment by Suvanth-Erranki** [comment]
I FIGURED OUT THE SOLUTION!!!!

Just add to your client/index.html 

document.documentElement.onclick = function() {
    socket.emit('keyPress',{inputId:"releaseAll",state:true});
}

**Comment by Suvanth-Erranki** [comment]
This is still possible for me by simply going to another tab while holding left click - then on the tab let go of your click and then come back to the game. I am on Chrome Canary and I used touchpad.

**Comment by Suvanth-Erranki** [comment]
This doesn't happen anymore.
