### ISSUE TITLE
The cave has sections where the graphics are glitching the player every where, shades of stripes are flying all over the place.

### ISSUE THREAD

**Issue by Suvanth-Erranki** [maitian352/Meadow-Guarder#44]
The cave has sections where the graphics are glitching the player every where, shades of stripes are flying all over the place.

**Comment by maitian352** [comment]
Can you post a screenshot?

**Comment by Suvanth-Erranki** [comment]
See this glitch:
![image](https://user-images.githubusercontent.com/63676047/98007576-8dcf5180-1dc1-11eb-8a94-b39efc72ed1e.png)

**Comment by Suvanth-Erranki** [comment]
Its hard to capture the glitch with a screenshot because the stripes appear quickly and disappear quickly.

**Comment by Suvanth-Erranki** [comment]
This is not happening to me anymore - GOOD!
