### ISSUE TITLE
If you spam the Sign In button when the page is loading, it says you signed in twice.

### ISSUE THREAD

**Issue by maitian352** [maitian352/Meadow-Guarder#46]
I spammed the Sign In button while the client was still loading the maps, and in the chat it said I signed in twice.
![image](https://user-images.githubusercontent.com/68207888/98034631-54a8d880-1de5-11eb-83f6-f28827f26ca4.png)

**Comment by Suvanth-Erranki** [comment]
Ok so here is the solution - I am still testing it:

**Comment by Suvanth-Erranki** [comment]
I didn't come up with the code yet but here is the main idea:

Add an event listener to the button. If the sign in works, disable the button through:

 document.getElementById("signIn").disabled = true;

If the sign in fails execute the following code:

document.getElementById("signIn").enabled = true;

**Comment by maitian352** [comment]
I have a different way. Add a variable called canSignIn, and at the start it is true and when you press the sign in button it becomes false for two seconds. So like this.
```
var canSignIn = true;
signIn.onclick = function(){
    if(canSignIn){
        //sign in code
        canSignIn = false;
        setTimeout(() => {
            canSignIn = true;
        },2000);
    }
}
```

**Comment by Suvanth-Erranki** [comment]
Ok. Try it.

**Comment by Suvanth-Erranki** [comment]
I can do it!
![image](https://user-images.githubusercontent.com/63676047/98038802-b704d780-1deb-11eb-8aec-1f8c07e413ed.png)

**Comment by maitian352** [comment]
Fixed.

**Comment by Suvanth-Erranki** [comment]
Ok
Did you update?
