### ISSUE TITLE
There is a way to fire bullets in the map village for about 0.5-1.5 seconds.

### ISSUE THREAD

**Issue by Suvanth-Erranki** [maitian352/Meadow-Guarder#47]
If you hold double click, go into any other place (i.e. the secret base), and still holding double click, come back to the map village, the bullets fire - sometimes they fire once, sometimes twice.

HERE IS A VIDEO:

https://drive.google.com/file/d/18y9HdDkx8lVh8Kp8gmJ21EInkJdms0mS/view

**Comment by Suvanth-Erranki** [comment]
I'll see if I can post a video of me doing so.

**Comment by maitian352** [comment]
Fixed.

**Comment by Suvanth-Erranki** [comment]
Good
