### ISSUE TITLE
Bread won't talk to me.

### ISSUE THREAD

**Issue by Suvanth-Erranki** [maitian352/Meadow-Guarder#49]
In this instance, I tried to talk to bread and I failed.
![image](https://user-images.githubusercontent.com/63676047/98120501-0561b700-1e7c-11eb-8184-761ea594861c.png)

**Comment by maitian352** [comment]
All of the Npc's except for Bob don't have quests anymore. This isn't a bug, but we are looking for more quest ideas, hopefully one that involves Bread.

**Comment by Suvanth-Erranki** [comment]
Ok, cool!
