### ISSUE TITLE
In the secret base when you talk to the big boss monster, if you click "I want the gold behind you," the boss monster says "Go ahead and try," but this is a very vague and poorly phrased wording.

### ISSUE THREAD

**Issue by Suvanth-Erranki** [maitian352/Meadow-Guarder#51]
![image](https://user-images.githubusercontent.com/63676047/98125498-8fad1980-1e82-11eb-9bb1-e6c3ab5a891c.png)

**Comment by maitian352** [comment]
This has been changed to 'You want the gold behind me? You\'ll have to kill me to get it!'
