### ISSUE TITLE
While you are doing a quest for Bob, he disappears - which is impossible!

### ISSUE THREAD

**Issue by Suvanth-Erranki** [maitian352/Meadow-Guarder#52]
![image](https://user-images.githubusercontent.com/63676047/98126115-3b566980-1e83-11eb-965b-5e039c491a87.png)

**Comment by maitian352** [comment]
Bob can wander a bit, so he might be offscreen on top.

**Comment by Suvanth-Erranki** [comment]
No, I checked everywhere in the village map.

**Comment by maitian352** [comment]
Yes, I also found Bread disappearing.

**Comment by Suvanth-Erranki** [comment]
I know right!

**Comment by maitian352** [comment]
Fixed. The problem was that a packet was lost so the client changed the Npc's x and y position to NaN.
