### ISSUE TITLE
server/DATABASE_URL.js

### ISSUE THREAD

**Issue by DevourCode** [maitian352/Meadow-Guarder#54]

**Comment by DevourCode** [comment]
Who is the server/DATABASE_URL.js file*

**Comment by definitely-nobody-is-here** [comment]
DATABASE_URL.js is a private piece of code. It will never be released due to security concerns.

**Comment by DevourCode** [comment]
Then what do you upload it to Public for?

**Comment by DevourCode** [comment]
What should be so "private" about DATABASE_URL?

**Comment by definitely-nobody-is-here** [comment]
You can also just play the game at the link.

https://meadowguarder.herokuapp.com/

also, shameless plug, GO PLAY MOUNTAIN GUARDER FREE TODAY at https://mountainguarder.herokuapp.com

**Comment by definitely-nobody-is-here** [comment]
Or play the old version at https://meadowguarderold.herokuapp.com/
It's more complete and personally I think it's better.

**Comment by DevourCode** [comment]
xD

**Comment by DevourCode** [comment]
okay, thanks

**Comment by definitely-nobody-is-here** [comment]
Also who even are you

**Comment by maitian352** [comment]
> What should be so "private" about DATABASE_URL?

so nobody accesses the database except for me

**Comment by definitely-nobody-is-here** [comment]
As I said, it's hidden for security reasons (we don't want people accessing the database and injecting/deleting stuff)

**Comment by maitian352** [comment]
> What should be so "private" about DATABASE_URL?

Search up what a database url is. It allows you to access and change a database.
