### ISSUE TITLE
In the land near the water, you can go onto the corners and make the player look like they are on the water.

### ISSUE THREAD

**Issue by Suvanth-Erranki** [maitian352/Meadow-Guarder#55]
![image](https://user-images.githubusercontent.com/63676047/98158501-00ffc300-1ea9-11eb-8812-bf4c25546772.png)

![image](https://user-images.githubusercontent.com/63676047/98158422-dada2300-1ea8-11eb-9433-abfd2cecd273.png)

**Comment by Suvanth-Erranki** [comment]
Why did you add a question label?

**Comment by Suvanth-Erranki** [comment]
You can also do this with a monster:


![image](https://user-images.githubusercontent.com/63676047/98453619-257ec800-2153-11eb-9a7a-e00a8e1a667e.png)

**Comment by Suvanth-Erranki** [comment]
Fixed.

**Comment by Suvanth-Erranki** [comment]
Well, sort of because you intentionally stopped this in the current version.

**Comment by maitian352** [comment]
This has been fixed with the addition of Collision2 and small collision tiles.

**Comment by Suvanth-Erranki** [comment]
Good!
