### ISSUE TITLE
There are certain areas in the Lilypad Part 1 where you can go onto the water fully.

### ISSUE THREAD

**Issue by Suvanth-Erranki** [maitian352/Meadow-Guarder#56]
![image](https://user-images.githubusercontent.com/63676047/98158785-808d9200-1ea9-11eb-93e0-1a1fb7018e47.png)

**Comment by maitian352** [comment]
If you count this, why don't you count going on the water in the middle of the lilypads?

**Comment by Suvanth-Erranki** [comment]
Maitian:

here is another place:

![image](https://user-images.githubusercontent.com/63676047/98159174-1de8c600-1eaa-11eb-93ac-16ee625859ba.png)

**Comment by Suvanth-Erranki** [comment]
Ok sure, count that too.

**Comment by Suvanth-Erranki** [comment]
This issue is fixed.
