### ISSUE TITLE
game is boring

### ISSUE THREAD

**Issue by definitely-nobody-is-here** [maitian352/Meadow-Guarder#56]
nothing to do add a plot or something before adding random mstuff

**Comment by maitian352** [comment]
kill monsters

**Comment by definitely-nobody-is-here** [comment]
boring

**Comment by maitian352** [comment]
Grind better items. Get all the secret easter egg items. Get max DPS for all classes. Research ways to beat Skeleton King with a Copper Shiv. Join the Copper Shiv war and try to get 20 Copper Shivs. Grind Gold Tokens and Ash Tokens. Grind Deaths. Grind Potions. Grind Wood, Cotton and Yarn. Recreate the `quark123` and `admin` troll. Make a better hack client than MGHC. Join the [Meadow Guarder Discord Server](https://discord.gg/Py5GKdMvrZ). Mod the game. Grind Wood Sticks and join the Wood Stick war. Visit Meadow Guarder News. Create like 10 alt accounts to store extra diamond items. Get a max Crit Chance build. Get a max defense build. Get a max hp build. Get a max Crit Power build. Get a max mana build. Get a max hp regen build. get a max mana regen build. Kill Skeleton King without a weapon. (might be possible) Get more Copper Shivs. Break the fourth wall. Pretend to be a new player. Open an item shop. (wood as currency? or copper shivs for the Copper Shiv war?) Get more players to play Meadow Guarder. Grind Skeleton King. Make a Meadow Guarder wiki. Get one of every item. Get an OG item. Post actual bugs on the Meadow Guarder Github. Kill Skeleton King with a Rusty Axe. (probably not possible). PvP. Download a old version of Meadow Guarder and play that. Troll sp by pretending to be a new player. Get the best bundle. Find out just how many items have an easter egg description. Find out how many items have a reference in their description. Kill monsters. Do the tileset trick where every tile is drawn a few pixels off. Do the previous tileset trick except using rotation. Use a random file as `tileset.png`. Use a random file as `items2.png`. Randomize the monsters in `monsters.json`. Kill mosters. Find good hide-and-seek hiding spots. Make a character randomizer hack. Make a auto-pathfind hack. Play Meadow Guarder on your phone. (it won't work). Do a Skeleton King% speedrun. Do a Meadow Guarder manhunt. Wait. Sleep. Eat. Sleep some more. Play with Rainy, Salt, and a large person. (opposite of something). Program a better CubieWorld. Try to make a "Best" build. Find the most amount of damage one projectile can do. Find the best passives. Play [Meadow Guarder](http://meadowguarder.herokuapp.com).

**Comment by definitely-nobody-is-here** [comment]
too grindy

**Comment by maitian352** [comment]
Grind better items. Get all the secret easter egg items. Get max DPS for all classes. Research ways to beat Skeleton King with a Copper Shiv. Join the Copper Shiv war and try to get 20 Copper Shivs. Grind Gold Tokens and Ash Tokens. Grind Deaths. Grind Potions. Grind Wood, Cotton and Yarn. Recreate the `quark123` and `admin` troll. Make a better hack client than MGHC. Join the [Meadow Guarder Discord Server](https://discord.gg/Py5GKdMvrZ). Mod the game. Grind Wood Sticks and join the Wood Stick war. Visit Meadow Guarder News. Create like 10 alt accounts to store extra diamond items. Get a max Crit Chance build. Get a max defense build. Get a max hp build. Get a max Crit Power build. Get a max mana build. Get a max hp regen build. Get a max mana regen build. Kill Skeleton King without a weapon. (might be possible). Get more Copper Shivs. Break the fourth wall. Pretend to be a new player. Open an item shop. (wood as currency? or copper shivs for the Copper Shiv war?) Get more players to play Meadow Guarder. Grind Skeleton King. Make a Meadow Guarder wiki. Get one of every item. Get an OG item. Post actual bugs on the Meadow Guarder Github. Kill Skeleton King with a Rusty Axe. (probably not possible). PvP. Download a old version of Meadow Guarder and play that. Troll sp by pretending to be a new player. Get the best bundle. Find out just how many items have an easter egg description. Find out how many items have a reference in their description. Kill monsters. Do the tileset trick where every tile is drawn a few pixels off. Do the previous tileset trick except using rotation. Use a random file as `tileset.png`. Use a random file as `items2.png`. Randomize the monsters in `monsters.json`. Kill mosters. Find good hide-and-seek hiding spots. Rickroll someone. Make a character randomizer hack. Make a auto-pathfind hack. Play Meadow Guarder on your phone. (it won't work). Do a Skeleton King% speedrun. Do a Meadow Guarder manhunt. Wait. Sleep. Eat. Sleep some more. Play with Rainy, Salt, and a large person. (opposite of something). Program a better CubieWorld. Try to make a "Best" build. Find the most amount of damage one projectile can do. Find the best passives. Kill Ten Eyed One. Kill Ten Eyed One without dying. Break the game. Do a Ten Eyed One% speedrun. Mod the game. Infiltrate West Wood Wolves. Get #1 on Leaderboard. Store items and trade them for Death Globes. Trade items for real world money (not recommended). Break every rule. Get the secret death message. Get weird items like Diamond Bars. Post bugs. Make suggestions. Get Admin. Craft Blade of Death. Craft Frozen Breath. Craft Shield of Life. Craft Valerian Wand. Stream Meadow Guarder. Get good at using shields. Use MGHC. Play [Meadow Guarder](https://www.youtube.com/watch?v=dQw4w9WgXcQ).
