### ISSUE TITLE
You can walk through a tree in the secret base.

### ISSUE THREAD

**Issue by Suvanth-Erranki** [maitian352/Meadow-Guarder#57]
![image](https://user-images.githubusercontent.com/63676047/98159824-3a393280-1eab-11eb-8d75-91c1a15c1f30.png)

**Comment by Suvanth-Erranki** [comment]
LOL

**Comment by Suvanth-Erranki** [comment]
If you have just the right point where you enter the secret base, you can do the glitch.

**Comment by Suvanth-Erranki** [comment]
I did it again!

![image](https://user-images.githubusercontent.com/63676047/98159952-72407580-1eab-11eb-88f2-0a8399800c15.png)

**Comment by maitian352** [comment]
Fixed.

**Comment by Suvanth-Erranki** [comment]
I will post a video on how to do it.

**Comment by Suvanth-Erranki** [comment]
Wait what?
How did you fix it?

**Comment by Suvanth-Erranki** [comment]
Did you update it yet?

**Comment by Suvanth-Erranki** [comment]
Cause I still did it:
![image](https://user-images.githubusercontent.com/63676047/98160401-27732d80-1eac-11eb-9b66-fea00538ec61.png)

**Comment by Suvanth-Erranki** [comment]
Ok you updated nevermind.

**Comment by Suvanth-Erranki** [comment]
THIS IS OBVIOUSLY NOT FIXED - LOL ;)

![image](https://user-images.githubusercontent.com/63676047/98164977-1aa60800-1eb3-11eb-94e6-8cb3f1c3e2d6.png)

**Comment by maitian352** [comment]
Finally fixed.
