### ISSUE TITLE
skeleton king too op

### ISSUE THREAD

**Issue by definitely-nobody-is-here** [maitian352/Meadow-Guarder#59]
veryy unbalanced
ruby gun and ruby waraxe cant make 1 damage on it

**Comment by definitely-nobody-is-here** [comment]
and it 1 shots you

**Comment by maitian352** [comment]
its supposted to

best strategy is to get diamond claw, sky robe, and red fedora. Run away while hitting it

**Comment by maitian352** [comment]
> and it 1 shots you

it only does 50 damage
