### ISSUE TITLE
There is a spot in the forest where if a monster shoots at you and hits you, you don't take any damage.

### ISSUE THREAD

**Issue by Suvanth-Erranki** [maitian352/Meadow-Guarder#60]
This account is a brand new account - it hasn't killed any monsters/gotten any weapons.
![image](https://user-images.githubusercontent.com/63676047/98170598-47125200-1ebc-11eb-96ae-409284b26726.png)

**Comment by maitian352** [comment]
This is because the projectile got deleted before it could hit you.

**Comment by Suvanth-Erranki** [comment]
No, the projectile hit me - but it did not damage.

**Comment by maitian352** [comment]
Fixed.

**Comment by Suvanth-Erranki** [comment]
Ok.

**Comment by Suvanth-Erranki** [comment]
Did you update yet?
