### ISSUE TITLE
collisions wierd

### ISSUE THREAD

**Issue by definitely-nobody-is-here** [maitian352/Meadow-Guarder#60]
![image](https://user-images.githubusercontent.com/67865358/140445900-5eda97b0-4529-4e56-97b9-7e87a7b4de67.png)
why??? theres nothing there so unless your wall is 4 tiles thick at the bottom and only 1 at the top (so really stupid wall) it shouldn't be that way

so stupid.

go play mountain guarder instead the collisions are more wierd AS YOU CAN LITERALLY STAND IN A STAIRCASE

**Comment by definitely-nobody-is-here** [comment]
at least I found an issue that makes sense unlike you

**Comment by maitian352** [comment]
did you just pass the line?
