### ISSUE TITLE
this

### ISSUE THREAD

**Issue by definitely-nobody-is-here** [maitian352/Meadow-Guarder#61]
![image](https://user-images.githubusercontent.com/67865358/140446041-5731b406-63b7-46c3-8187-a1731ed24a8a.png)

**Comment by maitian352** [comment]
how am i supposted to fix it?

**Comment by definitely-nobody-is-here** [comment]
change the chunks to stripes

**Comment by maitian352** [comment]
and then? is the axe supposted to go on top of the chair or underneath the chair?

**Comment by definitely-nobody-is-here** [comment]
on top. duh.

**Comment by maitian352** [comment]
so should held items be on top of everything?

**Comment by maitian352** [comment]
> on top. duh.

but then you might be like

axe is on top of chair

it looks weird

stupid
