### ISSUE TITLE
If you say to the boss monster that Bob told you to come the secret basement, you get an incorrect prompt to respond to the boss's response.

### ISSUE THREAD

**Issue by Suvanth-Erranki** [maitian352/Meadow-Guarder#62]
It says that Bob told you to come to the forest, but this is the secret base basement!
![image](https://user-images.githubusercontent.com/63676047/98259889-a9b52d80-1f50-11eb-833f-8aaec62cee14.png)

**Comment by maitian352** [comment]
It is supposed to be River.

**Comment by Suvanth-Erranki** [comment]
What?

**Comment by maitian352** [comment]
Fixed.
