### ISSUE TITLE
skeleton king just walked through a tree

### ISSUE THREAD

**Issue by definitely-nobody-is-here** [maitian352/Meadow-Guarder#62]
what just happened

i just saw it go over a tree and then kill me

**Comment by maitian352** [comment]
interpolation and lag?

**Comment by Suvanth-Erranki** [comment]
Perhaps the next time it happens, screenshot it or something. I usually do this, because it provides more clarity for the problem.

**Comment by Suvanth-Erranki** [comment]
There hasn't been much discussion on the issue, nor sufficient evidence to confirm this bug really exists. I think we can close this.
