### ISSUE TITLE
interiors are wierd

### ISSUE THREAD

**Issue by definitely-nobody-is-here** [maitian352/Meadow-Guarder#64]
![image](https://user-images.githubusercontent.com/67865358/140619347-9b5b17ef-cbc6-4a71-ac77-03eccb938ecd.png)
this wall is stupidly thick and there is no point in making it so thick. why are all the walls so thick??

also inside you cant see the other side of the exterior walls so it seems like they are super thick

stupid.

**Comment by maitian352** [comment]
I don't have thinner walls.

**Comment by definitely-nobody-is-here** [comment]
then make some. if I could make snow tiles then you can make thinner walls

**Comment by maitian352** [comment]
Thinner walls look weird.
