### ISSUE TITLE
Tianmu is makeing a new GUN MOD!!!!!!

### ISSUE THREAD

**Issue by Tianmu695** [maitian352/Meadow-Guarder#65]
It has so many COOOL guns, like a GOLDEN DEAGLE, and even THE TIANMU OP GUN!!!!!!!!! ITS SOOOOOO OPPPPPPP!!!!!

**Comment by Tianmu695** [comment]
yep it is

**Comment by Tianmu695** [comment]
your right @Tianmu695 i hate meadow guarder

**Comment by Tianmu695** [comment]
ok VERY AWSWME
 by noob

**Comment by Suvanth-Erranki** [comment]
That's really cool. However, I think that we should move this to the discussions section, as this is more of an announcement than an actual issue. Let's just make the open issues something which is an actual problem.

**Comment by definitely-nobody-is-here** [comment]
this isn't an issue.

**Comment by definitely-nobody-is-here** [comment]
also why is it marked as documentation

**Comment by Tianmu695** [comment]
Im not doing this
