### ISSUE TITLE
The gap to enter the Altoris Island from the Sleeping Boar Inn needs to be fixed

### ISSUE THREAD

**Issue by Suvanth-Erranki** [maitian352/Meadow-Guarder#66]
![image](https://user-images.githubusercontent.com/76885647/141596092-f568176c-44a2-4eff-b10e-e1a492a63634.png)
I can't get through, even when I'm just a little bit away from going through the passage. Please make this passage wider. I find this very frustrating if I am being honest.

**Comment by maitian352** [comment]
Will be fixed in the new map update.

**Comment by Suvanth-Erranki** [comment]
Great!

**Comment by maitian352** [comment]
Actually, just hold left/right and walk into the wall.
