### ISSUE TITLE
Players should be able to use swords and shields together.

### ISSUE THREAD

**Issue by Suvanth-Erranki** [maitian352/Meadow-Guarder#67]
This would be a really awesome combo and if it can be used in real battles, why not in the game as well? Also, it is kind of annoying to have to have to constantly switch from offense to defense. It would be easier to have both together. That's just my opinion though.

**Comment by Suvanth-Erranki** [comment]
Actually my first issue was the previous issue: https://github.com/maitian352/Meadow-Guarder/issues/66

**Comment by Suvanth-Erranki** [comment]
But thanks

**Comment by maitian352** [comment]
This would be really cool to be in the game! However, it would be pretty hard to implement and balance, like should shields block damage and do you have to activate the shield or not. Also, if you are using a bow or a staff, what would a shield do?

**Comment by Suvanth-Erranki** [comment]
I don't think it makes much sense to use a bow and a shield (how do you even hold that lol?) and I don't think a staff makes much sense either. Just make it sword and shield, because that's really the best combo.

**Comment by Suvanth-Erranki** [comment]
I understand that it is hard so perhaps we can leave this open, but it does not necessarily have to be added instantly.

**Comment by Suvanth-Erranki** [comment]
Also, I think the shields should be blocking damage in whatever direction the cursor is aimed at. This would be really cool - it would be as though the player is actually fighting the battle.

**Comment by maitian352** [comment]
> I don't think it makes much sense to use a bow and a shield (how do you even hold that lol?) and I don't think a staff makes much sense either. Just make it sword and shield, because that's really the best combo.

The problem is that this would make rangers and mages underpowered. I think a good idea might be having a special sword that you can also use as a shield. Or, maybe you could have a potion that gives you a shield.

> Also, I think the shields should be blocking damage in whatever direction the cursor is aimed at. This would be really cool - it would be as though the player is actually fighting the battle.

Would a wooden shield block like a diamond shield? That basically makes higher levels of shields useless.

**Comment by Suvanth-Erranki** [comment]
Ok, we can just switch a slot in the hotbar from a sword to a shield, so when it is a sword you attack and when it is a shield you block. This can be implemented through scrolling. Also, better shields will block more damage.

**Comment by maitian352** [comment]
> Ok, we can just switch a slot in the hotbar from a sword to a shield, so when it is a sword you attack and when it is a shield you block. This can be implemented through scrolling. Also, better shields will block more damage.

Scrolling has been implemented three months ago.

**Comment by definitely-nobody-is-here** [comment]
technically you can have a shield equipped in your offhand and use any weapon in your hotbar

**Comment by definitely-nobody-is-here** [comment]
![image](https://user-images.githubusercontent.com/67865358/143665533-eea4bbb5-b564-4987-b4dc-65db8460b13f.png)

**Comment by maitian352** [comment]
Even **_LOVAGE VINES!!!_**

**Comment by maitian352** [comment]
> This would be a really awesome combo and if it can be used in real battles, why not in the game as well? Also, it is kind of annoying to have to have to constantly switch from offense to defense. It would be easier to have both together. That's just my opinion though.

I mean, there's not really any offense or defense. It's just that you can have different builds, such as a tank build, glass cannon, etc.
