### ISSUE TITLE
You can go on top of a tree in the bridge area and look like a weird glitch.

### ISSUE THREAD

**Issue by Suvanth-Erranki** [maitian352/Meadow-Guarder#68]
Look at the character on top of the tree:
![image](https://user-images.githubusercontent.com/63676047/98393685-8c1bbd00-2051-11eb-86e0-ba9dfc715e7e.png)
 The character should look like this:
![image](https://user-images.githubusercontent.com/63676047/98393955-f7fe2580-2051-11eb-9ad0-1d4ac6e6d2b5.png)
You shouldn't be able to see the character's legs when they are under a tree.

**Comment by maitian352** [comment]
Fixed.
