### ISSUE TITLE
The chat says that the game is version 0.0.9 when it is actually 0.1.0

### ISSUE THREAD

**Issue by Suvanth-Erranki** [maitian352/Meadow-Guarder#69]
![image](https://user-images.githubusercontent.com/63676047/98401705-07836b80-205e-11eb-91cc-85d03246930c.png)

**Comment by maitian352** [comment]
It is actually version 009f10a.

**Comment by Suvanth-Erranki** [comment]
Oh - then why does it say on github version 0.1.0 ?

**Comment by maitian352** [comment]
Because the milestone is version 0.1.0, which means we hope to get to version 0.1.0 by 11/9.

**Comment by Suvanth-Erranki** [comment]
Oh okay. So should we close the issue?

**Comment by maitian352** [comment]
Ok.

**Comment by maitian352** [comment]
Fixed.
