### ISSUE TITLE
This bug causes half of the screen goes black!

### ISSUE THREAD

**Issue by Suvanth-Erranki** [maitian352/Meadow-Guarder#69]
![image](https://user-images.githubusercontent.com/76885647/141600818-c18bdeeb-1da3-4ecc-bfbc-7a86710196cc.png)
![image](https://user-images.githubusercontent.com/76885647/141600867-10c5bec9-8bf6-4387-bbae-de5aadaf4c9e.png)

Please fix. Also why is this happening?

**Comment by maitian352** [comment]
What did you do?

**Comment by maitian352** [comment]
You are leaving the world. This is also fixed.
