### ISSUE TITLE
Please add a pause button!

### ISSUE THREAD

**Issue by Suvanth-Erranki** [maitian352/Meadow-Guarder#70]
It's so inconvenient when you have to leave for some reason (such as the bathroom) and when you come back, you've died from monsters and have to respawn all the way back in the inn. Adding a pause button means that the game is frozen (no interaction, except for resume button). This would be extremely helpful in certain scenarios.

**Comment by definitely-nobody-is-here** [comment]
here's the problem - you would have to pause the entire server, this is literally asking to pause an online game. What if other people are online? what now? It's better to just leave the server.

**Comment by maitian352** [comment]
> here's the problem - you would have to pause the entire server, this is literally asking to pause an online game. What if other people are online? what now? It's better to just leave the server.

I think because this is an online game, there won't be a pause button.
