### ISSUE TITLE
Mark won't respond to me.

### ISSUE THREAD

**Issue by Suvanth-Erranki** [maitian352/Meadow-Guarder#70]
![image](https://user-images.githubusercontent.com/63676047/98422977-1df0ed80-2085-11eb-8330-6766c17654b0.png)

**Comment by Suvanth-Erranki** [comment]
It works now!

**Comment by maitian352** [comment]
This is probably because you are doing another quest. In the future, we hope to have a current quest to make it less confusing.

**Comment by Suvanth-Erranki** [comment]
Ok.

**Comment by maitian352** [comment]
Notifications fixes everything
