### ISSUE TITLE
Let the player see the stats of the items they have in their inventory.

### ISSUE THREAD

**Issue by Suvanth-Erranki** [maitian352/Meadow-Guarder#71]
This makes it so much easier to know what items in your inventory is useless and not useless, without having to remove the items and check their stats after having dropped them.

**Comment by maitian352** [comment]
you can see  the stats
just hover over the item

**Comment by maitian352** [comment]
![image](https://user-images.githubusercontent.com/68207888/141651604-265d2dc6-a334-4ac4-8abc-c6e71c2d3cac.png)

**Comment by definitely-nobody-is-here** [comment]
maybe... test that your bug/suggestion isn't already  done before posting it.
