### ISSUE TITLE
Sometimes, when you enter another area on the map, for a split second, you are on the wrong patch of land.

### ISSUE THREAD

**Issue by Suvanth-Erranki** [maitian352/Meadow-Guarder#71]
When I entered the starter house from the village, for a split second, I was in the forest.
Here is a video of me doing this glitch:
https://drive.google.com/file/d/1DDJPC08BtTW4RwYrjNfoVq85Czq_OG03/view?usp=sharing

This is the split image of me in map forest but the game renders it as starter house because I was entering the starter house from the village.
![image](https://user-images.githubusercontent.com/63676047/98447479-049b8000-211d-11eb-8f92-0899c9ebf8c9.png)

**Comment by maitian352** [comment]
Fixed.

**Comment by Suvanth-Erranki** [comment]
Actually I can still do this after you updated.

**Comment by Suvanth-Erranki** [comment]
its now fixed.

**Comment by Suvanth-Erranki** [comment]
This is now happening to me again.

**Comment by Suvanth-Erranki** [comment]
This doesn't happen anymore.
