### ISSUE TITLE
New items suggestion, based on Greek Mythology!

### ISSUE THREAD

**Issue by Suvanth-Erranki** [maitian352/Meadow-Guarder#72]
I have an idea for a few new items. 

- We can make a staff called the "The Caduceus". This staff would make the player's movement really fast (in Greek Mythology, Hermes, the god of speed and movement had a staff named Caduceus).

- We can make winged sandals called "Talaria". Heremes had a pair of Winged Sandals with the same name that allowed him to travel very quickly.

- We can make a shield called "The Aegis". This was one of the most powerful shields in Greek Mythology. 

For the stats, I suggest we make these weapons one of the most powerful and rare items since in the mythology, they were very rare and powerful.

Tell me what you think of these ideas.

**Comment by Suvanth-Erranki** [comment]
Image of Caduceus:
![image](https://user-images.githubusercontent.com/76885647/141653548-8c3102a8-6d34-46e0-aa0a-1d93ff132d7f.png)

Image of Talaria:
![image](https://user-images.githubusercontent.com/76885647/141653569-795bfb31-738e-4690-afad-b4f8eb29870f.png)

Image of The Aegis:
![image](https://user-images.githubusercontent.com/76885647/141653582-48561aac-f043-4c91-bd25-a842a9e3736d.png)

**Comment by maitian352** [comment]
I might add Caduceus, but I don't think I will add the other two.

**Comment by Suvanth-Erranki** [comment]
that was an accident

**Comment by maitian352** [comment]
There is just one problem. It is hard to find sprites, because I am using the itemset attached below.
![items2](https://user-images.githubusercontent.com/68207888/143616163-b61cc11f-2b6d-4747-b2de-3fe07c9f6e1c.png)
