### ISSUE TITLE
Suggestion: Add weather!

### ISSUE THREAD

**Issue by Suvanth-Erranki** [maitian352/Meadow-Guarder#73]
It would be really cool to add:

- Rain
- Snow
- Hail
- Storms
- Lightning and thunder effects

We can even make things like lightning or hail can damage the player if they get hit. I think this would be extremely cool!

**Comment by Tianmu695** [comment]
Meadow Guarder Is a 2D game

So it will be hard to add

**Comment by maitian352** [comment]
> Meadow Guarder Is a 2D game
> 
> So it will be hard to add

no it wont
