### ISSUE TITLE
Sometimes at random points, you can't kill a monster.

### ISSUE THREAD

**Issue by Suvanth-Erranki** [maitian352/Meadow-Guarder#73]
This happened to me:
https://drive.google.com/file/d/1GuXOSedqFf0hjfXwqSQ_32-uQkK1EBNG/view

**Comment by maitian352** [comment]
This is because the monster is actually right in front of you and it didn't update.

**Comment by maitian352** [comment]
If you leave the tab, the monsters don't update and this can happen.

**Comment by Suvanth-Erranki** [comment]
This bug happened again:
https://drive.google.com/file/d/1-aKxK6wdLqcDv81dTsfukpa31nVqkGSY/view

**Comment by maitian352** [comment]
Fixed.
