### ISSUE TITLE
BUG - Pickaxe doesn't swing when mouse button held

### ISSUE THREAD

**Issue by definitely-nobody-is-here** [maitian352/Meadow-Guarder#74]
If I use a pickaxe or any other item used for harvesting resources and hold the mouse button it won't actually swing, it'll just sit there at an angle and move with my mouse.
![image](https://user-images.githubusercontent.com/67865358/141655110-ed32fa08-af27-415b-84c2-4e7c36b8e48f.png)
P.S. It's the hacks problem. There should be multiple entities popping up.

**Comment by maitian352** [comment]
I use "sameId", which makes all the projectiles have the same Id. This means that there will never be two swords you swing. This is a bug with MGHC.
