### ISSUE TITLE
In the Upper Mine Deposit, somehow the monster detects your presence even if it can't see you.

### ISSUE THREAD

**Issue by Suvanth-Erranki** [maitian352/Meadow-Guarder#74]
View this video to see the full details:
https://drive.google.com/file/d/1zpfw2s1CY81xVcxo90JV-0A4pSCyvwuH/view

**Comment by maitian352** [comment]
Are you sure the monster can't see you? You can see the monster.

**Comment by Suvanth-Erranki** [comment]
I know but that shouldn't be possible because if you think about it, its like you are on the roof of a building and a you are surrounded by trees and the monster below you sees you.

**Comment by maitian352** [comment]
Monsters have magical abilities. Why aren't you questioning them being able to shoot infinite amounts of ninja stars?

**Comment by Suvanth-Erranki** [comment]
Ok yeah sure I guess with that logic.

**Comment by Suvanth-Erranki** [comment]
Now that I think about it, it is an issue because how come when I get this close to a monster and it has the ability to see and detect me and it doesn't:
![image](https://user-images.githubusercontent.com/63676047/98470345-e8f7ae80-21dc-11eb-9a68-eca42f230a58.png)
but the monster can't see me in this image and yet it detects me:
![image](https://user-images.githubusercontent.com/63676047/98470396-32e09480-21dd-11eb-8f32-849cb3a39286.png)

THE REAL ISSUE HERE IS THE DIFFERENCE IN THE MONSTERS ABILITIES EVEN THOUGH THEY ARE THE SAME MONSTERS.

**Comment by maitian352** [comment]
Why can't the monster be better at detecting players through trees than over a long distance?

**Comment by Suvanth-Erranki** [comment]
Because they are the same purple monsters, just in different distances
and settings. They should have equal abilities Maitian.

**Comment by maitian352** [comment]
They do have equal abilities. They detect for a player over an 8 tile radius.

**Comment by Suvanth-Erranki** [comment]
I know, but what I'm saying is the terrain should be a variable in
their detecting abilities, because if the monster is trapped, then how
would it be able to sense a player right if its detecting systems
can't move around?
There has to be some logic.

**Comment by maitian352** [comment]
Ok, but then the terrain will also be a variable to the player's detecting abilities.

**Comment by Suvanth-Erranki** [comment]
Yes that is a good idea. But wait, how will you impliment this?

**Comment by maitian352** [comment]
> I know, but what I'm saying is the terrain should be a variable in their detecting abilities, because if the monster is trapped, then how would it be able to sense a player right if its detecting systems can't move around? There has to be some logic.
> […](#)
> On 11/9/20, maitian352 ***@***.***> wrote: They do have equal abilities. They detect for a player over an 8 tile radius. -- You are receiving this because you modified the open/close state. Reply to this email directly or view it on GitHub: [#74 (comment)](https://github.com/maitian352/Meadow-Guarder/issues/74#issuecomment-723979630)

If your player was trapped, you can still detect monsters.

**Comment by Suvanth-Erranki** [comment]
Yeah but what I mean is that one of the purple monsters isn't trapped
and cannot detect the player while the other monster is trapped but it
can detect the player.

**Comment by maitian352** [comment]
The monster that isn't trapped is further away from you.

**Comment by Suvanth-Erranki** [comment]
After thinking this through I guess its just not a bug.

**Comment by maitian352** [comment]
Also, why does it matter if the monster's detecting abilities are different? It's just like a player that only attacks you if it is trapped.

**Comment by Suvanth-Erranki** [comment]
Okay.
