### ISSUE TITLE
The player can go through the bridge wall in the map bridge area.

### ISSUE THREAD

**Issue by Suvanth-Erranki** [maitian352/Meadow-Guarder#75]
At the top of the bridge, you can't go through the walls. At the bottom though, some glitch allows you to - on both sides of the bottom of the bridge.
Here is an image:

![image](https://user-images.githubusercontent.com/63676047/98451647-9e742480-213f-11eb-9f13-0861bde7a0e1.png)

**Comment by maitian352** [comment]
Fixed.
