### ISSUE TITLE
BUG - flowers render under player

### ISSUE THREAD

**Issue by definitely-nobody-is-here** [maitian352/Meadow-Guarder#75]
![image](https://user-images.githubusercontent.com/67865358/141655146-53767110-0f24-44db-9a5c-340ee1299320.png)
flowers should be considered entities if they don't have collision

**Comment by maitian352** [comment]
They are entities. This is how entities act.

**Comment by maitian352** [comment]
Is the bug the healthbar or what?

**Comment by definitely-nobody-is-here** [comment]
no the flower is under the player no matter what

**Comment by maitian352** [comment]
> no the flower is under the player no matter what

You're standing on the flower.
