### ISSUE TITLE
Sometimes the game glitches the player so that they are rendered as unknown and their messages are in black font.

### ISSUE THREAD

**Issue by Suvanth-Erranki** [maitian352/Meadow-Guarder#76]
Here is an image:

![image](https://user-images.githubusercontent.com/63676047/98451695-104c6e00-2140-11eb-84c9-5f5d904e36fd.png)

**Comment by maitian352** [comment]
This isn't glitches, this is intentional.

**Comment by Suvanth-Erranki** [comment]
Oh okay.
