### ISSUE TITLE
BUG - projectiles stop when out of range

### ISSUE THREAD

**Issue by definitely-nobody-is-here** [maitian352/Meadow-Guarder#76]
A projectile will stop and then fade out when out of range
![image](https://user-images.githubusercontent.com/67865358/141655165-2980fabd-28ca-418c-98a9-c90fa819a636.png)

**Comment by maitian352** [comment]
Is there anything wrong with this?

**Comment by definitely-nobody-is-here** [comment]
they just float there

**Comment by maitian352** [comment]
Fixed.
