### ISSUE TITLE
Bug: I can't pick up items sometimes

### ISSUE THREAD

**Issue by Suvanth-Erranki** [maitian352/Meadow-Guarder#78]
Video proof (No audio, but I really was clicking on the wood to pick it up and it didn't work):
https://www.youtube.com/watch?v=9frMQ7kCrAQ

As far as I know, this bug isn't reproducable, so I don't know why it was happening.

**Comment by Suvanth-Erranki** [comment]
Also, you can see that I am clicking, because everytime I click, it shows that the weapons are being used.

**Comment by Suvanth-Erranki** [comment]
This could be because the item is illegal and has an undefined id.

**Comment by maitian352** [comment]
I was able to reproduce this bug, and opened the console. There were errors because the item had an id of undefined.

**Comment by Suvanth-Erranki** [comment]
This happened to me again with mystic gloves.

**Comment by maitian352** [comment]
Fixed.

**Comment by Suvanth-Erranki** [comment]
Not fixed.

**Comment by Suvanth-Erranki** [comment]
I wasn't able to pick up a few death globes still. I have a video if you need proof.

**Comment by Suvanth-Erranki** [comment]
Nevermind, my inventory was full I think. I wasn't sure though. sorry.
