### ISSUE TITLE
In the upper mine deposit, the blue monster went in between the wall - that should be impossible, the player can't do that.

### ISSUE THREAD

**Issue by Suvanth-Erranki** [maitian352/Meadow-Guarder#78]
![image](https://user-images.githubusercontent.com/63676047/98453234-d898f280-214e-11eb-9f5d-abd4c677b227.png)

**Comment by maitian352** [comment]
I think this issue is related to [this](https://github.com/maitian352/Meadow-Guarder/issues/73), and the client is rendering the monster in the wall when it actually not.

**Comment by Suvanth-Erranki** [comment]
Yes it seems so that the monster doesn't see the structure.

**Comment by maitian352** [comment]
Fixed.

**Comment by Suvanth-Erranki** [comment]
Nice!
