### ISSUE TITLE
While you are still moving from one land to another, a monster fires on you even though you haven't even reached the other land for the monster to detect you.

### ISSUE THREAD

**Issue by Suvanth-Erranki** [maitian352/Meadow-Guarder#79]
This is the first frame in which you can see yourself in another place after moving and you see that the mosnter has already fired bullets!
![image](https://user-images.githubusercontent.com/63676047/98453496-b0f75980-2151-11eb-883a-754ee24d0c5c.png)

Here is a video to me doing this glitch:
https://drive.google.com/file/d/1GKxrq8tTagYpT8HRCpGsMi0b8zOQBYlh/view?usp=sharing

**Comment by maitian352** [comment]
Fixed.
