### ISSUE TITLE
slight problem if map is smaller than screen

### ISSUE THREAD

**Issue by definitely-nobody-is-here** [maitian352/Meadow-Guarder#79]
I'm using a big screen
![image](https://user-images.githubusercontent.com/67865358/141661112-80b96971-57a9-4004-b41a-0c95d9cbd60c.png)

**Comment by Suvanth-Erranki** [comment]
What size screen? I have a 17.3 inch laptop and this isn't happening to me. Are you using a special monitor?

**Comment by Suvanth-Erranki** [comment]
Let me try using my monitor.

**Comment by Suvanth-Erranki** [comment]
Even my monitor doesn't have this issue. I think you accidentally enabled free cam mode or something.

**Comment by Suvanth-Erranki** [comment]
Did you zoom out? I think you zoomed out with ctrl - which makes this happen.
