### ISSUE TITLE
If the monster goes on the edge of the sand, the monster goes entirely on the water - a glitch.

### ISSUE THREAD

**Issue by Suvanth-Erranki** [maitian352/Meadow-Guarder#81]
I was able to do the glitch without using the "move anywhere hack" but the player covered the monster, so I went onto the water to get a clear shot of how the monster was on the corner in a glitchy way.

![image](https://user-images.githubusercontent.com/63676047/98453619-257ec800-2153-11eb-9a7a-e00a8e1a667e.png)

**Comment by maitian352** [comment]
This is a duplicate of [this](https://github.com/maitian352/Meadow-Guarder/issues/55), where instead of the player going on the water, the monster goes on the monster.

**Comment by Suvanth-Erranki** [comment]
Okay.

**Comment by Suvanth-Erranki** [comment]
I will combine the issues.
