### ISSUE TITLE
When you you get stuck, but you can still type in chat as "Unknown", if you try to run the command " for(var i in Player.list){console.log(Player.list[i]);} " you still can't move.

### ISSUE THREAD

**Issue by Suvanth-Erranki** [maitian352/Meadow-Guarder#82]
When you you get stuck, but you can still type in chat as "Unknown", if you try to run the command " for(var i in Player.list){console.log(Player.list[i]);} " you still can't move.

**Comment by maitian352** [comment]
Fixed.

**Comment by maitian352** [comment]
> When you you get stuck

Whaat
