### ISSUE TITLE
player shadow on top of lawn chair that player is not on top of

### ISSUE THREAD

**Issue by definitely-nobody-is-here** [maitian352/Meadow-Guarder#82]
![image](https://user-images.githubusercontent.com/67865358/141661212-2501bb5b-3307-492c-8f8f-27668ca57922.png)

**Comment by maitian352** [comment]
Just because your legs are not on top of the lawn chair, that doesn't mean your shadow is not on top of it. It's like saying the tree's shadow must be the trunk of the tree because otherwise the shadow will be on top of some ground/grass while the trunk is not.
