### ISSUE TITLE
In the map forest, some of the trees have no stumps!

### ISSUE THREAD

**Issue by Suvanth-Erranki** [maitian352/Meadow-Guarder#83]
Please add stumps!
![image](https://user-images.githubusercontent.com/63676047/98454155-2d416b00-2159-11eb-9621-affbd57e90ec.png)
![image](https://user-images.githubusercontent.com/63676047/98454167-4ea25700-2159-11eb-892b-dded01890b8c.png)

**Comment by maitian352** [comment]
These trees are behind the cave wall.

**Comment by Suvanth-Erranki** [comment]
Okay, but I would still consider fixing them because that just looks awkward.

**Comment by maitian352** [comment]
Can you change the title to forest instead of forrest?

**Comment by Suvanth-Erranki** [comment]
Ok.

**Comment by maitian352** [comment]
I don't think this looks awkward.

**Comment by Suvanth-Erranki** [comment]
Ok fine,
