### ISSUE TITLE
Monsters get stuck moving back and forth when they reach you.

### ISSUE THREAD

**Issue by definitely-nobody-is-here** [maitian352/Meadow-Guarder#83]
they get stuck going back and forth between two blocks
![image](https://user-images.githubusercontent.com/67865358/141661231-b9d82d24-e6e6-4ece-afc8-78e37f548869.png)

**Comment by Suvanth-Erranki** [comment]
This is a known glitch. This also happened I think in old meadow guarder

**Comment by maitian352** [comment]
Is there anything wrong with this?

**Comment by definitely-nobody-is-here** [comment]
> This is a known glitch. This also happened I think in old meadow guarder

No, the monsters would circle you

**Comment by definitely-nobody-is-here** [comment]
Also, this is not a glitch, it's a bug.

**Comment by maitian352** [comment]
> > This is a known glitch. This also happened I think in old meadow guarder
> 
> No, the monsters would circle you

This did happen in the old meadow guarder, back in november and december or so. Suvanth only played the very first versions of Meadow Guarder.

**Comment by definitely-nobody-is-here** [comment]
well, that's an old version and they don't work now.

**Comment by Suvanth-Erranki** [comment]
I just quickly changed the title to make it more specific if @definitely-nobody-is-here you don't mind.

**Comment by definitely-nobody-is-here** [comment]
please juet make them circle you or just stop walking when they get close enough to you
