### ISSUE TITLE
Sometimes when you do the secondary attack where the bullets fire out in a circle, even though you only click once, sometimes the circle of bullets fire 3 times.

### ISSUE THREAD

**Issue by Suvanth-Erranki** [maitian352/Meadow-Guarder#84]
This is a bug, the circle of bullets should only fire once if you right click once.
Here is a video of it happening to me - I actually didn't click more than once, I am serious.
https://drive.google.com/file/d/17T6iwvd6LfibtLC0c3ZymakNo5uX4P5W/view

**Comment by maitian352** [comment]
The secondary attack fires four rounds of circular bullets.
