### ISSUE TITLE
The Npc John tries to congratulates you on crossing the bridge once you do so. However, John congratulates you right before you cross the end of the bridge.

### ISSUE THREAD

**Issue by Suvanth-Erranki** [maitian352/Meadow-Guarder#85]
In this picture, I haven't reached the end of the bridge yet and John already says I crossed the bridge.
![image](https://user-images.githubusercontent.com/63676047/98470794-08dca180-21e0-11eb-88a7-577d4c6f4d50.png)

**Comment by maitian352** [comment]
Fixed.
