### ISSUE TITLE
For some reason, Bob has stopped talking to me.

### ISSUE THREAD

**Issue by Suvanth-Erranki** [maitian352/Meadow-Guarder#87]
I clicked on Bob and didn't talk. I went to the secret base to see if I was in the middle of a quest which was why Bob wouldn't talk to me, but I didn't start the quest. I have already done all the other quests and for some reason, the game wouldn't let Bob talk to me. I tried going out of the village and back in, but nothing worked.

Here is a video of me trying to talk to Bob, I am unsucessful.
https://drive.google.com/file/d/1znKS-X6yJP4or23qgA2qNxXQ6RnhWvmE/view

**Comment by maitian352** [comment]
You could have been doing another quest like Bridge.

**Comment by Suvanth-Erranki** [comment]
I wasn't doing any other quest.
