### ISSUE TITLE
None of the axes cut the trees for me

### ISSUE THREAD

**Issue by Suvanth-Erranki** [maitian352/Meadow-Guarder#87]
I tried with normal axes, pickaxes, waraxes, nothing works. I pointed and clicked on the trees. Is this a bug or am I doing something wrong?

**Comment by maitian352** [comment]
You have to make sure you are close enough to the tree and you have your tile selection on the base of the tree.

**Comment by maitian352** [comment]
![image](https://user-images.githubusercontent.com/68207888/141687716-0f1a87f1-4c1b-499f-a126-b816fb4969f2.png)
![image](https://user-images.githubusercontent.com/68207888/141687728-975fe0bc-3df5-40f6-8b98-3ef35a13e259.png)
![image](https://user-images.githubusercontent.com/68207888/141687725-5080914c-cb19-4a9b-9a87-fe6ee8e8835f.png)

**Comment by Suvanth-Erranki** [comment]
Let me show you what is happening for me:

**Comment by maitian352** [comment]
There is a minor bug. Just hold left click.

**Comment by maitian352** [comment]
Fixed.

**Comment by Suvanth-Erranki** [comment]
Ok.
