### ISSUE TITLE
Sometimes even if a monster has no health, it doesn't die.

### ISSUE THREAD

**Issue by Suvanth-Erranki** [maitian352/Meadow-Guarder#88]
![image](https://user-images.githubusercontent.com/63676047/98483853-56b6d100-2203-11eb-83b1-d9a1a57d3e75.png)

**Comment by maitian352** [comment]
The monster has 1 health so it doesn't die but it looks like it has no health.

**Comment by Suvanth-Erranki** [comment]
I think that maybe you should then add numbers to the player's and monster's health bar because that can be quite frustrating if it seems like a monster won't die at 0 health.

**Comment by maitian352** [comment]
But it could be confusing to the player how much health the monster actually has.

**Comment by Suvanth-Erranki** [comment]
MAITIAN!!!! Big breakthrough!!! I just discovered that this is a big glitch because I manually made the monster's health zero and it was still alive! Using the code: 

setInterval(function() { for(var i in Monster.list){Monster.list[i].hpMax = 0;} }, 1);

I made the monsters health 0 and they still moved around fired bullets and acted normally. Here is an image:

![image](https://user-images.githubusercontent.com/63676047/99137156-a1c84e00-2620-11eb-9fa1-6e1b976e56cd.png)

LOL - #ZombieMonsters ;)

**Comment by maitian352** [comment]
You made the maximum health zero, not the health.

**Comment by Suvanth-Erranki** [comment]
No, I made the monster's health zero. I knew the command for that.

**Comment by maitian352** [comment]
hpMax is maximum hp. Hp is current health.

**Comment by Suvanth-Erranki** [comment]
Yeah - I wrote hp

**Comment by maitian352** [comment]
No you wrote hpMax.

**Comment by maitian352** [comment]
> MAITIAN!!!! Big breakthrough!!! I just discovered that this is a big glitch because I manually made the monster's health zero and it was still alive! Using the code:
> 
> setInterval(function() { for(var i in Monster.list){Monster.list[i].hpMax = 0;} }, 1);
> 
> I made the monsters health 0 and they still moved around fired bullets and acted normally. Here is an image:

You wrote hpMax.

**Comment by Suvanth-Erranki** [comment]
I also wrote hp afterwards.

**Comment by maitian352** [comment]
I don't think so.

**Comment by Suvanth-Erranki** [comment]
I'll try again with setInterval(function() { for(var i in Monster.list){Monster.list[i].hp = 0;} }, 1);

**Comment by maitian352** [comment]
I tested the hp version on my local server, and it works fine.

**Comment by Suvanth-Erranki** [comment]
Okay let me check though.

**Comment by Suvanth-Erranki** [comment]
Fixed.
