### ISSUE TITLE
If you fire at a monster and just as your bullets are about to hit and kill the monster, if you leave the area, your bullet doesn't hit the monster even though it should.

### ISSUE THREAD

**Issue by Suvanth-Erranki** [maitian352/Meadow-Guarder#89]
I was somehow lucky enough to get a video of doing the glitch. Its very quick but at the end of the clip, you will see that just as I was about to kill the monster with my bullet, I went from the map river into the map bridge and the kill didn't happen. I know that the kill didn't happen because my XP didn't increase and if I kill a monster, it always does. Slow down the video to see the issue happen - the glitch happens at 0:11 seconds.

https://drive.google.com/file/d/1u7ETeN8op8Y6SMAMr8Z_rE_zIYUVvkRt/view

Also, here is the exact frame at which the bullet was about to hit the monster and I left:
![image](https://user-images.githubusercontent.com/63676047/98484073-e8730e00-2204-11eb-9040-51d87bf6cfce.png)

**Comment by maitian352** [comment]
The game only processes maps that have players in them so if you want the XP just don't leave the map.

**Comment by Suvanth-Erranki** [comment]
I know, but this is still a bug because let's say I was being fired upon by several monsters. Then, I wanted to get away and still get a kill for XP so as I hit the monster, I leave and find I didn't get the XP. So that would be understandably frustrating to the player.

**Comment by maitian352** [comment]
1. I don't think it will be frustrating if you lose a tiny bit of XP, because for every monster kill you get not much XP, and
2. It will be even more frustrating if the player was really laggy because the server processes every map.

**Comment by Suvanth-Erranki** [comment]
Okay sure - but you should put a disclaimer at the log in page to make
things easier.

**Comment by maitian352** [comment]
Ok.
