### ISSUE TITLE
If you keep the tab open too long it uses too much memory whiches causes your browser tries to clear up space and deletes the maps, resulting in the screen to be black.

### ISSUE THREAD

**Issue by rod0624** [maitian352/Meadow-Guarder#91]
When there is too much lag it will kick you out and when you join back in the screen will be black and you could see some things and you will have a lot of lag.

**Comment by maitian352** [comment]
This is actually a memory problem, where if you keep the tab open too long it uses too much memory. Then your browser tries to clear up space and deletes the maps, which causes the screen to be black.

**Comment by definitely-nobody-is-here** [comment]
this issue should be renamed to be more descriptive.

there should also be a template to make it easier to fill out useful bug reports
