### ISSUE TITLE
Skeleton king gets stuck.

### ISSUE THREAD

**Issue by Suvanth-Erranki** [maitian352/Meadow-Guarder#92]
Video: https://www.youtube.com/watch?v=A9_vciMnx2s

**Comment by Suvanth-Erranki** [comment]
Update: Right after I moved the player, it respawned me back in the village inn and said in the chat that Skeleton King had killed me.

**Comment by Suvanth-Erranki** [comment]
Update 2: It happened again. I think this is a collision glitch since the skeleton king is always getting stuck at a tree.

**Comment by maitian352** [comment]
yeah
its a pathfinding glitch
it moves one pixel too little and gets stuck on the tree.

**Comment by Suvanth-Erranki** [comment]
![image](https://user-images.githubusercontent.com/76885647/142338925-73242018-c70a-4fc9-b3d9-456c5b67a85a.png)

**Comment by Suvanth-Erranki** [comment]
Tutorial on trapping Skeleton King:
1. Go to Skeleton King.
2. Get him to chase you tothe spot in between the 3 trees in the photo where Skeleton King is now trapped.
3. Once both of you are there, let him kill you.
4. When you respawn, he will be there, stuck and unable to move or shoot bones. Hilarious.

**Comment by definitely-nobody-is-here** [comment]
> 4. When you respawn, he will be there, stuck and unable to move or shoot bones. Hilarious.

It seems like once you die, the skeleton king deaggros, and when it reaggros it thinks it is stuck in a tile or something. It could also be that it's just too dumb to get back out since the pathfinding has no way of knowing how big the entity it controls is.
Not shooting bones, that's weird. either they instantly get deleted since they are shot into collisions or it can't shoot because the aggro is broken; try walking over to the other side and see if it tries to shoot you.

**Comment by Suvanth-Erranki** [comment]
I walked over to the other side. He still can't shoot me. Skeleton King can't shoot me in any direction.

**Comment by Suvanth-Erranki** [comment]
I did the glitch again:
![image](https://user-images.githubusercontent.com/76885647/142341549-9ce9e961-125e-456b-a3bd-d64733ba2f1b.png)
This leads me to believe that sometimes when the Skeleton King is stuck, it is stuck in an angle where all the bones it shoots fades out. However, in this scenario, the Skeleton King is able to shoot bones that don't fade away, hence we see him shooting.

**Comment by definitely-nobody-is-here** [comment]
the skeleton king wasn't aggroed on you last time for some reason, this time it is.

**Comment by Suvanth-Erranki** [comment]
I did it again:
![image](https://user-images.githubusercontent.com/76885647/142343181-cdf2ac5e-80e7-4002-b650-e4a07bdcbd4d.png)
This time it wasn't aggroed on me.

**Comment by maitian352** [comment]
I believe this is fixed. Reopen if it still happens.

**Comment by Suvanth-Erranki** [comment]
This still is happening. I have a video.

**Comment by maitian352** [comment]
Fixed. I didn't commit yet though.
