### ISSUE TITLE
Sometimes monsters don't die when you fire at them.

### ISSUE THREAD

**Issue by Suvanth-Erranki** [maitian352/Meadow-Guarder#93]
View this video to see the glitch:
https://drive.google.com/file/d/1-aKxK6wdLqcDv81dTsfukpa31nVqkGSY/view
Note: I could kill every monster around the area except for that monster.

**Comment by maitian352** [comment]
This bug is a duplicate of [this](https://github.com/maitian352/Meadow-Guarder/issues/73).

**Comment by maitian352** [comment]
Fixed.

**Comment by Suvanth-Erranki** [comment]
Great job Maitian!
