### ISSUE TITLE
Add a Meadow Guarder username and password blacklist

### ISSUE THREAD

**Issue by Suvanth-Erranki** [maitian352/Meadow-Guarder#94]
Some usernames are not very appropriate:
![image](https://user-images.githubusercontent.com/76885647/142332762-5687a1a6-5bfb-4234-8b95-b47841cb910c.png)

Add a black list that prevents people from creating accounts that have innappropriate names and delete the ones that do.

**Comment by definitely-nobody-is-here** [comment]
is it really hard? make an array of banned things. and for each item in the array check if the username includes that banned item. not hard.

**Comment by maitian352** [comment]
> is it really hard? make an array of banned things. and for each item in the array check if the username includes that banned item. not hard.

Like what banned things?

**Comment by Suvanth-Erranki** [comment]
> > is it really hard? make an array of banned things. and for each item in the array check if the username includes that banned item. not hard.
> 
> Like what banned things?

Exactly. Should we have to come up with a list of every single bad word/phrase? That's tedious and difficult.

**Comment by definitely-nobody-is-here** [comment]
well its better than  leaving this issue open and not doing anything

**Comment by maitian352** [comment]
![image](https://user-images.githubusercontent.com/68207888/143801487-6520b53a-55ea-432d-825f-306db6f34330.png)
Does this count?
