### ISSUE TITLE
You can shoot bullets through players but not npc's

### ISSUE THREAD

**Issue by maitian352** [maitian352/Meadow-Guarder#95]
![image](https://user-images.githubusercontent.com/68207888/98587917-d80c7300-2298-11eb-8574-341a9181fd05.png)
Here is an image of it. I couldn't get the perfect shot, but the bullet would have gone through my body.

**Comment by maitian352** [comment]
Actually this isn't a bug, because the players aren't hurting each other.

**Comment by Suvanth-Erranki** [comment]
Okay.
