### ISSUE TITLE
When I tried to login, the website didn't display the game yet it displayed the inventory! Extremely weird glitch! Please fix soon!

### ISSUE THREAD

**Issue by Suvanth-Erranki** [maitian352/Meadow-Guarder#95]
Video: https://www.youtube.com/watch?v=Sixd-zMrOw8

**Comment by Suvanth-Erranki** [comment]
This only happened once to me just now.

**Comment by maitian352** [comment]
Whenever you post a glitch, please also post a screenshot of the console.

**Comment by definitely-nobody-is-here** [comment]
why don't you add an issue template?

**Comment by Suvanth-Erranki** [comment]
If this happens to me again, I will screenshot the console.

**Comment by maitian352** [comment]
This seems like the server restarted right as you were logging on, which prevented the player data from reaching your client, and creating this bug.

**Comment by Suvanth-Erranki** [comment]
I found this issue. This happens when window.requestAnimationFrame = undefined

However, I didn't execute this code, so I don't understand why this happened.

**Comment by maitian352** [comment]
Fixed.
