### ISSUE TITLE
Logging out of the game twice without logging back in!

### ISSUE THREAD

**Issue by Suvanth-Erranki** [maitian352/Meadow-Guarder#96]
![image](https://user-images.githubusercontent.com/76885647/142340473-2a39a1b3-6173-46ae-b1bf-df5d33a476af.png)
I think this glitch was present in an old version of old Meadow Guarder. I remember logging in 3 times in a row to show the glitch.

**Comment by Suvanth-Erranki** [comment]
I found the old glitch:
![image](https://user-images.githubusercontent.com/76885647/142340995-bc224653-2257-47a0-a11a-7b3abd743921.png)
https://github.com/maitian352/Meadow-Guarder-old/issues/120
https://github.com/maitian352/Meadow-Guarder-old/issues/46

However, in those issues, the reason this happened was because the user spammed login too quickly. I don't think that is the issue for this version of the game.

**Comment by definitely-nobody-is-here** [comment]
oh yeah earlier i was spamming the login button to get that weird game GUI on the menu. guess I accidentally found a bug.

**Comment by definitely-nobody-is-here** [comment]
https://github.com/maitian352/Meadow-Guarder/issues/95

**Comment by maitian352** [comment]
Fixed.
