### ISSUE TITLE
Sometimes, items look like they have spawned inside of tress (which doesn't look very good or is realistic)

### ISSUE THREAD

**Issue by Suvanth-Erranki** [maitian352/Meadow-Guarder#98]
![image](https://user-images.githubusercontent.com/76885647/142518117-c1cbd801-2bdb-469e-807a-fc34207b590f.png)
This may not necessarily be a bug, but can you like stop this from happening. It's just weird.

**Comment by maitian352** [comment]
Fixed. If there is no spot to spawn the item other than in a collision, it will spawn the item in a collision.
