### ISSUE TITLE
There is an arrow in the map forrest which doesn't lead to any other area yet.

### ISSUE THREAD

**Issue by Suvanth-Erranki** [maitian352/Meadow-Guarder#99]
I hope you will add the path from the map forest to somewhere elese through this arrow soon:
![image](https://user-images.githubusercontent.com/63676047/98819179-76790f80-2424-11eb-9299-c449e3f8c3da.png)

**Comment by maitian352** [comment]
You typed forrest again.

**Comment by Suvanth-Erranki** [comment]
Aw man.

**Comment by maitian352** [comment]
This shouldn't be an issue, because there are lots of arrows that don't lead anywhere yet.

**Comment by Suvanth-Erranki** [comment]
Okay.

**Comment by maitian352** [comment]
You made two typos.
