### ISSUE TITLE
I died by committing suicide with the death weapon, but only the respawn message showed up, not the death message.

### ISSUE THREAD

**Issue by Suvanth-Erranki** [maitian352/Meadow-Guarder#99]
![image](https://user-images.githubusercontent.com/76885647/142554960-57e61934-d0bf-4e2a-a1e9-d75da11ad379.png)
I was using instant respawn, so I think that's reason for this glitch.

**Comment by maitian352** [comment]
Fixed. This was because you had exactly 100 health, and the system treats hp like mana, and allows you to be at 0 health without dying. This then triggers auto respawn, which respawns you.
